### ISSUE TITLE
Queue transaction related messages in charge point when it is offline.

### ISSUE THREAD

**Issue by elchupokabrapolisetty** [mobilityhouse/ocpp#10]
Hi!

Was wondering if the library has a function for message queuing and dequeuing for use in a charge_point.

Also is this meant to be used for a charge_system only? or can a client be developed using this library in a system such as the beaglebone black?

thanks in advance

**Comment by OrangeTux** [comment]
> Was wondering if the library has a function for message queuing and dequeuing for use in a charge_point.

I am not sure if you need queues. I think there are 2 places where you might expect queues: a queue for receiving messages and a queue for messages that needs to be send.

I think the 'receive queue' is a responsibility of the websocket library you are using. This library only iterates over the all received messages and process them using the following code in [ocpp.v16.charge_point.ChargePoint](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v16/charge_point.py#L125-L130):

``` python
    async def start(self):
        while True:
            message = await self._connection.recv()
            LOGGER.info('%s: receive message %s', self.id, message)

            await self.route_message(message)
``` 

Regarding the 'send queue': the OCPP specification doesn't allow to send multiple CALLs to an other party before the previous CALLs are answered or have timed out.  From the Open Charge point Protocol JSON 1.6 specification:

> A Charge Point or Central System SHOULD NOT send a CALL message to the other party unless all the CALL messages it sent before have been responded to or have timed out. 

This library implements flow control to satisfy this requirement. If 2 tasks at the same time try to send a call using [ChargePoint.call](https://github.com/mobilityhouse/ocpp/blob/f807cbaffc48c7e115ce7e3f92266b1b82b1a614/ocpp/v16/charge_point.py#L218) only 1 can obtain a lock  that is required to send the CALL. If this task has received an answer or his request timed out he will release the lock and the second task can obtain it to send it's request.

> Also is this meant to be used for a charge_system only?

No, you can use it also to create charge points. See the example at [examples/charge_point.py](https://github.com/mobilityhouse/ocpp/blob/master/examples/charge_point.py).

This example implements a very minimal charge point that connects to the central system and sends a BootNotification.

> or can a client be developed using this library in a system such as the beaglebone black?

You can use it to create an application on the BeagleBone Black.

**Comment by elchupokabrapolisetty** [comment]
Hi!

thank you for really prompt response!
What i meant by using a queue/dequeue system is for the chargepoint in case of loss network connectivity, as all transaction related messages have to be stored and sent once the charge point connects back to the system.That was the reasoning for my initial question. 

Ps:(I am also really new to ocpp so please forgive me if Ive interpreted anything incorrectly)

Regards

**Comment by OrangeTux** [comment]
> What i meant by using a queue/dequeue system is for the chargepoint in case of loss network connectivity, as all transaction related messages have to be stored and sent once the charge point connects back to the system.

You're correct,  that is true. Currently it is not supported. But it is definitely something this library should support. Thanks for bringing it up!

**Comment by chargeguy** [comment]
Hi! 

Is the offline behaviour (considering the configuration parameters TransactionMessageAttempts and TransactionMessageRetryInterval and queueing of messages) already supported now in the library? 

Best regards!

**Comment by Jared-Newell-Mobility** [comment]
As this has gone stale and the queuing of messages is likely to be specific to the implementation of the charge point (specifically handing of transaction id's in 1.6) - I'll close this
