### ISSUE TITLE
Return CallError if Call fails to unpack.

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#102]
For every message `ocpp.ChargePoint` receives `ocpp.messages.unpack()` is called. See https://github.com/mobilityhouse/ocpp/blob/master/ocpp/charge_point.py#L135-L140

If unpacking fails `ChargePoint.start()` crashes with the exception thrown in `unpack()`. Depending on how `ChargePoint` is used the connection to the charger might be closed as well. See #101 . 

Instead of crashing the `ChargePoint` an CallError could be returned if a Call is received that fails to `unpack()`. That will inform the charger about the problem and the connection stays in tact.

Not sure what to do with CallResult that fail to `unpack()`. We could return CallErrors on CallResults as well, I've seen at least 1 charger that implemented OCPP like that. But I'm afraid that the OCPP specification doesn't have a mechanism to inform the other party that it send an invalid CallResult. So returning CallErrors on CallResults would violate the specification.

**Comment by OrangeTux** [comment]
Good addition @DColadas. I totally agree.

**Comment by jainmohit2001** [comment]
Closing this.
We are logging the error if `unpack` fails with an exception of `OCPPError`. 
https://github.com/mobilityhouse/ocpp/blob/d59ecf140eead945b234745d956d142c79a3816d/ocpp/charge_point.py#L255
