### ISSUE TITLE
Offline behaviour (TransactionMessageAttempts / TransactionMessageRetryInterval / Queueing)

### ISSUE THREAD

**Issue by chargeguy** [mobilityhouse/ocpp#103]
Hi!

Is the OCPP offline behaviour (considering the configuration parameters TransactionMessageAttempts and TransactionMessageRetryInterval and queueing of messages) already supported in the library?

Best regards!

**Comment by jr-tactiq** [comment]
Did you ever resolve this question?

It is related to my question #119 about handling loss of connection to the server
