### ISSUE TITLE
Implement way to allow users to handle CallErrors

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#104]
Currently `ChargePoint.call()` returns `None` when the remote end returns a `CallError`. That is because [`ChargePoint.call()`](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/charge_point.py#L258-L260) silences the `CallError`.

This is problematic when one wants to act upon receiving a `CallError`. 

I'm not sure yet how and where to change the code so one can handle `CallError`s. The easiest way is to change the body of `ChargePoint.call()` to this:

``` python
if response.message_type_id == MessageType.CallError:
    raise response.to_exception()  
```

But this change is not backwards compatible. In existing code bases one users of this library might need to wrap all there calls to `ChargePoint.call()` inside try/except to avoid their code from breaking, like:

``` python
try:
   self.call(call.HeartbeatPayload())
except ocpp.exceptions.OCPPError as e:
   pass
```

**Comment by OrangeTux** [comment]
In order to main backwards compatibility I suggest to add a keyword argument `suppress` to `ChargePoint.call()` that defaults to `True.

**Comment by tropxy** [comment]
Fixed in Raise exception if response from call() is CallError #124
