### ISSUE TITLE
Can I catch websockets exception?

### ISSUE THREAD

**Issue by JavanWang** [mobilityhouse/ocpp#11]
HI,
I try to catch an exception "Connection reset by peer" when server-client is on heartbeat phase;
unfortunately, I can not get the exception of websockets object via class ChargePoint.
How can I do?
Thanks
I try to modify the code like this

``` python

    async def start(self):
        while True:
            try:
                message = await self._connection.recv()
                LOGGER.info('%s: receive message %s', self.id, message)               
                await self.route_message(message)
            except self._connection.exceptions as e: #fail
                print('websockets.exceptions')
            except IOError as err:
                print(self.id, 'disconnected')
            finally:
                pass
```

error message like this
`File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054]`
and
`websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason`

**Comment by OrangeTux** [comment]
Hello @JavanWang.

A couple of things. First you don't need to patch the `start()` method to catch exceptions raised by in the websockets layer.

Second catching `self._connection.exceptions` is not possible because `self_connection.exceptions` is not an exception. 

Here an example of an of a client that catches an `websockets.exceptions.ConnectionClosed` error:

``` python
import asyncio
import websockets

from ocpp.v16 import call
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import RegistrationStatus


class ChargePoint(cp):
    async def send_boot_notification(self):
        request = call.BootNotificationPayload(
            charge_point_model="Optimus",
            charge_point_vendor="The Mobility House"
        )

        response = await self.call(request)

        if response.status ==  RegistrationStatus.accepted:
            print("Connected to central system.")


async def main():
    async with websockets.connect(
        'ws://localhost:9000/CP_1',
         subprotocols=['ocpp1.6']
    ) as ws:

        cp = ChargePoint('CP_1', ws)

        try:
            await asyncio.gather(cp.start(), cp.send_boot_notification())
        except websockets.exceptions.ConnectionClosed as e:
            print(e)

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by JavanWang** [comment]
> Hello @JavanWang.
> 
> A couple of things. First you don't need to patch the `start()` method to catch exceptions raised by in the websockets layer.
> 
> Second catching `self._connection.exceptions` is not possible because `self_connection.exceptions` is not an exception.
> 
> Here an example of an of a client that catches an `websockets.exceptions.ConnectionClosed` error:
> 
> ```python
> import asyncio
> import websockets
> 
> from ocpp.v16 import call
> from ocpp.v16 import ChargePoint as cp
> from ocpp.v16.enums import RegistrationStatus
> 
> 
> class ChargePoint(cp):
>     async def send_boot_notification(self):
>         request = call.BootNotificationPayload(
>             charge_point_model="Optimus",
>             charge_point_vendor="The Mobility House"
>         )
> 
>         response = await self.call(request)
> 
>         if response.status ==  RegistrationStatus.accepted:
>             print("Connected to central system.")
> 
> 
> async def main():
>     async with websockets.connect(
>         'ws://localhost:9000/CP_1',
>          subprotocols=['ocpp1.6']
>     ) as ws:
> 
>         cp = ChargePoint('CP_1', ws)
> 
>         try:
>             await asyncio.gather(cp.start(), cp.send_boot_notification())
>         except websockets.exceptions.ConnectionClosed as e:
>             print(e)
> 
> if __name__ == '__main__':
>     asyncio.run(main())
> ```

Sorry, I don't express it clearly. 
The scenario is an ocpp server connects with an ocpp client when the client disconnected the server, the server needs to raise an exception to notify backend staff to do something. 
I need to catch this exception message on the server side when I off-line the client network.
the error exception as below

``
Error in connection handler
Traceback (most recent call last):
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 674, in transfer_data
    message = yield from self.read_message()
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 742, in read_message
    frame = yield from self.read_data_frame(max_size=self.max_size)
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 815, in read_data_frame
    frame = yield from self.read_frame(max_size)
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\protocol.py", line 884, in read_frame
    extensions=self.extensions,
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\site-packages\websockets\framing.py", line 99, in read
    data = yield from reader(2)
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 679, in readexactly
    await self._wait_for_data('readexactly')
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\asyncio\streams.py", line 473, in _wait_for_data
    await self._waiter
  File "C:\Users\W8-PC\AppData\Local\Programs\Python\Python37\lib\asyncio\selector_events.py", line 801, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [WinError 10054]
``

**Comment by OrangeTux** [comment]
So if I understand correctly you want to know when a client disconnects from the central system.

That can be done the same as I demonstrated with in my previous example. The key is to wrap the `cp.start()` with a exception handler. For the central system it could look like this:

``` python
import asyncio
import websockets
from datetime import datetime

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus
from ocpp.v16 import call_result


class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notitication(self, charge_point_vendor, charge_point_model, **kwargs):
        return call_result.BootNotificationPayload(
	    current_time=datetime.utcnow().isoformat(),
	    interval=10,
	    status=RegistrationStatus.accepted
	)


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint instance
    and start listening for messages.

    """
    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    try:
        await cp.start()
    except websockets.exceptions.ConnectionClosed:
        print("Inform someone that this client has closed.")


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    await server.wait_closed()


if __name__ == '__main__':
    asyncio.run(main())
```

Does this answer your question?

**Comment by JavanWang** [comment]
This is totally my needs
thank you very much

**Comment by OrangeTux** [comment]
Happy to help! I will open this ticket now. Feel free to open a new one if you have more questions.

**Comment by Buco11-dev** [comment]
Hey @OrangeTux I know this issue is closed but I was wondering if you could help me with something similar to your answer above to monitor a web3 node WebSocket connection in the background while the rest of the code runs and can auto-reconnect when it disconnects.

Here's how I connect currently:
```
from web3 import Web3

web3 = Web3(Web3.WebsocketProvider(node, websocket_timeout=60))
try:
        if web3.isConnected():
            print("Successfully connected to network")
    except Exception as error:
        print(f"[Connection Error]: {error}")
 ```
 Thanks in advance!
