### ISSUE TITLE
Make casing of enum members consistent

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#114]
The casing for members of enums in `ocpp.v16.enums` is inconsistent. 

It contains PascalCase...

``` python
class Action:
    Authorize = "Authorize"
    BootNotification = "BootNotification"
```

...camelCase...

``` python
class ChargePointErrorCode:
    connectorLockFailure = "ConnectorLockFailure"
```

... and lowercase

``` python
class ChargingProfilePurposeType(str, Enum):
    chargepointmaxprofile = "ChargePointMaxProfile"
```

I suggest to use snake_case for all members. To maintain backwards compatibility I suggest to mark all non_snake_case members with a deprecation warning.

**Comment by lsaavedr** [comment]
snake_case is suggest by pylint also
