### ISSUE TITLE
colaboration

### ISSUE THREAD

**Issue by maksyutovrv** [mobilityhouse/ocpp#120]
Hi,
I'm looking for a person who could help with OCPP implementation on the product and would like to talk to you. Feel free to send me a message to maksyutovrv@gmail.com

thanks,
Rinat

**Comment by OrangeTux** [comment]
What kind of questions do you have? Can't we discuss it here so everyone can learn from it?

**Comment by OrangeTux** [comment]
Closed due inactivity.
