### ISSUE TITLE
EVlink Smart Wallbox and OCPP 1.6

### ISSUE THREAD

**Issue by jatty** [mobilityhouse/ocpp#122]
When trying to use ocpp with a Schneider Electric EVlink Smart Wallbox and OCPP 1.6 with the following code snippet:

```
#!/usr/bin/env python3
# https://pypi.org/project/ocpp/

import asyncio
import logging
import websockets
from datetime import datetime

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus
from ocpp.v16 import call_result

logging.basicConfig(level=logging.INFO)

class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notitication(self, charge_point_vendor, charge_point_model, **kwargs):
      return call_result.BootNotificationPayload(
        current_time=datetime.utcnow().isoformat(),
          interval=10, status=RegistrationStatus.accepted)

async def on_connect(websocket, path):
    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    await cp.start()

async def main():
    server = await websockets.serve(on_connect, '0.0.0.0', 8180,
        subprotocols=['ocpp1.5'])
    await server.wait_closed()

if __name__ == '__main__':
    asyncio.run(main())
```

I get the error:

```
Failed validating 'maxLength' in schema['properties']['chargePointSerialNumber']:
    {'maxLength': 25, 'type': 'string'}
```

**Comment by OrangeTux** [comment]
The charger seems to be sending an OCPP message that doesn't follow the specification: the field 'chargePointSerialNumber' is to long. Can you provide the message send by the charger?

**Comment by jatty** [comment]
The payload is:

`{'chargeBoxSerialNumber': 'EVBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 'chargePointModel': 'EVlink Smart Wallbox', 'chargePointSerialNumber': '3N180xxxxxxxxxxxxxxxxxxxxx', 'chargePointVendor': 'Schneider Electric', 'firmwareVersion': '3.3.0.12'}`

**Comment by jatty** [comment]
After deploying the patch, it works:

INFO:ocpp:CP1: receive message [2,"1","BootNotification",{"chargeBoxSerialNumber":"EVBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","chargePointModel":"EVlink Smart Wallbox","chargePointSerialNumber":"3N180840566A1S1B7551700016","chargePointVendor":"Schneider Electric","firmwareVersion":"3.3.0.12"}]
INFO:ocpp:CP1: send [3,"1",{"currentTime":"2020-10-04T17:34:19.689660","interval":10,"status":"Accepted"}]
INFO:ocpp:CP1: receive message [2,"2","StatusNotification",{"connectorId":11,"errorCode":"NoError","status":"Available","timestamp":"2020-10-04T15:34:21Z"}]
INFO:ocpp:CP1: send [3,"2",{}]
INFO:ocpp:CP1: receive message [2,"3","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"3",{"currentTime":"2020-10-04T17:34:34Z"}]
INFO:ocpp:CP1: receive message [2,"4","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"4",{"currentTime":"2020-10-04T17:34:44Z"}]
INFO:ocpp:CP1: receive message [2,"5","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"5",{"currentTime":"2020-10-04T17:34:54Z"}]
INFO:ocpp:CP1: receive message [2,"6","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"6",{"currentTime":"2020-10-04T17:35:04Z"}]
INFO:ocpp:CP1: receive message [2,"7","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"7",{"currentTime":"2020-10-04T17:35:14Z"}]

**Comment by jatty** [comment]
After deploying the patch, it works:

INFO:ocpp:CP1: receive message [2,"1","BootNotification",{"chargeBoxSerialNumber":"EVBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","chargePointModel":"EVlink Smart Wallbox","chargePointSerialNumber":"3N1xxxxxxxxxxxxxxxxxxxxxxx","chargePointVendor":"Schneider Electric","firmwareVersion":"3.3.0.12"}]
INFO:ocpp:CP1: send [3,"1",{"currentTime":"2020-10-04T17:34:19.689660","interval":10,"status":"Accepted"}]
INFO:ocpp:CP1: receive message [2,"2","StatusNotification",{"connectorId":11,"errorCode":"NoError","status":"Available","timestamp":"2020-10-04T15:34:21Z"}]
INFO:ocpp:CP1: send [3,"2",{}]
INFO:ocpp:CP1: receive message [2,"3","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"3",{"currentTime":"2020-10-04T17:34:34Z"}]
INFO:ocpp:CP1: receive message [2,"4","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"4",{"currentTime":"2020-10-04T17:34:44Z"}]
INFO:ocpp:CP1: receive message [2,"5","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"5",{"currentTime":"2020-10-04T17:34:54Z"}]
INFO:ocpp:CP1: receive message [2,"6","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"6",{"currentTime":"2020-10-04T17:35:04Z"}]
INFO:ocpp:CP1: receive message [2,"7","Heartbeat",{}]
INFO:ocpp:CP1: send [3,"7",{"currentTime":"2020-10-04T17:35:14Z"}]
