### ISSUE TITLE
Create router map doesnt work well with properties

### ISSUE THREAD

**Issue by fa1k3n** [mobilityhouse/ocpp#137]
`If` you have a class containing properties the getters are called when the ocpp library is building its route map since it iterates att the attributes in the object

in router.py

  ```
   for attr_name in dir(obj):
         attrib = getattr(obj, attr_name)    
```   

The problem is with the getattr call, if this is a property it will then actually call the getter method, which in most cases is unwanted. 

One solution that I have found is to have a global list in router.py that contains all the routables. The on and after decorators can then append the method name to this list. Then during the call to create router map instead of iterating the object attributes this list can be iterated

**Comment by OrangeTux** [comment]
Hello. thanks for the report. I tried reproduce the problem as you described in a minimal example, but I failed. Can you show some code that show the problem?

**Comment by fa1k3n** [comment]
Sure , it should be sufficient to add to the basic example 

@property
def foo(self):
    raise Exception(“this will be thrown when router is set up”)

But I need to unpatch my fixed version of the library to verify that. Will test tomorrow and get back with minimal example

**Comment by fa1k3n** [comment]
Here is a minimal unittest that will provoke the error and thus fail

import unittest                                                                                                                               
from ocpp.v20 import ChargePoint as cp                                                                                                        
                                                                                                                                              
class ChargePoint(cp):                                                                                                                        
    @property                                                                                                                                 
    def foo(self):                                                                                                                            
        raise Exception("this will fail")                                                                                                     
                                                                                                                                              
class TestChargePoint(unittest.TestCase):                                                                                                     
    def test_setters_should_not_be_called_during_routemap_setup(self):                                                                        
        try:                                                                                                                                  
            ChargePoint("blah", None)                                                                                                         
        except Exception as e:                                                                                                                
            self.assertEqual(str(e), "this will fail")                                                                                        
            self.fail("Setter was called during ChargePoint creating")                                                                        
        self.assertTrue(True)                                                                                                                 
                                                                                                                                              
if __name__ == '__main__':                                                                                                                    
    unittest.main()

**Comment by OrangeTux** [comment]
Thanks for the code. I was able to reproduce the error.

**Comment by fa1k3n** [comment]
> Thanks for the code. I was able to reproduce the error.

excellent, do you want me to do a PR for my solution?

**Comment by OrangeTux** [comment]
Sure! It would be great.

**Comment by fa1k3n** [comment]
just did it, all tests passed locally, CI is running right now
