### ISSUE TITLE
Update Schema from OCPP 2.0.1

### ISSUE THREAD

**Issue by OSkrk** [mobilityhouse/ocpp#139]
Apparently JSON Schemas from last realease OCPP 2.0.1 are not yet updated

**Comment by OrangeTux** [comment]
What do you mean exactly? Which version of the schemas do you think we should be used?

**Comment by OSkrk** [comment]
Last version of OCPP 2.0.1 has been published in mars 2020 (and replace OCPP 2.0) having modification to json schemas.

See:
https://www.openchargealliance.org/downloads/

**Comment by OrangeTux** [comment]
[We just added support for OCPP 2.0.1](https://github.com/mobilityhouse/ocpp/tree/master/ocpp/v201), I believe that uses the correct schemas. Can you confirm that?

**Comment by OSkrk** [comment]
Yes, I did not have that in local repo. Sorry.

**Comment by tropxy** [comment]
Closed due to question answered
