### ISSUE TITLE
OCPP 1.6 Security White Paper Ed 2

### ISSUE THREAD

**Issue by tropxy** [mobilityhouse/ocpp#141]
Add support for the Security OCPP messages of the 2nd Edition of the white paper
[JSON_schemas.zip](https://github.com/mobilityhouse/ocpp/files/5419159/JSON_schemas.zip)
[OCPP 1.6 security whitepaper edition 2.pdf](https://github.com/mobilityhouse/ocpp/files/5419160/OCPP.1.6.security.whitepaper.edition.2.pdf)

**Comment by villekr** [comment]
Does the attached JSON_schemas.zip contain official json schema files from Open Charge Alliance? I was searching for them but they weren't included in ocpp 1.6 specification bundle.

**Comment by OrangeTux** [comment]
Here they are: 
[Uploading JSON_schemas.zip…]()
