### ISSUE TITLE
ChangeAvailabilityPayload incorrect?

### ISSUE THREAD

**Issue by danielbons** [mobilityhouse/ocpp#147]
According to the OCPP 1.6 manual:

A ChangeAvailability.req should include the connector ID and an AvailabilityType while the response from the Charging Station should include AvailabilityStatus. See image below

![ocpp_change_availability](https://user-images.githubusercontent.com/44609193/97403997-accb7080-18f5-11eb-85ff-4a76c222f7e7.png)

The file ocpp/v16/call.py contains:
```
@dataclass
class ChangeAvailabilityPayload:
    connector_id: int
    type: AvailabilityStatus
```

And ocpp/v16/call_result.py contains:
```
@dataclass
class ChangeAvailabilityPayload:
    status: AvailabilityStatus
```

AvailabilityStatus an AvailabilityType is defined in ocpp/v16/enums.py as follows
```
class AvailabilityStatus(str, Enum):
    """
    Status returned in response to ChangeAvailability.req.
    """

    accepted = "Accepted"
    rejected = "Rejected"
    scheduled = "Scheduled"


class AvailabilityType(str, Enum):
    """
    Requested availability change in ChangeAvailability.req.
    """

    inoperative = "Inoperative"
    operative = "Operative"
```

When checking the references for AvailabilityStatus and AvailabilityType, I noticed that AvailabilityType is never referenced while AvailabilityStatus is referenced in both call.py and call_result.py as described above. Shouldn't ChangeAvailabilityPayload be as follows?
```
@dataclass
class ChangeAvailabilityPayload:
    connector_id: int
    type: AvailabilityType
```

**Comment by OrangeTux** [comment]
Thanks! You're right, it's a bug.
