### ISSUE TITLE
Typo in Readme.rst

### ISSUE THREAD

**Issue by henbier** [mobilityhouse/ocpp#161]
Hi,
I'm working with OCPP for a few weeks now and I just noticed this due to PyCharm telling me.
There is a typo in the Readme - Quick start - Central system section.
It says on_boot_noti-t-ication instead of noti-f-ication.

class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notitication(self, charging_station, reason, **kwargs):
    ...

I really don't want to be annoying, I just thought you would want to know :)
Keep up the great support 👍

**Comment by OrangeTux** [comment]
Thanks for reporting @henbier
