### ISSUE TITLE
Help needed for first use

### ISSUE THREAD

**Issue by SmartTransp** [mobilityhouse/ocpp#175]
Hello 
I wnat to know how can I "save" the incoming data 

now I have added in the charge_point.py line 161
        print ('this is what I get - ' , msg)
so when the code run , I can see the message from the charger 

how can I see it from the main code ?
so I can save it to my logs?

Thanks,

**Comment by OrangeTux** [comment]
From what I understand you want to save the logs of this library to a file, correct?

You can hook up a [`FileHandler`](https://docs.python.org/3/library/logging.handlers.html#logging.FileHandler) to to the `ocpp` logging handler.

Something like so:

``` python
 ocpp_logger = logging.getLogger('ocpp')
ocpp_logger.setLevel(level=logging.DEBUG)
file_handler = logging.FileHandler("/tmp/ocpp.log")

ocpp_logger.addHandler(file_handler)
```

**Comment by SmartTransp** [comment]
not quite
I want to save the incoming data that the charger send and make my own work according to the data  , then send it to my DB 
I want to save the websocket incoming data as a string 

also (somehow related ) 
can I send command to the charger ?
right now I get hearbeat once every 10 seconds 
can I send to it in reply  to do a reset 
ot to send me a the boot notifiction of it ?

Thanks,

**Comment by OrangeTux** [comment]
>  I want to save the websocket incoming data as a string

You can write your own websocket adapter that does that. See PR #181 that I just created to explain that.

I'm not entirely sure what you meant by the rest of your comment. I guess you want to create a CSMS. And that
CSMS should also send some OCPP requests to a connected charger. Is my understanding correct?

You can use `ChargePoint.call()` to send OCPP requests.  However, you can't use [`ChargePoint.call()`](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/charge_point.py#L227-L283) inside a [`@on()`](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/routing.py#L6-L55) handler as that causes a deadlock. So you should use the [`@after()`](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/routing.py#L58-L80) handler for that.

**Comment by SmartTransp** [comment]
thank you for the answer 

but I didn;t understand 
how do I add the "websocket adapters" while running your code\project?

where do I need to add it ?

```
async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        6005,
        subprotocols=['ocpp1.6']
    )

    await server.wait_closed()
```

I want everything will work as it right now.


also where do I need to put the  @after()  ?
in the chargepoint class?
can you show me a simple example of sending soft reset to the charger?

Thanks,

**Comment by analge-hk** [comment]
You are defining reboot_charger but not executing by calling. Move the define outside and use self.reboot_charger in @after.
