### ISSUE TITLE
Ignoring message with unknown unique ID in ChargePoint.call function

### ISSUE THREAD

**Issue by ToasterUwU** [mobilityhouse/ocpp#179]
I have an issue with the call function. 

I have to run it in a different thread because I use fastapi to make a API. This blocks the Thread, but the WebSocket server for OCPP also blocks the Thread.

Because these are different threads, I ran into the issue that I cant call the async function .call of the ChargePoint Object within my API thread (the main thread), because the function belongs to the event loop of the OCPP thread.

I made myself a custom function for calling the CPs:
```py
def call(self, cp_id, call_obj):
    async def start(cp_id, call_obj):
        response = await self._cps[cp_id].call(call_obj)
        self._cps[cp_id].add_message("Response", response)
    
    loop = self._cps[cp_id].loop()
    asyncio.run_coroutine_threadsafe(start(cp_id, call_obj), loop=loop)
```

I get the event loop of the Chargepoint Object, i run asyncio.run_coroutine_threadsafe to run the call in the right loop, i use .add_message to add the response to my list with responses.

But i dont get the response into the var, because i get a logging.error() message that says: 
`ERROR:ocpp:Ignoring response with unknown unique id: <CallResult - unique_id=...`

Hope this issue can be fixed.
Im stuck with that. So if anyone has a idea how to get around the issue or how to call the .call function in the API thread, it would be greatly appreciated.

**Comment by OrangeTux** [comment]
I'll dig into this later. But I won't recommend to mix threaded sync with async code. It's hard to do right.

**Comment by OrangeTux** [comment]
From what I understand is that the snippet you posted is executed from the main thread, correct?

I'm wondering if you're using the `ChargePoint` objects from both the main and the 'event loop' thread. As `ChargePoint`s are not thread safe. Internally `ChargePoint` uses an [`asyncio.Queue()` which is not thread safe](https://docs.python.org/3/library/asyncio-queue.html#asyncio.Queue).

**Comment by OrangeTux** [comment]
You mentioned that  FastAPI requires you to multiple threads. But [FastAPI supports async and websockest](https://fastapi.tiangolo.com/advanced/websockets/). Are you sure you really need your app to be multithreaded?

**Comment by ToasterUwU** [comment]
> I'll dig into this later. But I won't recommend to mix threaded sync with async code. It's hard to do right.

I agree.. its really hard.. 

Im still learning, 2 years into programming, just had my midterm exam.

So if you maybe have a good idea of how I can connect FastAPI with an OCPP Server, that would be greatly appreciated. I didn't work much with async until now, so i don't really know how it works and what my options are.

**Comment by proelke** [comment]
From what I have seen in the past, FastAPI's web sockets implementation doesn't work like the websockets library. Making use of the OCPP library isn't as straightforward.

**Comment by OrangeTux** [comment]
This library requires a websocket connection to implement an async  `recv()` and `send()`. It's easy to wrap `fastapi.Websocket` into an adapter that implements this interface. Here is an example:

``` python
import asyncio
import logging
from datetime import datetime
from fastapi import FastAPI, WebSocket

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus
from ocpp.v16 import call_result

app = FastAPI()

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notification(
        self, charge_point_vendor: str, charge_point_model: str, **kwargs
    ):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted,
        )


class WebsocketAdapter:
    def __init__(self, websocket: WebSocket):
        self._ws = websocket

    async def recv(self):
        return await self._ws.receive_text()

    async def send(self, msg):
        await self._ws.send_text(msg)


@app.get("/")
async def get():
    return "Hello"


@app.websocket("/ocpp")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    id = websocket.url.path

    cp = ChargePoint(id, WebsocketAdapter(websocket))

    await cp.start()
```

**Comment by ToasterUwU** [comment]
Thanks a lot, now when I see it, it makes a lot of sense..

I will change it to something like that on Monday..

Thanks again and have a great day!

**Comment by OrangeTux** [comment]
I created #181 to make writing adapters more clear.

**Comment by ToasterUwU** [comment]
OK, thats enough for me then, you can close the issue if you want.
