### ISSUE TITLE
How to send meter values in regular interval after start transaction 

### ISSUE THREAD

**Issue by Aashutosh3804** [mobilityhouse/ocpp#184]
I want to send meter values to charge point server  after start transaction is called at regular interval how to achieve the same?

**Comment by analge-hk** [comment]
You need to use Scheduler to call functions periodically

**Comment by Aashutosh3804** [comment]
> You need to use Scheduler to call functions periodically

but how handle these Scheduler after ,if client becomes offline

**Comment by analge-hk** [comment]
You need to create a flag when the client is connected and clear it when disconnected . Check the flag before sending periodic messages. Periodic function does nothing if client is offline.
