### ISSUE TITLE
Transaction_ID

### ISSUE THREAD

**Issue by winimaister** [mobilityhouse/ocpp#185]
Hi, for make a RemoteStopTransaction, Need I first obtain a transaction ID from the RemoteStart? How can obtain the transaction ID?

**Comment by analge-hk** [comment]
When you initiate Remote start , if charger accepted it will initiate Start Transaction request. You need to provide the transaction id in this response. You need to use the same id for RemoteStopTransaction.

**Comment by winimaister** [comment]
> When you initiate Remote start , if charger accepted it will initiate Start Transaction request. You need to provide the transaction id in this response. You need to use the same id for RemoteStopTransaction.

Can you put an example of the StartTransaction and the TransactionID?
Thanks and best regards

**Comment by analge-hk** [comment]
@on(Action.StartTransaction)
    def on_StartTransaction(self,**kwargs):
          return call_result.StartTransactionPayload(
          transaction_id = You can specify some unique number for each charger
          id_tag_info = {
            "status" : "Accepted"}
        )

**Comment by analge-hk** [comment]
example for transaction id i am using 10085016. It could be anything unique for that session or for that charger

**Comment by winimaister** [comment]
Thanks for the example.

**Comment by winimaister** [comment]
I, im trying to send the RemoteStopTransaction but all times y recive Rejected status.
INFO:root:Protocols Matched: ocpp1.6
INFO:ocpp:ocpp1.6: send [2,"9ef16283-003c-4101-b582-c052f01a383b","RemoteStartTransaction",{"idTag":"1"}]
INFO:ocpp:ocpp1.6: receive message [3, "9ef16283-003c-4101-b582-c052f01a383b", {"status": "Accepted"}]
INFO:ocpp:ocpp1.6: send [2,"5a172917-d7c5-4243-abb4-aa218e56a784","RemoteStopTransaction",{"transactionId":10085016}]
Stopping Rejected
INFO:ocpp:ocpp1.6: receive message [3, "5a172917-d7c5-4243-abb4-aa218e56a784", {"status": "Rejected"}]

I use the example and have this implementation:
```
@on(Action.StartTransaction)
    def on_start_transaction(self, **kwargs):
        return call_result.StartTransactionPayload(
            transaction_id=10085016,
            id_tag_info={
                "status": 'Accepted'
            }

        )

    async def remote_start_transaction(self):
        request = call.RemoteStartTransactionPayload(
            id_tag='1'
        )
        response = await self.call(request)
        if response.status == RemoteStartStopStatus.accepted:
            print("Transaction Started!!!")

    async def remote_stop_transaction(self):
        request = call.RemoteStopTransactionPayload(
            transaction_id=10085016
        )
        response = await self.call(request)

        if response.status == RemoteStartStopStatus.accepted:
            print("Stopping transaction")
        elif response.status == RemoteStartStopStatus.rejected:
            print("Stopping Rejected")
            print(response)
```

**Comment by analge-hk** [comment]
Are you testing with real charger or simulation? Did you receive Start Transaction request  from charger? I don't see from your log. Remote stop is rejected might be because the charging session is not started.

**Comment by winimaister** [comment]
I probe in a simulator with this error, but in real charpoint work correctly now the remotestop. Thanks for help me analge-hk.
Now I go to implement other messages, if I have a problem I open a new issue. 
Thank you very much and greetings
