### ISSUE TITLE
Timestamp in start_transaction

### ISSUE THREAD

**Issue by atminstone** [mobilityhouse/ocpp#186]
It seems as the timestamp from the json message StartTransaction isn't transmitted. In this example the message timestamp and the one inserted into mysql (with mycon.message_insert) have a one second difference. The one second difference isn't much, but when losing connection the EVSE (ABB AC TERRA) sends a new StartTransaction message without a StopTransaction for the last one. The new StartTransaction message has the original timestamp, but since the timestamp isn't transferred, I can't easily check if it's just a lost connection or a real new StartTransaction message...

message from EVSE:
`receive message [2, "0809558", "StartTransaction", {"connectorId": 1, "idTag": "20:69:C0:21", "meterStart": 0, "timestamp": "2021-03-24T07:06:40.000Z"}]
`
with the on_start_transaction code:

```
    @on(Action.StartTransaction)
    def on_start_transaction(self, connector_id, id_tag, meter_start, timestamp, **kwargs):
        # possible **kwargs: reservation_id
        status = 'Accepted'
        message_content = {"timestamp":timestamp, "charge_point_id":self.id, "connector_id":connector_id, "id_tag":id_tag, "meter_start":meter_start, "status":status, **kwargs}
        response = mycon.message_insert("start_transaction", **message_content)

        return call_result.StartTransactionPayload(
            id_tag_info={
                "status": status
            },
            transaction_id=response
        )
```

timestamp in mysql:
2021-03-24 07:06:41    

any help in how to check if the new StartTransaction is a new transaction or just a connection error would be appreciated

**Comment by OrangeTux** [comment]
I'm not sure if I understand you. What do you mean with:

> but since the timestamp isn't transferred, 

`timestamp` is a required field of a `StartTransaction`. The charger must use this field.

About the charger you write:

> . The one second difference isn't much, but when losing connection the EVSE (ABB AC TERRA) sends a new StartTransaction message without a StopTransaction for the last one. 

That seems like a bug in the charger. As the OCPP specification states in section **3.6. Transaction Related message**

> When  offline, the  Charge Point MUST queue any transaction-related messages that it  would  have sent to the Central System if the Charge Point had been online

**Comment by atminstone** [comment]
Thanks for the answer, i should be more clear. The charger is sending the right timestamp, as seen in the received message. But when i insert the values into mysql with the attached on_start_transaction, the inserted timestamp is one second later than the one received in the message. It is as the timestamp is generated somewhere in the program. 

This isn’t a problem when everything is running well, but if the charger is offline, the timestamps differ substantially.

**Comment by atminstone** [comment]
With the ”transferred” i mean that the timestamp is somehow altered (or regenerated) before I insert into mysql. All other variables (connector_id, id_tag, meter_start) are working as expected. I tried looking through where it might get regenerated, but couldn’t find any clues. The mycon.message_insert is just a simple mysql connector.

I agree about the bug in the charger. I’ve contacted ABB about the issue, but haven’t had any response yet.

**Comment by OrangeTux** [comment]
Ok. I think it's a bit clearer now for me.  If I understand correctly the charger sends a timestamp, let's assume it has value `T`.
But the timestamp field in your database contains the value of `T+1`, correct?

Can you verify the value of `timestamp` before you save it to the database? Can you verify whether it has value of `T` or `T+1`?

**Comment by atminstone** [comment]
Yep that's correct. It's more apparent if the charger has a connection error, and sends the cached start_transaction message. Then the OCPP message timestamp will be `T` and the database timestamp will be 'current timestamp' (time when inserted into database).

I can print out the timestamp with
```
def on_start_transaction(self, connector_id, id_tag, meter_start, timestamp, **kwargs):
        print timestamp
```
and report back on monday when I have access to the charger again.

I have checked that my mysql connector doesn't alter the values in any way, and the database doesn't have any default values for timestamp.
