### ISSUE TITLE
Custom Data Extension support

### ISSUE THREAD

**Issue by ferfersan6** [mobilityhouse/ocpp#189]
Hi all!

Recently, I have tested my Charging Station with a vendor's testing CSMS. The thing is that the CSMS sends a CustomData field in the StatusNotificationResponse. When I received this message, an error raises:

`
  File "/home/***/***/env/lib/python3.8/site-packages/ocpp/charge_point.py", line 283, in call
    return cls(**snake_case_payload)
TypeError: __init__() got an unexpected keyword argument 'custom_data'
`

As 'StatusNotification' in call_result class does not have the field 'custom_data', it raises the error. I would like to know if there is a way to support that or at least, to avoid the error (just ignoring the field or whatever), so the program keeps running. 

Thank you in advance!

**Comment by laysauchoa** [comment]
Thanks for the question! Which ocpp version are you using?

From the ocpp specifications, no fields are defined in the `call_result` for `StatusNotification.conf`. So I do not think we should add this specifically field or allow extra fields which are not in the specification. Check section 6.48 of [OCPP 1.6](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf)

However, you can modify your code to support this behavior:

1. Specify the field here, `custom_data`
https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v16/call_result.py#L79

2. Add validation for this field or make `"additionalProperties": true` to make validation loose.
https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v16/schemas/StatusNotificationResponse.json#L6

Can you try and see how it goes?

**Comment by tropxy** [comment]
Hi,

Unfortunately that is not something we can support, since it violates the current standards. A StatusNotification Response shall not contain any fields. I would suggest you put some pressure into the vendor to change that as they are not in accordance with any standard. 

If for some weird reason they dont want to do that, the only alternative I can foresee for the short term, is if you clone our project and you modify the code yourself or schema files like @laysauchoa just suggested.

But again, I wouldnt recommend that course of actions, since you will have to do that for every new update we may release. Maybe this is something I, @OrangeTux, @laysauchoa  and whoever is interested can discuss, but the answer for now, is no, we dont support this.

**Comment by OrangeTux** [comment]
I'd like to keep the implementation of this library as close to the specification as possible. Therefore I'm not in favor of adding support for this.

**Comment by matteomaser** [comment]
`OCPP 2.0.1 - Part 2 - Specification - functional block P. DataTransfer` states:

> A CustomData element exists as an optional element in the JSON schemas of all types. CustomData is the only class in the
> JSON schema files that allows additional properties. It can thus be used to add additional custom attributes to any type.
> The CustomData has been deliberately left out of the specification document, because it would introduce a lot of clutter and
> it is not meant to be used in standard implementations. See also [OCPP2.0-PART4].

I think adding support for this feature is legitimate according to the specification.

I hope you change idea, but I respect your decision not to support this. After all the spec says:

> Please use with extreme caution and only for optional functionality, since it will impact your compatibility
> with other systems that do not make use of this option. We recommend mentioning the usage explicitly in
> your documentation and/or communication. Please consider consulting the Open Charge Alliance before
> turning to this option to add functionality.

**Comment by atDTSystemsLtd** [comment]
OCPP (and the whole e-mobility field) is still fairly new. People will have legit use cases which are not covered by current iteration of the standard. Having well define way to "extend" the standard is "lesser of two evils". People are going to mess with the standard implementation... it is better to have them "mess" in one place and in well defined way.

**Comment by matteomaser** [comment]
Sending requests with custom_data is actually pretty simple. You can copy&paste the payload to your code and add the `custom_data` attribute.

```python
from dataclasses import dataclass
from typing import Dict

@dataclass                    
class TransactionEventPayload:
    event_type: str
    timestamp: str
    trigger_reason: str
    seq_no: int
    transaction_info: Dict
    custom_data: Dict
```

Than you can replace calls to `await self.call(call.TransactionEventPayload(...` with `await self.call(TransactionEventPayload(`

There's obviously no guarantee this hack will work in future versions of the library.

Handling custom_data in received messages is more difficult and might require editing the library as already suggested.

**Comment by OrangeTux** [comment]
@matteomaser I wasn't aware of this part of the OCPP 2.0.1 specification. Thanks for letting me know. 

But I'm no sure how to interpret the section.

> A CustomData element exists as an optional element in the JSON schemas of all types.

seems to to contradict with

> The CustomData has been deliberately left out of the specification document, because it would introduce a lot of clutter and
it is not meant to be used in standard implementations.

In the meantime you could disable validation on routes that receive custom data. See https://github.com/mobilityhouse/ocpp/blob/41d4a16c368cab124264a052844332d29248372e/ocpp/routing.py#L6-L56

**Comment by maurerle** [comment]
Just a mention for other people coming here and want to send custom_data with this ocpp library:

```python
from dataclasses import dataclass
# this overrides the call.TransactionEventPayload
# it must have the same name, so that the ocpp module can validate
# with the correct action validation schema
# this way custom_data can be sent through the ocpp library
@dataclass
class TransactionEventPayload(call.TransactionEventPayload):
    custom_data: dict = None
```

Then creating:
```
request = TransactionEventPayload(
                event_type, timestamp, trigger_reason,
                seq_no, transaction_info, meter_value,
                evse=evse, id_token=id_token, custom_data=custom_data)
            response = await self.call(request)
```
Note the usage of the derived TransactionEventPayload class
