### ISSUE TITLE
help changing meter values 

### ISSUE THREAD

**Issue by SmartTransp** [mobilityhouse/ocpp#191]
I want to change the default meter values been send from the charger
so it will send me also the temperture and not just the default
this is what I'm sending 
`request = call.ChangeConfigurationPayload(key="MeterValuesSampledData", value="Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Voltage,Temperture")`
I can see he is sending this : 
`Charger123456: send [2,"7a245693-ff95-4549-8073-615256cfc364","ChangeConfiguration",{"key":"MeterValuesSampledData","value":"Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Voltage,Temperture"}]`

but I get "reject" error 
`Charger123456: receive message [3,"7a245693-ff95-4549-8073-615256cfc364",{"status":"Rejected"}]`

what is the correct why to do this ?
what did I miss? 
Thanks ,

**Comment by tropxy** [comment]
Was really that value that you have used? Because if so, you have misspelled "Temperature"

```python
#"Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Voltage,Temperture")
```

**Comment by laysauchoa** [comment]
@SmartTransp hey, has your question been answered?
