### ISSUE TITLE
Does it support OCPP over MQTT?

### ISSUE THREAD

**Issue by jim-king-2000** [mobilityhouse/ocpp#192]
Now it only supports WebSocket. Can it support MQTT? Is there any plan to support MQTT?

**Comment by tropxy** [comment]
Hi, thanks for your question.

If you dig a bit deeper into our code you will notice that we dont hook our implementation to a specific transport medium.
As you can see in the example, in the Readme, we pass the websocket instance to the ChargePoint object:
```python
cp = ChargePoint(charge_point_id, websocket)
```

inside ChargePoint we assume that the object we passed, in this case the "websocket" (which inside ChargePoint is named self._connection) contains two methods:
* rcv (https://github.com/mobilityhouse/ocpp/blob/31f7893856b27f6e5b90ae5f5f3f1aba6296614d/ocpp/charge_point.py#L123)
* send (https://github.com/mobilityhouse/ocpp/blob/31f7893856b27f6e5b90ae5f5f3f1aba6296614d/ocpp/charge_point.py#L310)

for the send you can just override the method _send (https://github.com/mobilityhouse/ocpp/blob/31f7893856b27f6e5b90ae5f5f3f1aba6296614d/ocpp/charge_point.py#L308) 
and there call the sending function that MQTT uses

For the reception you can just create another method that uses your MQTT base to receive and you dont need to use the start method we defined in ChargePoint

**Comment by jim-king-2000** [comment]
Fantastic! We are going to try it ASAP. Thank you.
