### ISSUE TITLE
ocpp 2.0.1 chargingState "Idle" in transactionevent not recognized 

### ISSUE THREAD

**Issue by Simon-gt** [mobilityhouse/ocpp#194]
The chargingState "Idle" in a transactionevent is not recognized

**Comment by OrangeTux** [comment]
I'm not entirely sure what you mean. [`ChargingStateType.Idle`](https://github.com/mobilityhouse/ocpp/blob/6cef24b84c3a82ca4b1e09e5904dacb448c5a8f7/ocpp/v201/enums.py#L286) has been defined. It's also defined [in the schemas](https://github.com/mobilityhouse/ocpp/blob/6cef24b84c3a82ca4b1e09e5904dacb448c5a8f7/ocpp/v201/schemas/TransactionEventRequest.json#L29). Can you elaborate on the issue? Maybe you give a code sample that shows the problem

**Comment by Simon-gt** [comment]
Apologies, it was due to an error on my side.
