### ISSUE TITLE
OCPP 2.0.1 TransactionEventRequest

### ISSUE THREAD

**Issue by laysauchoa** [mobilityhouse/ocpp#195]
About the [TransactionEventPayload](https://github.com/mobilityhouse/ocpp/blob/27d4e7480a293d19198e154d9484f03848285e4e/ocpp/v201/call.py#L392) which attribute refers to the `charging_state` [with possible values](https://github.com/mobilityhouse/ocpp/blob/74aef836d154f53f08c87b7b66f6fd95982a7d7c/ocpp/v201/schemas/TransactionEventRequest.json#L19)?

Maybe related to this https://github.com/mobilityhouse/ocpp/issues/194

**Comment by OrangeTux** [comment]
I'm not sure if I understand what the issue is. Can you elaborate?

**Comment by maurerle** [comment]
I think the question is how the ChargingState is set in a TransactionEventRequest?
The answer would be that the TransactionEventPayload contains an attribute "transactionInfo" of type TransactionType which contains the chargingState of type ChargingState.

But the JSON Schema is not an example json file.
I hope this helps @laysauchoa

**Comment by laysauchoa** [comment]
@maurerle you are right! I was reading from the specification the dataclasses and the JSON Schema, and got me thinking which field would refer to what. Now, I have it more clear, thanks!
Reference:
https://github.com/mobilityhouse/ocpp/blob/27d4e7480a293d19198e154d9484f03848285e4e/ocpp/v201/call.py#L397
