### ISSUE TITLE
OCPP 1.6-J Security enhancements missing from 1.6

### ISSUE THREAD

**Issue by villekr** [mobilityhouse/ocpp#197]
Improved security for OCPP 1.6-J v1.0 (ocpp_1_6_security.pdf) defines extra requests, responses and datatypes backported from 2.0 to 1.6. These are at the moment missing

The following requests are added:
CertificateSigned
DeleteCertificate
ExtendedTriggerMessage
GetInstalledCertificateIds
GetLog
InstallCertificate
LogStatusNotification
SecurityEventNotification
SignCertificate
SignedFirmwareStatusNotification
SignedUpdateFirmware

This should be quite straightforward task to backport to 1.6 from 2.0.

**Comment by OrangeTux** [comment]
Thanks. That is definitively something that should be added.

**Comment by villekr** [comment]
I can work on that if that's ok?

**Comment by OrangeTux** [comment]
Sure!

**Comment by villekr** [comment]
Actually missed already existing issue https://github.com/mobilityhouse/ocpp/issues/141. This can be closed as duplicate.
