### ISSUE TITLE
release latest OCPP to pypi

### ISSUE THREAD

**Issue by maurerle** [mobilityhouse/ocpp#198]
Hello,
please release the latest version of this package to pypi, as there are corrections which are fundamentaly needed for OCPP 2.0.1 to work as https://github.com/mobilityhouse/ocpp/commit/27d4e7480a293d19198e154d9484f03848285e4e

Distributing the package as a github release again would be nice too.
Thanks!

**Comment by OrangeTux** [comment]
Hello. Thanks for the reminder. I've released 0.8.2 and uploaded it to pypi.

I also uploaded the `.whl` files to Github releases.
