### ISSUE TITLE
Improve our Examples section, including other features that this lib provides

### ISSUE THREAD

**Issue by tropxy** [mobilityhouse/ocpp#205]
Our examples section do not include samples of how to use the @after decorator, for instance. In fact, a new comer to this open source lib will probably never know about it, unless it starts diving into the source code.

I suggest we add examples for it and for other features we may have or at least list them in the Readme, maybe even providing perma links to the source code

**Comment by daniel-makohin-mmz** [comment]
Would you want help or collaboration? Some friends and I have been using ocpp for python and we are working in some interesting fixtures to test CS and CP.

**Comment by garima8** [comment]
I need help please, I was trying to implement a call from central_system to charge_point for reset.req and got this error.
*** AttributeError: 'ChargePoint' object has no attribute '_call_result'

This is my function of the reset request

    async def reset_req(self):
        request = call.ResetPayload(
            type= ResetType.hard
        )
        response = await self.call(request)
        if response.status == ResetStatus.accepted:
            print("Reset Accepted!!")
        else:
            print("Reset Rejected!!")

**Comment by nickbedbury** [comment]
Not specific to the `@after` tag, but I have some code I could add to the `v16/central_system.py` example if interested.  I wasn't sure of the process for getting it into this repo as a non-collaborator.

**Comment by OrangeTux** [comment]
Sure, go ahead. PRs are welcome. A lot of issues cover similar topics, so it makes sense to update the examples to make usage of this lib more clear.  The `@after()` docorator is one of those topics.

**Comment by nickbedbury** [comment]
I created this PR: 
https://github.com/mobilityhouse/ocpp/pull/286

**Comment by Jared-Newell-Mobility** [comment]
As the above PR was closed and https://github.com/mobilityhouse/ocpp/issues/55 covers improved documentation; the original purpose of this PR - I'll close this for now
