### ISSUE TITLE
v16/schemas/StopTransaction.json missing "Hertz"

### ISSUE THREAD

**Issue by villekr** [mobilityhouse/ocpp#207]
In issue https://github.com/mobilityhouse/ocpp/issues/71 "Hertz" was added as valid unit. However it should also be allowed within StopTransaction's transactionData.

**Comment by villekr** [comment]
After checking the referred document "OCPP 1.6 Errata sheet, v4.0 Release, 2019-10-23, on page 33" I think that change done in https://github.com/mobilityhouse/ocpp/issues/71 might be incorrect. The document doesn't specify that unit "Hertz" should be explicitly defined and allowed in schema. Latest official ocpp 1.6 schemas for Metervalues.json and StopTransaction.json don't have "Hertz" as enumeration for "unit".

Document: OCPP 1.6 Errata sheet, v4.0 Release, 2019-10-23, on page 33:
_OCPP 1.6 does not have a UnitOfMeasure for frequency, the UnitOfMeasure for any SampledValue with measurand: Frequency is Hertz._

The question is that should change https://github.com/mobilityhouse/ocpp/issues/71 (https://github.com/mobilityhouse/ocpp/commit/22306f06962ab61448ef0c54d09e92318675fccf) be actually reverted?

**Comment by OrangeTux** [comment]
Good catch. I think you're right and `Hertz` has not been added as a Unit. However, reverting the change would be backwards incompatible.

**Comment by villekr** [comment]
Would it still be better to fix (i.e. revert) instead of keeping incorrect enum and schema there? Now it's possible to send non-standard MeterValues messages.

**Comment by OrangeTux** [comment]
I think you're right. Given that we're currently before a 1.x.x. release, this package can have backwards incompatible changes according to SemVer. I'll revert the change soon.

**Comment by Jared-Newell-Mobility** [comment]
Satisfied with PR https://github.com/mobilityhouse/ocpp/pull/497 - will be included in next major release

**Comment by Jared-Newell-Mobility** [comment]
Referenced in https://github.com/mobilityhouse/ocpp/issues/174
