### ISSUE TITLE
Payloads field type error

### ISSUE THREAD

**Issue by pagetable** [mobilityhouse/ocpp#21]
Although Type hints are not utilized in this project yet, I found some potential errors in the field type of payloads. I have double checked all these field types with json shcemas.

call.py
- GetConfigurationPayload.key: str -> List
- RemoteStartTransactionPayload.id_tag: int -> str
- MeterValuesPayload.connector_id: str -> int
  MeterValuesPayload.meter_value: Dict -> List
  MeterValuesPayload.transaction_id: str -> int
- StopTransactionPayload.transaction_data: Dict -> List

call_result.py
- GetConfigurationPayload.configuration_key: Dict -> List
  GetConfigurationPayload.unknown_key: str -> List

If these are wrong, please just ignore my issue. Thanks.

**Comment by OrangeTux** [comment]
Thank for reporting this issue! The problems will be fixed
