### ISSUE TITLE
Why the browser is not working??

### ISSUE THREAD

**Issue by josesilva1995** [mobilityhouse/ocpp#212]
![CentralSystem](https://user-images.githubusercontent.com/84137846/120462374-c6a0ca80-c392-11eb-99be-9d827b2edc21.PNG)
![CentralPoint](https://user-images.githubusercontent.com/84137846/120462382-c99bbb00-c392-11eb-86be-9118d54c4262.PNG)
![browser](https://user-images.githubusercontent.com/84137846/120462461-e0421200-c392-11eb-8f94-2309d359a59d.PNG)
Hello...
I used your code to try a communication between my laptop (Central System-Server) and a Raspberry (CentralPoint - Client). How can you see in first and second image, the bootnotification is a success. However, when I open the browser in my laptop, appears the message in third image. 
Once is used websockets, wouldn´t be supposed to appear something in browser??

Best regards,

**Comment by tropxy** [comment]
Hi,

Did you just entered the WS url in your browser and gave it a shot? Because as the message says, you need a proper WS client for that

**Comment by josesilva1995** [comment]
> Hi,
> 
> Did you just entered the WS url in your browser and gave it a shot? Because as the message says, you need a proper WS client for that

I entered this url: localhost:8000/CP_1 . It is the some url in your code to the CentralPoint. I just changed the socket from 9000 to 8000.

**Comment by tropxy** [comment]
The thing is that you wont be able to access your CSMS server just like that. you need a proper WS client. I would recommend you to check this: https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API?retiredLocale=pt-PT
