### ISSUE TITLE
ocpp client implementation usign threads instead of asyncio

### ISSUE THREAD

**Issue by marlonllano7** [mobilityhouse/ocpp#220]
Hi guys, As the title says I implemented an ocpp client taking as support all the comments and resolved issues on this channel and it performs fine, thank you very much. Now I must adapt it to a bigger module(with sensors and AWS connections etc.) that is already done and tested on a Raspberry Pi. The problem is that I find very difficult merging asyncio with threads so I decided to migrate my code to threads and I'm stucked on the classic "sendBootNotification" and wait the response from the server. I'm sorry if this is a very dummy question but could you please help me out? I will be uploading my code as far as I get some good results. Thank you in advance

**Comment by OrangeTux** [comment]
I've bad experiences with threaded and async code in Python: it's hard. However, the async part for project is relatively small. I suggest  tomake your own implementation of [`ocpp.v16.charge_point.ChargePoint`](https://github.com/mobilityhouse/ocpp/blob/41d4a16c368cab124264a052844332d29248372e/ocpp/charge_point.py#L79-L316)  (or the 2.0 or 2.0.1 variant) that reuses all the enums and dataclasses provided by this package.
