### ISSUE TITLE
Meter value call function in OCPP 2.0.1

### ISSUE THREAD

**Issue by Ruban-A** [mobilityhouse/ocpp#221]
Meter value call function in OCPP 2.0.1
I am trying to create a call function .
        request = call.MeterValuesPayload(
            evse_id=0,
            # meter_value=[
                {
                    'timestamp': 'time',
                    'sampledValue': ['value.array(''[1.2,1.3,2.3])']
                }
            ]
        )

 'sampledValue': ['value.array(''[1.2,1.3,2.3])'] on this line there is error thrown as its not type of array
can you send me snippet of **meter value** function and i am working on Python platform

**Comment by marlonllano7** [comment]
Hi Ruban, the following routine is tested and works fine. I only send the 3 phases values but you can adapt it to your specific problem. I hope it helps you    

async def send_meter_values(self):

        while self.cp_trans_status:
            v1,v2,v3 = randint(230,240),randint(230,240),randint(230,240)
            request = call.MeterValuesPayload(
                connector_id=0,
                meter_value=[{
                    "timestamp": datetime.utcnow().isoformat(),
                    "sampledValue":[
                        {"value":str(v1),
                        "phase": 'L1-N',
                        "measurand":'Voltage',
                        "unit": 'V'},
                        {"value":str(v2),
                        "phase": 'L2-N',
                        "measurand":'Voltage',
                        "unit":'V'},
                        {"value":str(v3),
                        "phase": 'L3-N',
                        "measurand":'Voltage',
                        "unit":'V'},
                        ]
                    },],
                transaction_id=123
                )
            await self.call(request)
            await asyncio.sleep(15)

**Comment by Ruban-A** [comment]
Thanks
