### ISSUE TITLE
in call_result.func in ocpp 2.0.1

### ISSUE THREAD

**Issue by Ruban-A** [mobilityhouse/ocpp#222]
in call_result.func in ocpp 2.0.1
in syntax its given pass for Transaction and meter value 
i am getting error
ERROR:ocpp:Error while handling request '<Call - unique_id=9517d108-1fa2-40ff-ac89-15b7719a3fd5, action=TransactionEvent, payload={'eventType': 'Started', 'timestamp': 'string', 'triggerReason': 'EnergyLimitReached', 'seqNo': 1234, 'transactionInfo': {'transactionId': 'TransactionID'}}>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 185, in _handle_call
    response = handler(**snake_case_payload)
  File "/usr/local/lib/python3.9/dist-packages/ocpp/routing.py", line 47, in inner
    return func(*args, **kwargs)
TypeError: on_transaction_event() got an unexpected keyword argument 'transaction_info'

other is 
return call_result.MeterValuesPayload()

ERROR:ocpp:Error while handling request '<Call - unique_id=4a5d1235-749d-4475-b83e-ef19ee984a4e, action=MeterValues, payload={'evseId': 0, 'meterValue': [{'timestamp': 'time', 'sampledValue': [{'value': 1}]}]}>'
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 185, in _handle_call
    response = handler(**snake_case_payload)
  File "/usr/local/lib/python3.9/dist-packages/ocpp/routing.py", line 47, in inner
    return func(*args, **kwargs)
TypeError: on_meter_value() got an unexpected keyword argument 'meter_value'

**Comment by tropxy** [comment]
> in call_result.func in ocpp 2.0.1
> in syntax its given pass for Transaction and meter value
> i am getting error
> ERROR:ocpp:Error while handling request '<Call - unique_id=9517d108-1fa2-40ff-ac89-15b7719a3fd5, action=TransactionEvent, payload={'eventType': 'Started', 'timestamp': 'string', 'triggerReason': 'EnergyLimitReached', 'seqNo': 1234, 'transactionInfo': {'transactionId': 'TransactionID'}}>'
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 185, in _handle_call
> response = handler(**snake_case_payload)
> File "/usr/local/lib/python3.9/dist-packages/ocpp/routing.py", line 47, in inner
> return func(*args, **kwargs)
> TypeError: on_transaction_event() got an unexpected keyword argument 'transaction_info'
> 
> other is
> return call_result.MeterValuesPayload()
> 
> ERROR:ocpp:Error while handling request '<Call - unique_id=4a5d1235-749d-4475-b83e-ef19ee984a4e, action=MeterValues, payload={'evseId': 0, 'meterValue': [{'timestamp': 'time', 'sampledValue': [{'value': 1}]}]}>'
> Traceback (most recent call last):
> File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 185, in _handle_call
> response = handler(**snake_case_payload)
> File "/usr/local/lib/python3.9/dist-packages/ocpp/routing.py", line 47, in inner
> return func(*args, **kwargs)
> TypeError: on_meter_value() got an unexpected keyword argument 'meter_value'

Hi, thanks for using our lib. Can you provide us the source code you have used that generated that traceback?

Cheers,
André

**Comment by Ruban-A** [comment]
The problem got resolved, Thanks
