### ISSUE TITLE
DataTransferPayload status validation

### ISSUE THREAD

**Issue by drc38** [mobilityhouse/ocpp#223]
Should this `status` in `call_result.py` be updated to `status: DataTransferStatus` rather than a generic string?

@dataclassclass 
DataTransferPayload:    
status: str    
data: Optional[str] = None

**Comment by laysauchoa** [comment]
@drc38 I agree with you. https://github.com/mobilityhouse/ocpp/pull/224 closes #223

**Comment by OrangeTux** [comment]
Thanks for reporting!
