### ISSUE TITLE
storing the Data from OCPP

### ISSUE THREAD

**Issue by Ruban-A** [mobilityhouse/ocpp#225]
storing the Data from OCPPv2.0.1 in sql server.
I am able to store in local host PC . Do you have any inbuilt library in OCPPv2.0.1 in python language to directly link to sql server with user and password.
If not any other means to store the received data to CSMS from CS .for furthered payment purpose.
Thanks in Advance
Ruban

**Comment by OrangeTux** [comment]
> Do you have any inbuilt library in OCPPv2.0.1 in python language to directly link to sql server with user and password.

Nope. You should implement that yourself. The Python ecosystem contains several good projects to communicate with SQL databases. I personally have used SQLAlchemy for quite a while. But I haven't worked with SQL databases and Python in the last few years. So I'm not sure if there are other projects around.
