### ISSUE TITLE
Configure throught GSM for OCPPv2.0.1

### ISSUE THREAD

**Issue by Ruban-A** [mobilityhouse/ocpp#226]
Configure throught GSM for OCPPv2.0.1.
If there is any link or related document can any of you kindly provide . I am trying to working OCPPv2.0.1 through GSM

**Comment by OrangeTux** [comment]
I don't see the relevance of this question for this project. This project implements a protocol on top of websockets. Websockets is part of the OSI application layer. Whatever technique you use to communicate (Ethernet, WiFi, Zigbee, GSM or something else) is not relevant.
