### ISSUE TITLE
Error with setdisplaymessage function and getdisplaymessage function

### ISSUE THREAD

**Issue by Ruban-A** [mobilityhouse/ocpp#228]
Request function in CSMS
    async def request_set_display_messages(self):
        request = call.SetDisplayMessagePayload(
            message={
                "id": 380,
                "priority": "InFront",
                "message": {
                    "format": "HTML",
                    "content": "string",
                    "language": "C"
                }
            }
        )
        response = await self.call(request)

Response Function in CS

    @on('SetDisplayMessages')
    async def response_set_display_messages(self, message):
        return call_result.SetDisplayMessagePayload(
            status="Accepted"
        )

Error

INFO:ocpp:CP_1: receive message [2,"3bf4cfff-b791-48ff-be94-f6c6c4fff8f7","SetDisplayMessage",{"message":{"id":380,"priority":"InFront","message":{"format":"HTML","content":"string","language":"C"}}}]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 162, in _handle_call
    handlers = self.route_map[msg.action]
KeyError: 'SetDisplayMessage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ruban/Desktop/OCPP-implementation-tracker/cs_clean.py", line 5226, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ruban/Desktop/OCPP-implementation-tracker/cs_clean.py", line 5213, in main
    await asyncio.gather(cp.start(), cp.request_sign_certificate(), cp.request_security_event_notification(),
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 126, in start
    await self.route_message(message)
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 144, in route_message
    await self._handle_call(msg)
  File "/usr/local/lib/python3.9/dist-packages/ocpp/charge_point.py", line 164, in _handle_call
    raise NotImplementedError(f"No handler for '{msg.action}' "
ocpp.exceptions.NotImplementedError: NotImplementedError: No handler for 'SetDisplayMessage' registered., {}

Process finished with exit code 1

**Comment by tropxy** [comment]
Hi @Ruban-A , it seems the problem you are experiencing is due to a misspell of the Action to route. You should use the word "SetDisplayMessage" and not "SetDisplayMessages". You can use the official and tested enums we have in our repo, to avoid this problems: https://github.com/mobilityhouse/ocpp/blob/a6f57307d2a8a1c8f85f802742b5855ccf48756d/ocpp/v201/enums.py#L57


So, in your case, would be:
```pyhton
from ocpp.v201.enums import Action
@on(Action.SetDisplayMessage)
async def response_set_display_messages(self, message):
    return call_result.SetDisplayMessagePayload(
        status="Accepted"
    )

```

**Comment by Ruban-A** [comment]
Thanks i figured it out . I added s  @on('SetDisplayMessages') , i cleared the error by removing s @on('SetDisplayMessage'). Now its working Fine

**Comment by tropxy** [comment]
> Thanks i figured it out . I added s @on('SetDisplayMessages') , i cleared the error by removing s @on('SetDisplayMessage'). Now its working Fine

Great! But as I said, is easier and faster if you use the enums. I realise that we dont have an example with it in our docs and we should. I will take care of opening a PR to solve that.
