### ISSUE TITLE
Question: How to send a message from CentralSytem to chargepoint

### ISSUE THREAD

**Issue by doumelas** [mobilityhouse/ocpp#23]
Hello @OrangeTux ,
I can't find a way to send a request  from CentralSytem to ChargePoint.
Could you please tell me what i can do or it will be great if you can provide  an example

**Comment by OrangeTux** [comment]
Hello @doumelas, sure I can tell you that! In this #7 I explained how to send a message from a the central system to a charge point. If you don't mind I close this ticket.

If you have any further question, feel free to reopen #7 and ask the question.

**Comment by doumelas** [comment]
Thanks didn't ssaw it

**Comment by OrangeTux** [comment]
@doumelas No problem. I think the fact that this question pops up multiple times shows that the examples can be improved.
