### ISSUE TITLE
OCPP 1.5 compatibility

### ISSUE THREAD

**Issue by sivabudh** [mobilityhouse/ocpp#237]
I would like to explore adding OCPP 1.5 compatibility to the library. Is it technically feasible and compatible with the library's intended design and architecture?

**Comment by OrangeTux** [comment]
I haven't worked with OCPP 1.5. But from what I understand [0] is OCPP 1.5 subset of OCPP 1.6, so it should work.

[0]: https://www.openchargealliance.org/protocols/ocpp-16/

**Comment by sivabudh** [comment]
> I haven't worked with OCPP 1.5. But from what I understand [0](https://www.openchargealliance.org/protocols/ocpp-16/) is OCPP 1.5 subset of OCPP 1.6, so it should work.

Thanks. We will give it a try!
