### ISSUE TITLE
evseId related query

### ISSUE THREAD

**Issue by zainuvk** [mobilityhouse/ocpp#239]
Thanks a lot for the package and sharing the starting up docs. I had a query of evseId which is used in RequestStartTransactionPayload.  Should every CSMS maintain a list of evseId for corresponding charger connected to it. The reason I am asking this is because evseId datatype is integer whereas Chargers connected are identified  by string. Does all CSMS maintain an internal mapping of chargers connected and their corresponding evseId.

**Comment by OrangeTux** [comment]
I'm not sure if I understand you correctly. But it seems that you mix up EVSE ID and charger ID. Those are 2 different kind of identifiers. 

A charger is identified by a charger id, which is a string. 
Every charger has 1 or more Electric Vehicle Supply Equipment (EVSE). In my experience , usually  chargers have 1 EVSE per connector. For more info see https://github.com/mobilityhouse/ocpp/blob/master/docs/v201/OCPP-2.0.1_part1_architecture_topology.pdf

**Comment by zainuvk** [comment]
Thanks for the explanation and  this reference helped.

![image](https://user-images.githubusercontent.com/13005040/132280219-63474430-61e1-49f4-a120-61b59265e85d.png)

A followup query on EVSEID and ConnectorId is how would  client send connector details to CSMS . Does it is sent via BootNotificationPayload.

An EVSE has two connectors and BootNotificationPayload accepts  ChargingStationType Dictionary and Reason. Incase we want to save that EVSE has 2 connectors with id 1 and 2 , could you please guide the correct way of sending these details to CSMS. 

One way I can think of is having another UI interface where an Operator would set these all master data (info regarding Charging Station, EVSE and Connectors) and every-time an EVSE is powered it would compare the data with CSMS and then move ahead.

**Comment by OrangeTux** [comment]
I'm not very familiar with OCPP 2.0.x. But in OCPP 1.6 the charge point sends StatusNotifications for every connector to the CSMS.

**Comment by zainuvk** [comment]
Thanks @OrangeTux .OCPP 2.0.1 specs had a section for Availability where it is documented that Charging Station sends a StatusNotificationRequest to the CSMS to inform the CSMS about the new status of its connectors. The data transfer object StatusNotificationRequest has timestamp,connectorStatus, evseId,connectorId . This was the info I was looking for.
