### ISSUE TITLE
Pulling electrical parameters from CP to server

### ISSUE THREAD

**Issue by StephenC808** [mobilityhouse/ocpp#241]
Is it possible to send MeterValues request from the central system to the cp?

I have the boot notifications working so how would this be implemented by modifying the boot notification example?

**Comment by tropxy** [comment]
It is possible to trigger Meter Values from the central system, which then causes the CP to send a  MeterValueRequest

**Comment by StephenC808** [comment]
I added a get_meter_values def into the cp class modeled off the bootnotification def but it doesnt seem to do anything. Any ides where I am going wrong?

`import asyncio
import logging
from datetime import datetime

try:
    import websockets
except ModuleNotFoundError:
    print("This example relies on the 'websockets' package.")
    print("Please install it by running: ")
    print()
    print(" $ pip install websockets")
    import sys
    sys.exit(1)

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus
from ocpp.v16 import call_result

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notification(self, charge_point_vendor: str, charge_point_model: str, **kwargs):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted
        )
        
    @on(Action.MeterValues)  
    def get_meter_values(self, charge_point_vendor: str, charge_point_model: str, **kwargs):
        return call_result.MeterValuesPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted
        )


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '192.168.1.80',
        80,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started listening to new connections...")
    await server.wait_closed()

if __name__ == '__main__':
    try:
        # asyncio.run() is used when running this example with Python 3.7 and
        # higher.
        asyncio.run(main())
    except AttributeError:
        # For Python 3.6 a bit more code is required to run the main() task on
        # an event loop.
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()`

**Comment by OrangeTux** [comment]
> Is it possible to send MeterValues request from the central system to the cp?

Although it's possible, it violates the OCPP standard. The specification states that MeterValues requests are send by the CP to the CSMS.

As @tropxy suggested you can uses `TriggerMessage` with type `MeterVaues` to 'poll'  `MeterValues` from the CP.  See section 6.51 of the OCPP 1.6 specification[0]


[0]: https://raw.githubusercontent.com/mobilityhouse/ocpp/master/docs/v16/ocpp-1.6.pdf

**Comment by StephenC808** [comment]
I have tried using the TriggerMessage to no avail. Am I doing something wrong or has that functionality not been included yet? See my output and code below

INFO:root:Server Started listening to new connections...
INFO:root:Protocols Matched: ocpp1.6
INFO:ocpp:TACW742421T1083: send [2,"6338f2aa-7ee3-4cbf-9751-179fece34388","TriggerMessage",{"requestedMessage":"MeterValues"}]
INFO:ocpp:TACW742421T1083: receive message [2, "6490086", "BootNotification", {"chargePointModel": "CDT_TACW7::NET_ETH", "chargePointVendor": "Chargedot", "chargeBoxSerialNumber": "TACW742421T1083", "firmwareVersion": "TAC1Z9118606710247::V1.3.4", "meterType": "V1"}]
INFO:ocpp:TACW742421T1083: send [3,"6490086",{"currentTime":"2021-09-15T13:44:01.801579","interval":10,"status":"Accepted"}]
INFO:ocpp:TACW742421T1083: receive message [3, "6338f2aa-7ee3-4cbf-9751-179fece34388", {"status": "NotImplemented"}]
---------------------------
TriggerMessagePayload(status='NotImplemented')
---------------------------
INFO:ocpp:TACW742421T1083: receive message [2, "3737587", "StatusNotification", {"connectorId": 0, "errorCode": "NoError", "info": "null", "status": "Unavailable", "vendorErrorCode": "0x00"}]

`import asyncio
import logging
from datetime import datetime

try:
    import websockets
except ModuleNotFoundError:
    print("This example relies on the 'websockets' package.")
    print("Please install it by running: ")
    print()
    print(" $ pip install websockets")
    import sys
    sys.exit(1)

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, MessageTrigger
from ocpp.v16 import call_result, call

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notification(self, charge_point_vendor: str, charge_point_model: str, **kwargs):        
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted
        )   
        
    async def get_meter_values(self):                  
        response  = await self.call(call.TriggerMessagePayload('MeterValues'))
        print("---------------------------")
        print (response)
        print("---------------------------")  
        

async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await asyncio.gather(cp.start(), cp.get_meter_values())


async def main():
    server = await websockets.serve(
        on_connect,
        '192.168.1.80',
        80,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started listening to new connections...")
    await server.wait_closed()


if __name__ == '__main__':
    try:
        # asyncio.run() is used when running this example with Python 3.7 and
        # higher.
        asyncio.run(main())
    except AttributeError:
        # For Python 3.6 a bit more code is required to run the main() task on
        # an event loop.
        loop = asyncio.get_event_loop()
        loop.run_until_complete(main())
        loop.close()`

**Comment by andcan86** [comment]
you are missing the **kwargs in the get_meter_values(), so you are not processing the information coming from the CP. 

Try this: 
`    async def on_meter_values(self, **kwargs):
        print(kwargs)
        mv = call.MeterValues(**kwargs)
        return call_result.MeterValuesPayload()  # you have to return an empty payload by ocpp std`

BTW this is not an issue nor a question concerning the expected behaviour of the code, this shall be a stackoverflow question. please close the issue
