### ISSUE TITLE
Iam getting this error but not frequently.

### ISSUE THREAD

**Issue by deepakEnercent** [mobilityhouse/ocpp#244]
![Screenshot from 2021-08-27 17-50-34](https://user-images.githubusercontent.com/86566162/131126905-d57411da-ed52-4d87-8851-d581e1e3b0eb.png)

This is the error iam getting and iam confused where to find and iam justing stating python.so help is needed here

Whenever i try to connect to the real load(Delta charger). I  get this kind of error and the program crashes and doesn't go forward after this error.

'' , from this part the error comes and i get stuck.

**Comment by laysauchoa** [comment]
Hey @deepakEnercent 

Thanks for the question. Could you please post your `server.py` file? It would make it possible to reproduce it and to help your further :)

**Comment by deepakEnercent** [comment]
> Hey @deepakEnercent
> 
> Thanks for the question. Could you please post your `server.py` file? It would make it possible to reproduce it and to help your further :)

Yeah.this is the file

`from quart import Quart, websocket
import asyncio
import logging
from datetime import datetime
from os import stat
import websockets

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result

# ==================== Variables are defined here ====================================

logging.basicConfig(level=logging.INFO)

app = Quart(__name__)

# ============================ BOOT NOTIFICATION ========================================
class ChargePoint(cp):
    @on('BootNotification')
    def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )

# ================================= HEART BEAT ===============================================
    @on('Heartbeat')
    def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )

#========================================= AUTHORIZATION ==================================
    @on('Authorize')
    def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
       
#========================= TRIGGER STATUS ====================================================

    @on('TriggerMessage')
    def triggerMsg(
        self,
        status
        ):
        print(f"Trigger Message request status =={status}")

        return call_result.TriggerMessagePayload(
            requestedMessage = "MeterValues"
            )

# =============================   START TRANSACTION ==========================================
    @on('StartTransaction')
    def startTransaction(
            self,
            connector_id,
            id_tag,
            timestamp,
            meter_start,
            **kwargs
    ):
        return call_result.StartTransactionPayload(
            transaction_id=3,
            id_tag_info={
                "status": "Accepted"
            }
        )

    
# ================================= STOP TRANSACTION ========================================
    @on('StopTransaction')
    def stopTransaction(
        self,
        meter_stop,
        timestamp,
        transaction_id,
        **kwargs
    ):
        return call_result.StopTransactionPayload(
            id_tag_info={
                "status": 'Accepted'
            }
        )


#========================= STATUS NOTIFICATION ===========================================
    @on('StatusNotification')
    def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):

        return call_result.StatusNotificationPayload()

#============================ METER VALUE ================================================

    @on('MeterValues')
    def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        return call_result.MeterValuesPayload() 

# =============================== Main handler ===========================================

async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        5000,
        subprotocols=['ocpp1.6']
    )
    logging.info("Server Started...")
    await server.wait_closed()



@app.route("/")
def home():
    return "hello"

@app.websocket("/w")
def print_websocket_data():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    


if __name__ == '__main__':
        app.run(debug=True)


`

**Comment by deepakEnercent** [comment]
``python 

from quart import Quart, websocket
import asyncio
import logging
from datetime import datetime
from os import stat
import websockets

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result

# ==================== Variables are defined here ====================================

logging.basicConfig(level=logging.INFO)

app = Quart(__name__)

# ============================ BOOT NOTIFICATION ========================================
class ChargePoint(cp):
    @on('BootNotification')
    def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )

# ================================= HEART BEAT ===============================================
    @on('Heartbeat')
    def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )

#========================================= AUTHORIZATION ==================================
    @on('Authorize')
    def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
       
#========================= TRIGGER STATUS ====================================================

    @on('TriggerMessage')
    def triggerMsg(
        self,
        status
        ):
        print(f"Trigger Message request status =={status}")

        return call_result.TriggerMessagePayload(
            requestedMessage = "MeterValues"
            )

# =============================   START TRANSACTION ==========================================
    @on('StartTransaction')
    def startTransaction(
            self,
            connector_id,
            id_tag,
            timestamp,
            meter_start,
            **kwargs
    ):
        return call_result.StartTransactionPayload(
            transaction_id=3,
            id_tag_info={
                "status": "Accepted"
            }
        )

    
# ================================= STOP TRANSACTION ========================================
    @on('StopTransaction')
    def stopTransaction(
        self,
        meter_stop,
        timestamp,
        transaction_id,
        **kwargs
    ):
        return call_result.StopTransactionPayload(
            id_tag_info={
                "status": 'Accepted'
            }
        )


#========================= STATUS NOTIFICATION ===========================================
    @on('StatusNotification')
    def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):

        return call_result.StatusNotificationPayload()

#============================ METER VALUE ================================================

    @on('MeterValues')
    def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        return call_result.MeterValuesPayload() 

# =============================== Main handler ===========================================

async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        5000,
        subprotocols=['ocpp1.6']
    )
    logging.info("Server Started...")
    await server.wait_closed()



@app.route("/")
def home():
    return "hello"

@app.websocket("/w")
def print_websocket_data():
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    


if __name__ == '__main__':
        app.run(debug=True)

**Comment by deepakEnercent** [comment]
> Hey @deepakEnercent
> 
> Thanks for the question. Could you please post your `server.py` file? It would make it possible to reproduce it and to help your further :)

server.py
`import asyncio
import logging
from datetime import datetime
from os import stat
import websockets


from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):

        print(f"{charge_point_model} from {charge_point_vendor} booted. and extras = {kwargs}")

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )


    @on('Heartbeat')
    async def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )


    @on('Authorize')
    async def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        print("This is data Auhtorize up  function")
        print (f"id_tag == {id_tag} and extra == {kwargs} ")
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
    print("This is data Authorize function")
       
    @on('StatusNotification')
    async def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):
        print(f"connector_id == {connector_id} status == {status} error_code == {error_code} and extras == {kwargs}")

        return call_result.StatusNotificationPayload()

    @on('MeterValues')
    async def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        print(f"connector_id == {connector_id} meter_value == {meter_value} and extras == {kwargs}")
        return call_result.MeterValuesPayload() 

    @on(Action.RemoteStartTransaction)
    async def starttra(self, status):

        return call_result.RemoteStartTransactionPayload(connector_id =1, id_tag = "hello")

# =============================== Main handler ===========================================

async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started...")
    await server.wait_closed()


if __name__ == '__main__':
        asyncio.run(main())


`

**Comment by deepakEnercent** [comment]
`python`
print("hello")

**Comment by deepakEnercent** [comment]
> Hey @deepakEnercent
> 
> Thanks for the question. Could you please post your `server.py` file? It would make it possible to reproduce it and to help your further :)

`import asyncio
import logging
from datetime import datetime
from os import stat
import websockets


from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result



logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):

        print(f"{charge_point_model} from {charge_point_vendor} booted. and extras = {kwargs}")

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )


    @on('Heartbeat')
    async def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )


    @on('Authorize')
    async def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        print("This is data Auhtorize up  function")
        print (f"id_tag == {id_tag} and extra == {kwargs} ")
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
    print("This is data Authorize function")
       





    @on('StatusNotification')
    async def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):
        print(f"connector_id == {connector_id} status == {status} error_code == {error_code} and extras == {kwargs}")

        return call_result.StatusNotificationPayload()



    @on('MeterValues')
    async def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        print(f"connector_id == {connector_id} meter_value == {meter_value} and extras == {kwargs}")
        return call_result.MeterValuesPayload() 

    @on(Action.RemoteStartTransaction)
    async def starttra(self, status):

        return call_result.RemoteStartTransactionPayload(connector_id =1, id_tag = "hello")


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started...")
    await server.wait_closed()


if __name__ == '__main__':
        asyncio.run(main())


`

**Comment by deepakEnercent** [comment]
code:
`import asyncio
import logging
from datetime import datetime
from os import stat
import websockets


from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result



logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):

        print(f"{charge_point_model} from {charge_point_vendor} booted. and extras = {kwargs}")

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )


    @on('Heartbeat')
    async def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )


    @on('Authorize')
    async def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        print("This is data Auhtorize up  function")
        print (f"id_tag == {id_tag} and extra == {kwargs} ")
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
    print("This is data Authorize function")
       





    @on('StatusNotification')
    async def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):
        print(f"connector_id == {connector_id} status == {status} error_code == {error_code} and extras == {kwargs}")

        return call_result.StatusNotificationPayload()



    @on('MeterValues')
    async def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        print(f"connector_id == {connector_id} meter_value == {meter_value} and extras == {kwargs}")
        return call_result.MeterValuesPayload() 

    @on(Action.RemoteStartTransaction)
    async def starttra(self, status):

        return call_result.RemoteStartTransactionPayload(connector_id =1, id_tag = "hello")


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started...")
    await server.wait_closed()


if __name__ == '__main__':
        asyncio.run(main())


`

**Comment by deepakEnercent** [comment]
`python`

import asyncio
import logging
from datetime import datetime
from os import stat
import websockets


from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result



logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):

        print(f"{charge_point_model} from {charge_point_vendor} booted. and extras = {kwargs}")

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )


    @on('Heartbeat')
    async def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )


    @on('Authorize')
    async def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        print("This is data Auhtorize up  function")
        print (f"id_tag == {id_tag} and extra == {kwargs} ")
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
    print("This is data Authorize function")
       





    @on('StatusNotification')
    async def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):
        print(f"connector_id == {connector_id} status == {status} error_code == {error_code} and extras == {kwargs}")

        return call_result.StatusNotificationPayload()



    @on('MeterValues')
    async def meterValue(
        self,
        connector_id,
        meter_value,
        **kwargs
    ):
        print(f"connector_id == {connector_id} meter_value == {meter_value} and extras == {kwargs}")
        return call_result.MeterValuesPayload() 

    @on(Action.RemoteStartTransaction)
    async def starttra(self, status):

        return call_result.RemoteStartTransactionPayload(connector_id =1, id_tag = "hello")


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)

    await cp.start()


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started...")
    await server.wait_closed()


if __name__ == '__main__':
        asyncio.run(main())

**Comment by deepakEnercent** [comment]
`server.py
`print("hello")
`

**Comment by deepakEnercent** [comment]
```python
import asyncio
import logging
from datetime import datetime
from os import stat
import websockets

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, ResetType
from ocpp.v16 import call_result

logging.basicConfig(level=logging.INFO)


class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(
            self,
            charge_point_vendor,
            charge_point_model,
            **kwargs
    ):

        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S"),
            interval=100,
            status= 'Accepted'
        )

    @on('Heartbeat')
    async def on_heartBeat(self):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S") + "Z"
        )

    @on('Authorize')
    async def on_authorize(
            self,
            id_tag,
            **kwargs
    ):
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'
            }
        )
    
    @on('StatusNotification')
    async def statusNotification(
        self, 
        connector_id, 
        status, 
        error_code, 
        **kwargs
    ):
        return call_result.StatusNotificationPayload()


async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers[
            'Sec-WebSocket-Protocol']
    except KeyError:
        logging.error(
            "Client hasn't requested any Subprotocol. Closing Connection"
        )
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning('Protocols Mismatched | Expected Subprotocols: %s,'
                        ' but client supports  %s | Closing connection',
                        websocket.available_subprotocols,
                        requested_protocols)
        return await websocket.close()

    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    await cp.start()

async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )

    logging.info("Server Started...")
    await server.wait_closed()


if __name__ == '__main__':
        asyncio.run(main())

```

**Comment by deepakEnercent** [comment]
> Please enable debug logs and post them.

Sorry for this dumb questions. but do i have to add anything in my program for the debug logs.Iam just starting this python language and bit confused with logger and asyncio part.

**Comment by deepakEnercent** [comment]
Yeah i've added the debug part and this is the error.

![Screenshot from 2021-09-02 23-39-01](https://user-images.githubusercontent.com/86566162/131895135-7541216a-d870-4f65-b3b9-3040f59d6002.png)

**Comment by tropxy** [comment]
Seems that that Delta Station is sending some empty message, which is violating the expected OCPP message format

**Comment by deepakEnercent** [comment]
> Seems that that Delta Station is sending some empty message, which is violating the expected OCPP message format

yes  that part i understood but is there any way that i can give some kind of dummy data to Delta charger so this error won't come again.  like iam getting empty list but can i do something like will store the previous value and will check like:


store = previous value

if empty _list from Delta:
       give back the previous value back to delta.


is this possible to do so i can make this error resolved.

**Comment by deepakEnercent** [comment]
Hi Thank you for the support and i found out the result and changed and deployed it and it's working fine.

**Comment by OrangeTux** [comment]
Great that the issue has been fixed.
