### ISSUE TITLE
Send requests from CSMS to CP / code flow

### ISSUE THREAD

**Issue by josesilva1995** [mobilityhouse/ocpp#247]
Hello,
I am new in python and async functions. So, I am not understanding the code flow of your example.
In your example, the CP send the BootNotification to CSMS and if Accepted, the Heartbeat function is called interspersed by interval time.
Then, I tried to send a message(GetBaseReport) from the CSMS to CP in boot_notification function. As you can see in first picture(code of CSMS).
However, I had the error asyncio.exceptions.CancelledError in second picture. I think I had this error because I sent a request from the CSMS to CP, when the CP was waiting one response from the CSMS. 
Thus, I dont know on what point of code I can send requests from the CSMS to CP. Because in your example, the CSMS is always sending responses.
![pythoncode](https://user-images.githubusercontent.com/84137846/132208420-2b4070e2-2899-4903-9a34-8f293a97f52f.PNG)
![output](https://user-images.githubusercontent.com/84137846/132208427-c947e484-bba3-4af1-9311-949f2d70f399.PNG)

**Comment by OrangeTux** [comment]
It seems that the CP doesn't answer the GetBaseReport. Can you try to put that code in a [`@after`](https://github.com/mobilityhouse/ocpp/blob/8da716971a87b278977d9a2296a051b6c5c77ace/ocpp/routing.py#L58-L81) handler?

**Comment by josesilva1995** [comment]
The CP answers the GetBaseReport. As you can see in the picture. I think it is not possible to send request inside another message. But I want to send the request whenever the user wants. For example when the user write in the keyboard "Send report". Is that possible??
I tried to replace @on('BootNotification') for @after('BootNotification') but I had the error in the second picture.
![outputCP](https://user-images.githubusercontent.com/84137846/132229530-939a0989-6cc2-40a1-b5ca-4eaf59722ec8.PNG)
![outputafter](https://user-images.githubusercontent.com/84137846/132229538-34e38f91-3c9d-4386-be50-e5da0a6929b5.PNG)

**Comment by OrangeTux** [comment]
I'm sorry for my unclear instructions. The second screenshot shows that no `@on()` handler for a BootNotification has been registered. With my previous suggest I meant to do this:

``` python
class ChargePoint(cp):
    @on('BootNotification')
    async def on_boot_notification(self, *args, **kwargs):
        return call_result.BootNotification(current_time=datetime.utcnow().isoformat(), interval=10, status='Accepted')
        
    @after('BootNotification')
    async def after_boot_notification(self, *args, **kwargs):
        await self.get_base_report()
```

> But I want to send the request whenever the user wants. For example when the user write in the keyboard "Send report". Is that possible??

Of course. Why wouldn't it be possible? You would need some task to listen for events. When the task registers an event it should execute the corresponding action.

**Comment by josesilva1995** [comment]
@OrangeTux that code is working. Now I send the request from the CSMS to CP after an response. Thank you...

 Regarding the task to listen for events. That seems to be a good idea, so I am going to learn about that and try,

Thank you and regards

**Comment by deepakEnercent** [comment]
> @OrangeTux that code is working. Now I send the request from the CSMS to CP after an response. Thank you...
> 
> Regarding the task to listen for events. That seems to be a good idea, so I am going to learn about that and try,
> 
> Thank you and regards

Hi Jose. can you show one implementation of @after as iam bit confused there.

**Comment by josesilva1995** [comment]
> > @OrangeTux that code is working. Now I send the request from the CSMS to CP after an response. Thank you...
> > Regarding the task to listen for events. That seems to be a good idea, so I am going to learn about that and try,
> > Thank you and regards
> 
> Hi Jose. can you show one implementation of @after as iam bit confused there.

You can see the code that @OrangeTux wrote. That is how I implemented @after

**Comment by OrangeTux** [comment]
Great that it worked!
