### ISSUE TITLE
Differenciating MeterValues between different physical CP's

### ISSUE THREAD

**Issue by StephenC808** [mobilityhouse/ocpp#254]
I am working with two physical CP's, both ABB and same model and am trying to differenciate the MeterValues from each of them. I can tell them apart from the transaction_id but cannot link that transaction id to the meter itself without looking at the terminal

INFO:ocpp:FRONT: receive message [2, "0774513", "MeterValues", {"connectorId": 1, "transactionId": 1632748233, "meterValue":...
INFO:ocpp:BACK: receive message [2, "0606942", "MeterValues", {"connectorId": 1, "transactionId": 1632747880, "meterValue":...

So essentially the meter serial numbers are FRONT and BACK which do not change and the transaction ID's change after each disconnect or power cycle. Is there a call from the CP to the central system or vice versa that contains both parameters so they can be linked from within the python code?

**Comment by OrangeTux** [comment]
For every  CP connecting to a CSMS a `ChargePoint` instance is created. This instance is passed to every method bound to it. It includes an attribute `id` that holds the CP ID. 

``` python
from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp, call_result


class ChargePoint(cp):
   @on("MeterValues")
   def on_meter_values(self, *args, **kwargs):
       print(f'{self.id} received a MeterValue')
       return call_result.MeterValuePayload()
```

Does that answer your question?

**Comment by StephenC808** [comment]
@OrangeTux Yes perfect, thank you
