### ISSUE TITLE
Code structure for Central System and event management

### ISSUE THREAD

**Issue by Velo-energy** [mobilityhouse/ocpp#261]
Hello,
I am trying to build a Central System in order to control and monitor several Charge Points. Although I have experience with python programming I am just starting with asyncio and I'm finding difficulties implementing the CS. Although I have watched and read several tutorials and guides on how to use asyncio I still can't figure out the whole code structure I should implement in order to achieve my goals. 
So far I have implemented succesfully some simple actions and I understand how OCPP protocol works (I'm using OCPP 1.6J), however what is not clear for me is how should I structure the code.
In the future I plan to run my server on a cloud service, which will be connected not only with the CPs but also with other cloud services where user could manage their chargers. So the CS should be able to handle events (for example ask for RemoteStartTransaction or any other request). This is where I'm finding problems, I don't know how to execute call functions when an event is received. Also some I need the code to still be running to perform several operations based on the information receive from the CPs and the cloud service. I don't know if all of this should be handled inside the callbacks or outside.
If anyone could give me some guidance on how to structure the code or some documentation on how to implement such a system I would really appreciated. 

Thank you so much for your time, best regards,

Andrés

**Comment by OrangeTux** [comment]
Similar questions have been asked before. See for example https://github.com/mobilityhouse/ocpp/issues/86 and https://github.com/mobilityhouse/ocpp/issues/263
