### ISSUE TITLE
SendLocalList, status: NotSupported

### ISSUE THREAD

**Issue by Velo-energy** [mobilityhouse/ocpp#265]
Hello,
I am trying to send a local authorization list to my charger from the server side, however I either receive a json schema validation error or a response from the charger saying NotSupported. In theory the CP does support this so I guess the problem is I am messing something up with the localAuthorizationList type or something like that. I have tried different things but nothing worked so far. Also, I noticed in the v201 enums.py file there is an idTokenType class (I'm using OCPP 1.6) so I tried importing that and using it, but no success either.
Can anyone tell me how I am supposed to format the sending of the SendLocalList request?

``` python
    async def send_local_list(self):
        response = await self.call(call.SendLocalListPayload(
            list_version=1,                         # int
            update_type=UpdateType.full,            # UpdateType
            local_authorization_list=[{"idTag": "admin"}]             # list
        ))
```

log:
`send [2,"0ea7c00f-b06b-4bcc-9100-d0cf974cf3aa","SendLocalList",{"listVersion":1,"updateType":"Full","localAuthorizationList":[{"idTag":"admin"}]}]
receive message [3,"0ea7c00f-b06b-4bcc-9100-d0cf974cf3aa",{"status":"NotSupported"}]`

Thank you for your time!

**Comment by OrangeTux** [comment]
See the [OCPP spec](OCPP spec) about the status "NotSupported", in particular sections 7.47:

> Update of Local Authorization List is not supported by Charge Point.

**Comment by Velo-energy** [comment]
Hello @OrangeTux, 
Thank you for your answer. Yes I saw that it means the CP doesn't support that feature, however the manufacturer tells me it does support it and there must be something wrong on my side. Could you confirm the format I showed in the code snippet in the question is correct?
Thanks for your time.
