### ISSUE TITLE
Central System documentation link

### ISSUE THREAD

**Issue by c0nr3f** [mobilityhouse/ocpp#266]
Nothing special but the Central System documentation link in your Readme.rst is not working due to a misspelling error i think.

`Central System documentation_`.

should be

`Central System documentation`_.

Keep up your great work :)

**Comment by OrangeTux** [comment]
Thanks for reporting!

**Comment by Jared-Newell-Mobility** [comment]
Resolved with https://github.com/mobilityhouse/ocpp/pull/526 - scheduled in next release
