### ISSUE TITLE
Store methods argument in any database

### ISSUE THREAD

**Issue by deepakEnercent** [mobilityhouse/ocpp#269]
``` python
class ChargePoint(cp):
    @on(Action.BootNotification)
    def on_boot_notification(self, charge_point_vendor: str, charge_point_model: str, **kwargs):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=10,
            status=RegistrationStatus.accepted
        )

```

I want to create a database where I want to store the data of boot_notification or other methods' argument(parameter) in a database. "like here the method is giving charge_point_model and charge_point_vendor. So, I just need an idea that how can I take the parameters of boot notification like "charge_poiunt_model" and store that in any other function or directly store it in the database. I'm completely new to this database and all I have done is store data that I am giving by myself but here struggling to store data where chargepoint(any charger) is giving its data in the argument of the methods.

From that method's argument, i want to either move it to class so I can parse the data according to my choice or send the data directly to database

Just a small idea or a rough sketch is enough to make me understand that how can I move forward. I need help on this topic.

**Comment by ishan3199** [comment]
> ```python
> class ChargePoint(cp):
>     @on(Action.BootNotification)
>     def on_boot_notification(self, charge_point_vendor: str, charge_point_model: str, **kwargs):
>         return call_result.BootNotificationPayload(
>             current_time=datetime.utcnow().isoformat(),
>             interval=10,
>             status=RegistrationStatus.accepted
>         )
> ```
> 
> I want to create a database where I want to store the data of boot_notification or other methods' argument(parameter) in a database. "like here the method is giving charge_point_model and charge_point_vendor. So, I just need an idea that how can I take the parameters of boot notification like "charge_poiunt_model" and store that in any other function or directly store it in the database. I'm completely new to this database and all I have done is store data that I am giving by myself but here struggling to store data where chargepoint(any charger) is giving its data in the argument of the methods.
> 
> From that method's argument, i want to either move it to class so I can parse the data according to my choice or send the data directly to database
> 
> Just a small idea or a rough sketch is enough to make me understand that how can I move forward. I need help on this topic.

Hi @deepakEnercent !! 
I am stuck in the same area, can you share some idea on how to store this methods and how did u solve it??
Thanks!!

**Comment by deepakEnercent** [comment]
Hi ishan.so the thing is that what python framework you are using and are you just using a plain python and had implemented this thing.And database completely depends on that.let me share a small instance with you like how iam storing that in db.
```python
 @on(Action.BootNotification)
   async def on_boot_notification(self, charge_point_vendor, charge_point_model, **kwargs):
      if await models.database.fetch_all(models.charger_info.select().filter(
         self.id == models.charger_info.c.id)):
         update_query = models.charger_info.update().filter(self.id == models.charger_info.c.id).values(
            id=self.id,
            device_model=charge_point_model,
            vendor=charge_point_vendor,
            charger_status='Unavailable'
         )
         await models.database.execute(update_query)
      else:
         query = models.charger_info.insert().values(
            id=self.id,
            device_model=charge_point_model,
            vendor=charge_point_vendor,
            charge_point_serial_number=kwargs['charge_point_serial_number'],
            charge_box_serial_number=kwargs['charge_box_serial_number'],
            charger_status='Unavailable'
         )
         await models.database.execute(query)
         
      return call_result.BootNotificationPayload(
         current_time=dt.utcnow().isoformat(),
         interval=100,
         status=RegistrationStatus.accepted
      )
```

you can try searching in database how to store data and just if you are using raw query it will be just like 1 line sentence.
good luck with that.

**Comment by ishan3199** [comment]
Hey Deepak! Sorry for the late reply!!
Firstly thanks for responding and Yes I am using the library by mobility house.
I am using simple mariaDB connection with my script and storing the values in the database. I know it is not recommended with  asyncio based script.

Can you explain the below line in your code:
models.database.fetch_all(models.charger_info.select().filter()
Is it fastAPI?

Thanks any help will be appreciated!!

**Comment by deepakEnercent** [comment]
Hey ishan.so iam using a framework i.e FastAPI but iam using ORM based models.that will be simple in writing and more understandble.you can search sqlalchemy orm

**Comment by ishan3199** [comment]
> Hey ishan.so iam using a framework i.e FastAPI but iam using ORM based models.that will be simple in writing and more understandble.you can search sqlalchemy orm

Ok ya that makes sense!!!
Thanks for your time deepak!!
