### ISSUE TITLE
charge_box_serial_number on Siemens EVlink Smart Wallbox is too long

### ISSUE THREAD

**Issue by bardahlm** [mobilityhouse/ocpp#273]
I have a Siemens EVLink Smart Wallbox.
I set up Home Assistant with the OCPP integration (https://github.com/lbbrhzn/ocpp).
It failed to get up and running, debugging showing:

```
ocpp.exceptions.ValidationError: Payload '{'chargeBoxSerialNumber': 'EVB1A22P2RI3N182341200100350795E5', 'chargePointModel': 'EVlink Smart Wallbox', 'chargePointSerialNumber': '3N18310641B55', 'chargePointVendor': 'Schneider Electric', 'firmwareVersion': '3.4.0.2'} for action 'BootNotification' is not valid: 'EVB1A22P2RI3N182341200100350795E5' is too long
```
I've read the standard over at https://www.oasis-open.org/committees/download.php/58944/ocpp-1.6.pdf and if I read it correctly this field should at max be 25 chars long. The string sent by the EVlink is 33 chars long and thus violates the standard.

After hacking ocpp/v16/schemas/BootNotification.json I got it up and running.
```
        "chargeBoxSerialNumber": {
            "type": "string",
            "maxLength": 64
        },
```

Can you accept payloads that violates the OCPP standard?

**Comment by proelke** [comment]
As you noted, their serial number violates the specification. To handle this, you need to set skip_validation to True in the @on decorator.

**Comment by bardahlm** [comment]
#122 and #128 are experiencing the same problem as described in this issue.
