### ISSUE TITLE
How to identify the Charging Station in any message

### ISSUE THREAD

**Issue by josesilva1995** [mobilityhouse/ocpp#281]
Hello,
I have a theoretical question.
According to OCPP2.0.1 Part 1 document. One Charging Station can have multiple EVSEs, and this can have multiple connectors.
In the BootNotificationRequest is required the model and vendorname, but in StatusNotificationRequest is not required that infomation.
So, how do I relate the information of StatusNotificationRequest(evseId,connectorId,...) to that especific ChargingStation??This way I can send information of one Charging Station and the CSMS related it with another Charging Station.
I think the message identify the Charging Station by "vendorId", but this is not required in JSON documents.
Someone can confirm me??

**Comment by josesilva1995** [comment]
Hum,
So I can associate any to connection to an instance. Thus, I can associate the messages to that specific Charging Station.
But I am true regarding the 'vendorId'. Right??
Thank you

**Comment by OrangeTux** [comment]
Yes. A connection is tight to an instance of `ChargePoint`.  In other words, 3 connections means 3 `ChargePoint` instances.

**Comment by josesilva1995** [comment]
Thank you @OrangeTux for your answers.
