### ISSUE TITLE
How to know which CS is disconnected.

### ISSUE THREAD

**Issue by josesilva1995** [mobilityhouse/ocpp#282]
Hello.
When one Charging Station disconnect from the CSMS, I have the error in the picture.
However, I want to which CS is associated to that disconnection.

Best regards,
![connection_lost](https://user-images.githubusercontent.com/84137846/146412984-0ffa0c0c-63d0-4d87-8c50-62d923e04928.PNG)

**Comment by OrangeTux** [comment]
This package is agnostic to the websocket implementation uses. Therefore, it can't provide generic mechanisms for handling disconnecting  chargers. You've to do that yourself.

Like so:

``` python
async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
  
    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
  
    try:
        await cp.start()
    except websockets.exceptions.ConnectionClosedOK:
        print(f"Charger {cp.id} disconnected")
```

**Comment by josesilva1995** [comment]
Hello @OrangeTux.Thanks for your reply again.
That information is about the id of the websocket. But is possible to associate the charger disconnected to the "model" and vendorName" provided by "BootNotification" message??

**Comment by OrangeTux** [comment]
Sure. You need to store that info and associate it with the connection specific `ChargePoint` instance. See also this issue: https://github.com/mobilityhouse/ocpp/issues/281

**Comment by josesilva1995** [comment]
Yes. I understood...
Thank you @OrangeTux
