### ISSUE TITLE
Sending data from CS to CP with user interaction

### ISSUE THREAD

**Issue by PLM0** [mobilityhouse/ocpp#283]
I'm using a tkinter window instantiated on a new thread to get input from a user, mainly for test support, after the GUI is created, the function forever_loop() is called, the def is :

```
def forever_loop(self):
        global EV_LOOP
        asyncio.set_event_loop(EV_LOOP)
        while True:
            if not self.commands.empty(): # instance of queue.Queue()
                data = self.commands.get() 
                if 'data_transfer' in data:     
                    EV_LOOP.create_task(self.cp.send_data_transfer(data['data_transfer']))
            self.main.update()
 async def call_send_data(self, data):
        await self.cp.call_send_data(data)
```

The code I provided works as expected, but with a small problem, the data is only sent from CS to CP when a heartbeat (or any other action) is given by the CP.
For example:
CP boot :                                             10:00:00
CS responds to boot at:                      10:00:00
CP heartbeat sent at :                          10:00:05
CS heartbeat response sent at :          10:00:05
Button pressed to send data at:          10:00:07
CP heartbeat sent at:                           10:00:10
CS responds to heartbeat at:               10:00:10
CS sends a data transfer request at:    10:00:10

If I press the button to send data multiple times, the data gathers inside the queue, then it's all consumed when a message comes from the CP.

From what I think, self._connection.recv() in the charge_point.py, class ChargePoint waits for something from the CP and doesn't execute anything else until it receives something. 

This is how I instantiate a CP:
```
async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint instance
    and start listening for messages.

    """
    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    #cp.GUI()
    cp.attach_pelo()
    #GUI_start_task = asyncio.gather(cp.parallel_command())
    test = window_test(cp)
    await cp.start()
```

So, how can I transfer data in real time and not have the asyncio coroutines block each other?

**Comment by OrangeTux** [comment]
I'm afraid I can't help much. Your issue is tightly related to tkinter, a project I'm not familiar with.
You mention that `tkinter` is working with threads. While this library is based on asyncio. Mixing sync and async code is easy to do wrong. In general, I would not recommend to join both idioms in a single application.

**Comment by PLM0** [comment]
Then how could I send data from the server to the CP by hand? For example with a simple data transfer, I want to send a string based on user interaction.

**Comment by proelke** [comment]
You can see an example of how to send a message in the example here: https://github.com/mobilityhouse/ocpp/blob/master/examples/v201/charge_point.py#L29-L41

**Comment by andcan86** [comment]
> Then how could I send data from the server to the CP by hand? For example with a simple data transfer, I want to send a string based on user interaction.

make a rest api to collect the user input and tell the (CS to tell the) CP what to do
