### ISSUE TITLE
How to handle responses from the Backend

### ISSUE THREAD

**Issue by c0nr3f** [mobilityhouse/ocpp#284]
I'm sorry if this sounds like a stupid question, but I'm just a hobby developer and kind of stuck here.

Regarding the classic example from the protocol (Authorize, StartTransaction, Authorize, StopTransaction), how can I handle the .conf responses from the charging stations ?

I have two seperate scripts as in the examples. The .req from the CP side works perfectly, but how can I handle the answer from the Charging Station ?

I initially thought on using `@on(Action.BootNotification)` to catch the call_result.BootNotification on CP side, but nothing happens.

**Comment by proelke** [comment]
If I understand correctly you are sending a `BootNotificationRequest` from a Charging Station script and getting a `BootNotificationResponse` and want to know how to handle it? If I understand correctly, this example will help: https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/charge_point.py#L29. The response variable holds the payload of the `BootNotificationResponse`.

**Comment by c0nr3f** [comment]
The example you linked shows only the request from the charging point to the backend/central station. The backend replies to that request with the BootNotificationResponse. This is the given example from the repo and this all works fine. 

I want to react to the central station from the charge point side. The BootNotification is actually just for explanation purposes, because I don't know how to react on the responses. 

Maybe a more intuitive example as described in the protocol: the charge point has to react to the Authorize.conf (call_result.AuthorizationPayload) with either a StartTransaction.req (call.StartTransactionPayload) or StopTransaction.req (call.StopTransactionPayload), depending on the current state (charging or not charging). 

As a potential solution I tried this inside the Chargepoint class, but I'm not sure if this is good practice.

`    async def send_boot_notification(self):
        request = call.BootNotificationPayload(
            charge_point_model="Python",
            charge_point_vendor="Test Script"
        )

        response = await self.call(request)

        if response.status == RegistrationStatus.accepted:
            logging.info("Connected to central system.")
            asyncio.create_task(self.send_authorize())
        elif response.status == RegistrationStatus.rejected:
            logging.info("Central system rejected the connection!")

    async def send_authorize(self):
        request = call.AuthorizePayload(
            id_tag='FED4269'
        )

        response = await self.call(request)

        if response.id_tag_info["status"] == "Accepted":
            logging.info("Authorization successful")
            return True
        else:
            logging.info("Authorization unsuccessful")
            return False
`
The main() stays the same. Is this the way to connect the different functions together or is it better to use the function decorators ´@on´ and ´@after´ to trigger the next function in the sequence ?

**Comment by proelke** [comment]
Ah for this I would use the @after decorator.

**Comment by c0nr3f** [comment]
Ok, can you give me a code example for this specific example ? Because 
```
    @after(Action.BootNotification)
    def after_bootnotification(self):
        create_task(self.send_authorize())
```
won't work.

**Comment by proelke** [comment]
Well in this case `create_task` is for async functions. However if you were to do something like this it should work:

```
    @after(Action.BootNotification)
    async def after_bootnotification(self, **kwargs):
        await self.send_authorize()
```

The code handling an after should see that it is an awaitable and await it using `ensure_future`.

**Comment by c0nr3f** [comment]
Ok, but this isn't working, either. Maybe because there is no "BootNotification" in the response.

ChargePoint Side:
```
INFO:ocpp:CP_3: send [2,"c43c7d51-3470-4724-98e9-c6761986d6e2","BootNotification",{"chargePointModel":"Python","chargePointVendor":"Test Script"}]
INFO:ocpp:CP_3: receive message [3,"c43c7d51-3470-4724-98e9-c6761986d6e2",{"currentTime":"2021-12-22T17:36:48.341833","interval":10,"status":"Accepted"}]
```

In the recieved message there is no "BootNotification", nor any other String I could use to trigger the `@after`.

This decorators work only on the recievers side I think (when you look from the Transaction initiators point of view, in this case the Charging Point).

**Comment by proelke** [comment]
This is definitely how the the after decorator works. If you look at the source, it adds an attribute to the function so it's added to the route map. Admittedly I've only used after in a sync way and not an async way. Perhaps there is a bug here.

**Comment by c0nr3f** [comment]
But then we are back at the question, how to handle the response from the backend. How would you code an Authorize call as a reaction to the BootNotification.conf ?

**Comment by OrangeTux** [comment]
The `@after()` is a post request hook.  It's triggered by requests, not responses.  Similar to the `@on()` decorator, that is only triggered by requests too, not responses. Therefore, the suggestion from @proelke  doesn't work. 

[Your code](https://github.com/mobilityhouse/ocpp/issues/284#issuecomment-999731099), @c0nr3f , works and makes sense to me. Although I suggest a small change: replace `asyncio.create_task(self.send_authorize())` with `await self.send_authorize()`.

Using a fire and forget strategy of tasks using `asyncio.create_task()` is dangerous. Errors raised during it's execution don't bubble up to the caller.
