### ISSUE TITLE
Update CI build so it builds when pushing a commit

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#291]
Currently, the unit tests are executed only when one creates a PR. To get feedback earlier in the development process, the CI build should run when one pushed to GH to any branch.

**Comment by jainmohit2001** [comment]
Is this still a requirement? I can work on creating a PR for this.

**Comment by mdwcrft** [comment]
I'd say we can skip this change, users should be able to run and pass the tests locally before opening a PR and we can make this explicit in the new docs
