### ISSUE TITLE
missing datatypes.py and enums.py in v2.0?

### ISSUE THREAD

**Issue by tb-78e** [mobilityhouse/ocpp#292]
Good morning,

I've been sucessfully implementing an ocpp-backend in v2.0.1 and I also need v2.0. 
But it seems that datatypes.py and enums.py files are missing in v2.0. 

Is this to bee expected, and I don't need them for a sucessfull v2.0 implementation? 
If not, would you be so kind and update them?

Cheers

**Comment by OrangeTux** [comment]
Hello @tb-78e,

I've not time planned to work on this myself. But I'm happy to receive a PR.

**Comment by Jared-Newell-Mobility** [comment]
In OCPP 2.0.1 section 1.1. It states that OCPP 2.0.1 version replaces OCPP 2.0. Moreover, OCA advises implementers of OCPP to no longer implement OCPP 2.0 and only use version 2.0.1 going forward. So it envisioned to reflect this that 2.0 will be removed from the library in future releases of 1.x +
