### ISSUE TITLE
If StatusNotification.info is None, a ValidationError is throw.

### ISSUE THREAD

**Issue by Rasmusmm96** [mobilityhouse/ocpp#296]
When a Charge Point sends a StatusNotificationPayload to the Central System, the following error is throw, if the info parameter is null.
```
ocpp.exceptions.ValidationError: Payload '{'connectorId': 1, 'errorCode': 'NoError', 'info': None, 'status': 'Unavailable', 'timestamp': '2022-01-27T14:42:15.1240977Z'} for action 'StatusNotification' is not valid: None is not of type 'string'
```

Here is the info debug:
```
INFO:ocpp:2108011897A: receive message [2,"6e445d08-bc1a-494f-b5f7-f52719b05eee","StatusNotification",{
  "connectorId": 1,
  "errorCode": "NoError",
  "info": null,
  "status": "Unavailable",
  "timestamp": "2022-01-27T14:42:15.1240977Z"
}]
```

StatusNotificationPayload.info is allowed to be None, so this seems to be an issue with the validate_payload function in ocpp/messages.py.

This is with ocpp1.6.

**Comment by proelke** [comment]
This seems to be an issue of the charger not implementing the OCPP specification correctly. The error indicates that the schema failed to validate the message. The schema is provided by the OCA and it indicates the key can be absent, but if it's present it needs to be of type string. This doesn't appear to be a bug in the library. To work around this, you could set the skip_validation parameter in the on decorator.

**Comment by Rasmusmm96** [comment]
Thank you the solution @proelke! It's probably easier to code around this issue, than to get the charging point manufacturer to fix their firmware 😊
