### ISSUE TITLE
v201/missing component and type enums

### ISSUE THREAD

**Issue by Shadowsith** [mobilityhouse/ocpp#300]
Shouldn't enum types for component and variable names also be added? 

Cf. **2. Referenced Components and Variables**, https://raw.githubusercontent.com/mobilityhouse/ocpp/master/docs/v201/OCPP-2.0.1_part2_specification.pdf from page 420 onwards

**Comment by OrangeTux** [comment]
Thanks for reporting the issue.

**Comment by Jared-Newell-Mobility** [comment]
PR open https://github.com/mobilityhouse/ocpp/pull/487

**Comment by Jared-Newell-Mobility** [comment]
Merged and will be included in the next minor release
