### ISSUE TITLE
Library for smart charging

### ISSUE THREAD

**Issue by betovaca** [mobilityhouse/ocpp#308]
Hi, I'm implementing OCPP but I have a little issue. 
How can you implement the smart charging block? If you have a Charging Profile with a Charging Schedule from 16h00 to 22h00 limited to 11kW, how do you implement a code for making this?

What library can we use in python to make a schedule like that? What's the best library to understand and make something daily?

Like how do you tell your code : when it's 16h00 do this and when it's 22h00 do this other thing

**Comment by OrangeTux** [comment]
I suggest to read the OCPP specification. For OCPP v1.6 you the SetChargingProfile call is used to limit charge rate. For OCPP 2.0.1 I suggest to read section K of the [specification](https://github.com/mobilityhouse/ocpp/blob/master/docs/v201/OCPP-2.0.1_part2_specification.pdf).
