### ISSUE TITLE
Schedule the remote start and stop

### ISSUE THREAD

**Issue by stStavropoulos** [mobilityhouse/ocpp#309]
Hello everyone!

I have created a charging point and CSMS scripts successfully with a structure similar to the examples you have in the repository. Now what I want to do is to do the remote start and stop charging but at a specific hour: e.g. at 17:30 I want to do the remote start procedure and at 19:30 that the charging will be over according to a timetable, I want to do the remote stop charging. However the whole asynchronous logic is still a bit confusing to me. Do you have any ideas of how should I approach the subject?

Thanks!

**Comment by fusionJose** [comment]
Can you share those scripts?

**Comment by ishan3199** [comment]
Maybe you can make an API using fastAPI and then trigger a remote start request at a particular time interval using scheduler or asyncioscheduler.
