### ISSUE TITLE
Send transaction with event_type = 'Update'

### ISSUE THREAD

**Issue by betovaca** [mobilityhouse/ocpp#311]
Hi, 
This question is only about python and not the protocol.
How do you send periodically the transacion_event_request once a transaction started?
I'm actually implementing the use case E02 from OCPP 2.0.1 and I managed to start the energy offer but I can't receive my meter values from this problem:

I'm using aioconsole to send my requests, which is working fine, but when it comes to the **transaction** with event type **updated** it blocks all the inputs from the console

I tried making an
```
await asyncio.sleep(txupdatedinterval) 
await send_transaction_event_request(...)
```

But the asyncio.sleep blocks my console and I can't do any other task from the CS. My goal is to send an send_transaction_event_request(event_type='Ended') from the console but I can't. So I'm stuch in my ongoing transaction and I can't stop it.

Do you have an idea to help me?

**Comment by Jared-Newell-Mobility** [comment]
It is a little difficult to replicate the problem, the logs from the CS could be helpful. In addition, the implementation of the CS could also be helpful, as it looks to have more functionally then what is included in this library.

It looks as though this question has gone stale, I will close it for now.
