### ISSUE TITLE
Wrong keyword in FirmwareType (2.0.1)

### ISSUE THREAD

**Issue by ephraim** [mobilityhouse/ocpp#313]
https://github.com/mobilityhouse/ocpp/blob/3bd72bab4b602d82bd6bfd7321ac23aba94bb3ef/ocpp/v201/datatypes.py#L412

Shouldn't this be called: "retrieve_date_time" instead of "retrieval_date_time"?

**Comment by Jared-Newell-Mobility** [comment]
Yes, in 2.24. FirmwareType - retrieveDateTime is specified

**Comment by Jared-Newell-Mobility** [comment]
This appears to be stale, as it has been correct - so I'll close this request
