### ISSUE TITLE
Typo in action enum DiagnosticsStatusNotification

### ISSUE THREAD

**Issue by mkirche** [mobilityhouse/ocpp#32]
In ocpp/v16/enums.py on line 11:

` DiagnosticStatusNotification = "DiagnosticStatusNotification"`

It should be

`DiagnosticsStatusNotification = "DiagnosticsStatusNotification"`

(Diagnostic**s** instead of Diagnostic). This is validated by the naming of the respective json schema in ocpp/v16/schemas/

The same error occurs in  ocpp/v16/call_result.py on line 35:
`class DiagnosticsStatusNotificationPayload:`
and in ocpp/v16/call.py on line 158:
`class DiagnosticsStatusNotificationPayload:`

The latter causes an error in a call, as the call action gets parsed from the payload class name (ocpp/v16/charge_point.py, line 238):

`action=payload.__class__.__name__[:-7],`

Schema DiagnosticStatusNotification.json doesn't exist which causes a ValidationError in ocpp\messages.py", line 85, in validate_payload:
`ocpp.exceptions.ValidationError: Failed to load validation schema for action 'DiagnosticStatusNotification': [Errno 2] No such file or directory: '.../ocpp/v16/schemas/DiagnosticStatusNotification.json'`

**Comment by OrangeTux** [comment]
Thanks for reporting this issue!

I have a PR up to fix the typo in DiagnosticsStatusNotification. 

But I don't understand what is wrong with FirmwareStatusNotificationPayload, could you elaborate?

**Comment by mkirche** [comment]
So sorry, I of course meant DiagnosticsStatusNotificationPayload. I went ahead and updated my issue description. Thanks for the quick response.

**Comment by mkirche** [comment]
Thanks for the quick resolution of the issue.

I am currently working on integrating this library in a charging station. 
Do you have a process/policy for contributing to this project should I have further suggestions, or is opening issues the preferred way for you?
