### ISSUE TITLE
Sending from Central System

### ISSUE THREAD

**Issue by Finalgamer14** [mobilityhouse/ocpp#325]
So question I have setup a basic Central System it receives requests from the CP.

But how does one actually then implement calls from CS to CP. I have system where main thread starts two threads one flask HTTP thread for REST API calls and one for OCPP 1.6, the main thread also does some other tasks. The threads between each other communicate via a queue, so how would I send requests to the CP?

I think the documentation around sending from CS to CP is lacking.

**Comment by ishan3199** [comment]
This thread can provide you some good insight!!

https://github.com/mobilityhouse/ocpp/issues/86

**Comment by OrangeTux** [comment]
This package is `async` and not thread safe. I wouldn't recommend to use this package in the setup you describe.

I guess it's not impossible, but it's tricky do execute correctly.
