### ISSUE TITLE
> Hey, I am stuck at the same place that is the CMS receives the HTTP post request but the reset function is not triggered.

### ISSUE THREAD

**Issue by ishan3199** [mobilityhouse/ocpp#327]
> Hey, thanks for the help and I really appreciate you found out the issue and now I have solved that issue and the issue was I was giving different objects to the same class that was made to connect to the server. You can now close this issue.

Hey deepak !! I am confused
can you please elaborate? I am also not able to send remote start PDU same way as you were not able to send reset here.
I am too using FASTapi.

Thanks in advance buddy!!

_Originally posted by @ishan3199 in https://github.com/mobilityhouse/ocpp/issues/263#issuecomment-1081751828_

**Comment by ishan3199** [comment]
So the HTTP request is received at CMS but it does not trigger the reset function defined in the central system. 
Just need some elaboration and I will take it from there.

**Comment by OrangeTux** [comment]
Please keep the discussion in the original thread #263
