### ISSUE TITLE
OCPP python based server deployment on HEROKU

### ISSUE THREAD

**Issue by ishan3199** [mobilityhouse/ocpp#328]
Hello people! Ishan here! an OCPP enthusiast.
Firstly this OCPP library is truly awesome by all means and also the community here is truly helpful.

So the thing is that I successfully tested the ocpp server by mobility house integrated with aiohttp api in local network. But now I am deploying the websocket server integrated with the HTTP api to heroku and the chargepoint script connects to the websocket server succesfully and OCPP is happening but the http endpoint is not reachable through curl through CMD by using the domain name URL.  Actually this was working perfectly when I reached the http server in local network using curl localhost:PORT command in CMD. But after deploying it is not.

On the server log It displays this:
heroku[router]: at=info method=POST path="/reset" host=ocpp.herokuapp.com request_id=43e705f-85c-48f-8273-002e5e9f3ed8 fwd="22.22.216.2" dyno=web.1 connect=0ms service=1ms status=400 bytes=242 protocol=http
-As seen above the http connection is received but it is not doing anything.

On the CMD curl Output  was this:
Failed to open Websocket connection: did not receive a valid http request.

I am using the below mentioned type of code for this:
https://github.com/mobilityhouse/ocpp/issues/86#issuecomment-620205346

Any help will be awesome for me as well as other stuck out there in this scenario.

Thanks for your time.

**Comment by OrangeTux** [comment]
This question seem to be related to Heroku and/or aiohttp and not with this package. Therefore, I close this issue.

**Comment by ishan3199** [comment]
@OrangeTux Ok no problem !!!

**Comment by ishan3199** [comment]
Thanks for the help! I solved this issue

**Comment by ConnieLWY** [comment]
> Thanks for the help! I solved this issue

Hi, How u solve the issue?

**Comment by patelishan1** [comment]
Can you reach out to me on my email please?
