### ISSUE TITLE
Request Timeout Until Reconnect

### ISSUE THREAD

**Issue by Aashutosh3804** [mobilityhouse/ocpp#338]
Sometimes I dint get 'CALL' response in time its gets timeout error, but soon as I disconnect the charger from the server and when it reconnects on its own the 'CALL' are working fine .
Its happening with some of the charger they send heartbeat at regular interval but don't respond to Call like(remoteStart,clearCache,reset etc.)
It mostly happens after charger is idle for long time , it doesn't respond to any CALL but regularly send heartbeat ,until it reconnects 

FYI
This particular vendor don't support ping/pong message so have diasabled them in in web socket. hope that is not causing any issue

` websockets.serve(handler, "0.0.0.0", 5609, subprotocols=["ocpp1.6"], ping_interval=None, ping_timeout=None)`

**Comment by Aashutosh3804** [comment]
> Sometimes I dint get 'CALL' response in time its gets timeout error, but soon as I disconnect the charger from the server and when it reconnects on its own the 'CALL' are working fine . Its happening with some of the charger they send heartbeat at regular interval but don't respond to Call like(remoteStart,clearCache,reset etc.) It mostly happens after charger is idle for long time , it doesn't respond to any CALL but regularly send heartbeat ,until it reconnects
> 
> FYI This particular vendor don't support ping/pong message so have diasabled them in in web socket. hope that is not causing any issue
> 
> ` websockets.serve(handler, "0.0.0.0", 5609, subprotocols=["ocpp1.6"], ping_interval=None, ping_timeout=None)`

Any help will be appreciated

**Comment by Jared-Newell-Mobility** [comment]
As this issue is difficult to reproduce and the age of the issue - I will close this for now.

**Comment by Mynk96** [comment]
Hey @Aashutosh3804 were you able to figure out the issue and solve the same. I am facing the same issue.
