### ISSUE TITLE
How send MeterValueSampleInterval ?

### ISSUE THREAD

**Issue by Ataraxiall** [mobilityhouse/ocpp#347]
Good morning,

I need to implement the MeterValueSampleInterval option, but I am not very clear about the format and when I should send it. does it have to be at the beginning? Would sending this for example be worth it?
{MeterValueSampleInterval:10} 
Thanks in advance

**Comment by Ataraxiall** [comment]
hello again,

I have been able to correctly send both the values ​​and the .

What I don't get now is knowing how to apply it automatically in the boot notification.

i have tried this

But it's not working

                    response = call_result.BootNotificationPayload(
                        current_time=datetime.now(timezone.utc).isoformat(),
                        interval=self.charge_point.heartbeat_interval,
                        status=RegistrationStatus.accepted
                    )
                    response = call.ChangeConfigurationPayload(key="MeterValuesSampledData",
                      value="Current.Import,Energy.Active.Import.Register,Power.Active.Import,SoC,Voltage,Temperature")


any help to apply this config?

Thanks!

**Comment by Jared-Newell-Mobility** [comment]
This appear to have gone stale
