### ISSUE TITLE
How to implement AuthorizePayload?

### ISSUE THREAD

**Issue by stig888881** [mobilityhouse/ocpp#348]
I'm new to working with JSON, tell me how to implement the server response during authorization? I had this option, but it gives an error and the server crashes.
`    @on('AutorizePayLoad')
    async def autorize(self, id_token, **kwargs):
        return call_result.AuthorizePayload(
            id_token_info={
                'status':'Accepted'
            }
        )`
My authorization request is like this, and it seems to be correct.
`    async def send_autorize(self):
        req=call.AuthorizePayload(
            id_token={
                'idToken': '123456789123456789123456789123456789',
                 'type' : 'Central'
            }
        )`
Tell me how to do it right ?

**Comment by deepakEnercent** [comment]
You need to understand then how JSON works and how are the datatypes being sent to the chargers(OCPP Compliant).if you can send hearbeat payload or any ocpp functionalities.The same goes for Authorize payload.

**Comment by stig888881** [comment]
> 

Could you give an example of authorization for OCPP 2.0 ? For server and client ? I think it would help me figure it out.

**Comment by deepakEnercent** [comment]
> > 
> 
> Could you give an example of authorization for OCPP 2.0 ? For server and client ? I think it would help me figure it out.

Have you seen the OCPP 2.0 datasheet.??Follwo that and you wil, get to know easily what iam saying.

https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf
Follow this and you will get to know what to send and receive
if still you have doubt then reply here.

**Comment by stig888881** [comment]
> > > 
> > 
> > 
> > Could you give an example of authorization for OCPP 2.0 ? For server and client ? I think it would help me figure it out.
> 
> Have you seen the OCPP 2.0 datasheet.??Follow that and you will get to know easily what iam saying.
> 
> https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf Follow this and you will get to know what to send and receive if still you have doubt then reply here.

Could you look at my sample code above and tell me what's wrong with it, I read the documentation and I think I did everything right.

**Comment by deepakEnercent** [comment]
You need to study the document more clearly as in the document for the Authorize payload there is no kwargs needed as only one parameter is there so your code will be like this:

```python

 @on(Action.Authorize)
    async def on_authorize(self, id_tag: str):
        return call_result.AuthorizePayload(
            id_tag_info={
                'status': 'Accepted'})

```

**Comment by stig888881** [comment]
> You need to study the document more clearly as in the document for the Authorize payload there is no kwargs needed as only one parameter is there so your code will be like this:
> 
> ```python
>  @on(Action.Authorize)
>     async def on_authorize(self, id_tag: str):
>         return call_result.AuthorizePayload(
>             id_tag_info={
>                 'status': 'Accepted'})
> ```

Thks
