### ISSUE TITLE
No response for remote trigger messages

### ISSUE THREAD

**Issue by Aashutosh3804** [mobilityhouse/ocpp#350]
Sometimes charger is sending heart bean but gets response timeout whenever do remote transaction like RemoteStartTransaction,RemoteStopTransaction,ClearCache,Reset etc.
Every call is getting response timeout but heartbeat is coming from charger , also this particular vendor do not support ping pong messages so it has been disabled in web socket
After charger restarts everything works fine , but again after some time same is issue is coming. Any help will be appreciated

**Comment by OrangeTux** [comment]
Can you verify the if the charger responded? For example, by using Wireshark?

**Comment by Jared-Newell-Mobility** [comment]
Closed - as this is specific to an implementation and it has become stale
