### ISSUE TITLE
First Time Use

### ISSUE THREAD

**Issue by OldCrow2018** [mobilityhouse/ocpp#354]
I am trying to use the Charge Point in conjunction with STEVE as the central server. Can anyone point me in the right direction on getting the charge point running? When i downloaded the zip and tried to change the charge_point.py to an executable i am getting the following errors: 

 ./charge_point.py: line 1: import: command not found
./charge_point.py: line 2: import: command not found
./charge_point.py: line 4: try:: command not found
./charge_point.py: line 5: import: command not found
./charge_point.py: line 6: except: command not found
./charge_point.py: line 7: syntax error near unexpected token `"This example relies on the 'websockets' package."'
./charge_point.py: line 7: `    print("This example relies on the 'websockets' package.")'

Thanks in advance for the help!

**Comment by Entropy512** [comment]
Looks like the examples don't have the usual #! on the first line indicating to a shell which interpreter is to be used

For example, most python scripts would have something like:
#!/usr/bin/env python3

as the first line, telling the shell to use python3 as the interpreter

Try:
python3 ./charge_point.py

**Comment by OldCrow2018** [comment]
I appreciate it, thank you
