### ISSUE TITLE
asynchronous tasks one after another

### ISSUE THREAD

**Issue by stStavropoulos** [mobilityhouse/ocpp#362]
Hello!

I implemented a charging point and a CSMS based on the examples and comments I found, and now, I want to implement a full charging scenario for smart charging.
![image](https://user-images.githubusercontent.com/66972298/187476672-9939587f-07b6-45f5-977c-a234a226bb1c.png)
![image](https://user-images.githubusercontent.com/66972298/187476795-02269901-64bd-4747-9beb-6f3698adff87.png)

The CSMS:
![image](https://user-images.githubusercontent.com/66972298/187477068-1dc7169d-301c-40b3-8570-560e0f7fd81a.png)

The script:
![image](https://user-images.githubusercontent.com/66972298/187477281-b98f5db3-fe44-4f95-9558-02b9615cbc13.png)

So my problem is that after I receive the answer from the CSMS for the authorization, I want the coroutine to be terminated and go to the next step which is the start transaction. When the start transaction receives an answer to go to the remote start of charging and goes like this. But what happens is that is stuck there and waiting. Do you have any idea what should I do?

Thanks!

**Comment by OrangeTux** [comment]
> I want the coroutine to be terminated 

Which one?

> after I receive the answer from the CSMS for the authorization, [...] and go to the next step which is the start transaction.

Seems like you might need the[ `@after()`](https://github.com/mobilityhouse/ocpp/blob/fdfb5b1b33665dad13708b47226f48b56ee6b438/ocpp/routing.py#L58-L80) decorator.

**Comment by stStavropoulos** [comment]
Maybe I wasn't very clear. Sorry about that. 
![image](https://user-images.githubusercontent.com/66972298/187642872-f9b738c6-8e04-4cb9-b4bb-b772265a6b97.png)

I meant this part here, the asyncio.gather should collect an answer from the csms. Here is what CSMS does:
![image](https://user-images.githubusercontent.com/66972298/187650185-a92847ba-6a12-4880-a3f1-fdb7fe1bb8e6.png)

And here is what the charging point sees:
![image](https://user-images.githubusercontent.com/66972298/187650376-8a03f9ca-c10f-4537-bd31-30187ef73e0b.png)

After I receive this answer, I want to store it and run another coroutinee for the remote start and stop, but the asyncio.gather is stuck there after the answer.

**Comment by OrangeTux** [comment]
Thanks for clarifying. It seems that you're question is more related to `asyncio`, than this library. I suggest to take a look at the documentation of[ `asyncio.gather()`](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) and `asyncio.wait()`. 

The docs of  `asyncio.gather()` state:

> If all awaitables are completed successfully, the result is an aggregate list of returned values. The order of result values corresponds to the order of awaitables in aws.

`asyncio.wait()` seems what you need. Quoting the docs:

> Run [awaitable objects](https://docs.python.org/3/library/asyncio-task.html#asyncio-awaitables) in the aws iterable concurrently and block until the condition specified by return_when.

**Comment by stStavropoulos** [comment]
The use of wait never receives something:

![image](https://user-images.githubusercontent.com/66972298/187656695-6b027147-5915-4f5b-8abc-79cbe62f3f8c.png)

It also didn't work with other conditions, only gather receives the answer fromt he CSMS.

Thanks again!
