### ISSUE TITLE
json schmemavalidation fails on type any - change configuration type incorrect

### ISSUE THREAD

**Issue by DanielMues** [mobilityhouse/ocpp#366]
im currently implementing the Change Configuration message initiated by the central system.
Everything worked fine, till I wanted to sent an integer as the value.
I get following error (im am working for v1.6):
![image](https://user-images.githubusercontent.com/54837088/189368248-4ce8e291-6789-4538-aa34-c8034e0865f6.png)

The Payload looks like this:
`{"somestring": 1}`
here it gets created:
![image](https://user-images.githubusercontent.com/54837088/189368811-ce235f37-a23d-4195-863f-ed4c696bf154.png)
it should work because the value type is any:
![image](https://user-images.githubusercontent.com/54837088/189368977-fb7e2efe-3964-42a0-8479-f929fb57cd96.png)

any idea what is causing this?

**Comment by OrangeTux** [comment]
You found a bug. Thanks! The type of `value` must be `str`.

The json schema's are leading as they're provided by the Open Charge Alliance (OCA). The OCA develops OCPP.

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/525 created and approved for addition in release v1.0.0
