### ISSUE TITLE
Automatic sending of Measurands by charger?

### ISSUE THREAD

**Issue by precabal** [mobilityhouse/ocpp#368]
Hi, after reading the OCPP 1.6 standard, I haven't been able to receive on the central system side, the measurands from the charging station, _except_ for when I send a trigger message to the unit for it to generate them. 

The charger config's relevant lines are: 

```
"ClockAlignedDataInterval":	"300",
"MeterValueSampleInterval":	"15",
"MeterValuesAlignedData":	"Current.Import,Energy.Active.Import.Register,Voltage,Current.Offered,Temperature,SoC",
"MeterValuesSampledData":	"Current.Import,Energy.Active.Import.Register,Voltage,Current.Offered,Temperature,SoC",
```
Here's an example of the Measurands received while the unit is charging, triggered with a TriggerMessagePayload:
```
[{'timestamp': '2022-09-12T13:39:49Z', 'sampled_value': [{'value': '137428.0', 'context': 'Trigger', 'measurand': 'Energy.Active.Import.Register', 'unit': 'Wh'}, {'value': '211.9', 'context': 'Trigger', 'measurand': 'Voltage', 'phase': 'L1-N', 'unit': 'V'}, {'value': '9.0', 'context': 'Trigger', 'measurand': 'Current.Import', 'phase': 'L1', 'unit': 'A'}, {'value': '1.907', 'context': 'Trigger', 'measurand': 'Power.Active.Import', 'unit': 'kW'}, {'value': '22.0', 'context': 'Trigger', 'measurand': 'Temperature', 'unit': 'Celsius'}]}]
INFO:ocpp:ocpp/CentralSystemService/A04220212242: send [3,"16629899891230846",{}]
```
Is there any additional config to tell the charger to send the measurands at the specified interval? 

I _am_ receiving Action.BootNotification, Action.Heartbeat, Action.StatusNotification, which I'm handling. 
Also, I'm receiving Action.Authorize, and Action.StartTransaction, although I've not implemented a handler for these, don't know if it might be related as it is raising an exception when received. 
Finally, when I restart the sever, I do not get a new BootNotification, unless I restart the charger. I'm unsure if this means the Charging unit is unregistered then and may have an impact in not receiving the Measurands...

**Comment by eeveefox** [comment]
Hi.
Is Free mode on at the station, by any chance?
It happened on one of my stations that 
ClockAlignedDataInterval should be set to 0 and the default FreeVendMode should be turned off

**Comment by eeveefox** [comment]
> Also, I'm receiving Action.Authorize, and Action.StartTransaction, although I've not implemented a handler for these
How do you start a charging session without StartTransaction?

**Comment by eeveefox** [comment]
>Finally, when I restart the sever, I do not get a new BootNotification, unless I restart the charger. I'm unsure if this means the Charging unit is unregistered then and may have an impact in not receiving the Measurands...

Read 1.6 doc pls
>The Charge Point SHALL send a BootNotification.req PDU each time it boots or reboots. Between the physical
power-on/reboot and the successful completion of a BootNotification, where Central System returns Accepted or
Pending, the Charge Point SHALL NOT send any other request to the Central System. This includes cached
32messages that are still present in the Charge Point from before.

**Comment by precabal** [comment]
Hey, thanks for your reply. 

> ClockAlignedDataInterval should be set to 0 and the default FreeVendMode should be turned off
There is no FreeVendMode field in the config when querying the charger for it. Also, could the Clock aligned data different than 0 interfere with the measurands? I set it up greater than zero with the opes of getting data at least from the other method...  

> How do you start a charging session without StartTransaction?
Manually, there was an RFID token used to authorize transactions locally (the charger is in a different city so I'm talking over the phone with the owner there).


> Read 1.6 doc pls
> 
> > The Charge Point SHALL send a BootNotification.req PDU each time it boots or reboots. Between the physical
> > power-on/reboot and the successful completion of a BootNotification, where Central System returns Accepted or
> > Pending, the Charge Point SHALL NOT send any other request to the Central System. This includes cached
> > 32messages that are still present in the Charge Point from before.

I did take a look at this, however I felt it was unspecific in terms of defining the behavior of a Charge Point that hasn't received a BootNotification.conf.

**Comment by Jared-Newell-Mobility** [comment]
It appears as though the start transaction was not implemented on the central system. It resulted in an exception, where in 4.8 of OCPP 1.6 failing of the central system to respond with StartTransaction.conf should not occur. As a result this will only cause the charge point to repeatedly attempt to sent the StartTransaction.req and therefore the MeterValue.req that is normally sent next is never sent from the charge point. So the StartTransaction message would need to be implemented completely on the central system as per the protocol.
