### ISSUE TITLE
`v201.datatypes.ChargingNeedsType.request_energy_transfer` is mistyped

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#373]
The attribute should be named `requested_energy_transfer`. 

https://github.com/mobilityhouse/ocpp/blob/cbf17a5523d8865a001fb7928e50957e2eab0822/ocpp/v201/datatypes.py#L98-L104

**Comment by Jared-Newell-Mobility** [comment]
Satisfied with PR https://github.com/mobilityhouse/ocpp/pull/496 - for inclusion in the next major release

**Comment by Jared-Newell-Mobility** [comment]
Referenced in https://github.com/mobilityhouse/ocpp/issues/174
