### ISSUE TITLE
Send messages to the server with same message id

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [mobilityhouse/ocpp#376]
I am trying to implement TransactionMessageAttempts and TransactionMessageRetryInterval keys, I want to send the same payload and also with the same message id. Is there any way to implement this?

**Comment by ChaitanyaYeole02** [comment]
@OrangeTux any suggestions?

**Comment by ChaitanyaYeole02** [comment]
Any suggestion on how can you implement these configuration keys into CP?

**Comment by HiGregory** [comment]
Hi @ChaitanyaYeole02 - 

We have a server-side API that can support this. Unsure if you are open to a 3rd party vendor solution.

If not, hope you get this answered.

**Comment by Jared-Newell-Mobility** [comment]
OCPP 1.6 defines the retry of failed message in Open Charge Point Protocol 1.6 Section 3.6.1. 

Error responses to transaction-related messages - in this case if a transaction related message is sent from the charge point and no acknowledgement is received e.g. StartTransaction.conf, MeterValues.conf, StopTransaction.conf then the message should be sent again. 

However, this is a little outside of this library as how this is implemented in code is up to the charge point developer. IMHO I would expect a queue retains all messages. Where an attempt is made to deliver them, if a .conf message is not received then they are place possibility in a retry queue and attempted again following the configuration keys TransactionMessageAttempts and TransactionMessageRetryInterval
