### ISSUE TITLE
Integration with flask-socketIO

### ISSUE THREAD

**Issue by frmunozForcast** [mobilityhouse/ocpp#380]
I'm wondering if this library could work with flask using something like [Flask-SocketIO](https://github.com/miguelgrinberg/Flask-SocketIO)? at first sight I could guess that it would require some modification, but I'm not sure where to start. Does anyone has tried something like this before?. Thanks.

**Comment by HiGregory** [comment]
Hi @frmunozForcast,

Flask is sync and this package is async. So it doesn't mix. [See Thread in 2019 (https://github.com/mobilityhouse/ocpp/issues/20)

Here is a small example of CSMS integrated with an HTTP API that another commenter left [HTTP API](https://github.com/mobilityhouse/ocpp/issues/86)

We took a different approach and built a unified API to pull various standards like OCPP at the DB level to help developers and data teams track their assets better. But that doesn't use Flask as a library.
