### ISSUE TITLE
FormatViolation serialization bug with OCPP 1.6-J

### ISSUE THREAD

**Issue by rtrbt** [mobilityhouse/ocpp#381]
While testing my OCPP Charge Point implementation I've noticed that https://github.com/lbbrhzn/ocpp that in turn uses this library sends FormatViolation errors with the error code set to "FormatViolation". While this looks correct at first glance, the spec spells this error code as "FormationViolation" and the OCPP 1.6-J Errata sheet states

> Incorrect name in enum: FormationViolation
> Old text FormationViolation
>New text FormatViolation
>Do not fix, this is a message level change, might break implementations
>Note: In the next version of OCPP we will add the correct spelling and make the incorrect (typo) value
>deprecated.

under section "5. Known issues that will not be fixed -> 5.2"

By the way, the other issue that will not be fixed (5.1) is a typo in the error code Occu_rr_enceConstraintViolation that is spelled as "Occu_r_enceConstraintViolation". I've only found the wrong (i.e. OCPP 1.6-J compatible) spelling in your repo, so maybe this is broken in OCPP 2.0? (Assuming that OCPP 2.0 fixed this.)

**Comment by Jared-Newell-Mobility** [comment]
Thanks for highlighting this; OCPP 2.0.1 has corrected this, which makes the incorrect (typo) value deprecated.
------------
CALLERROR(OccurenceConstraintViolation)
CALLERROR(FormatViolation)
