### ISSUE TITLE
ISO 15118 OCPP 1.6 

### ISSUE THREAD

**Issue by vagio** [mobilityhouse/ocpp#387]
Hello, does anyone know how to use iso 15118 in ocpp 1.6?

**Comment by a-alak** [comment]
I don't think it is supported in cpp 1.6. I think it is implemented in ocpp 2.0.

**Comment by Jared-Newell-Mobility** [comment]
Sorry, for OCPP 1.6 the IEC61851-1 protocol is used between charge point and the EV. OCA advises not to used OCPP 2.0 and implement 2.0.1 which implements ISO 15118.
