### ISSUE TITLE
OCPP websocket server across multiple servers

### ISSUE THREAD

**Issue by g-a-pet** [mobilityhouse/ocpp#389]
Hello !
Has anyone attemted integrating redis /websockets and this great package ?
I'm interested if it's possible to use this across multiple vps / workers .

**Comment by ChaitanyaYeole02** [comment]
@OrangeTux Can we share the websockets object created using ChargePoint across multiple workers to send messages to CP?

**Comment by OrangeTux** [comment]
Generally, I would advice against sharing websockets. Because that is sharing mutable state which state which can leads to race conditions (and therefore isn't allowed by strict languages like Rust). Instead, I would suggest to use queues and messages passing.

**Comment by g-a-pet** [comment]
@ChaitanyaYeole02 @OrangeTux 
I ended up using exactly that:
Message queues.
It takes a bit of work but can be done.
Now this is in no way necessary unless you got A LOT of chargers.

**Comment by deepakEnercent** [comment]
> @ChaitanyaYeole02 @OrangeTux I ended up using exactly that: Message queues. It takes a bit of work but can be done. Now this is in no way necessary unless you got A LOT of chargers.

Hello.have you got any resource of how to start using message queue with this package.or just a summary of how to use.??

**Comment by ChaitanyaYeole02** [comment]
Instead of queue, have you tried using Coordinator service, something like Manager Service Approach?

**Comment by ChaitanyaYeole02** [comment]
If you need any help in implementing that, then let me know.

**Comment by deepakEnercent** [comment]
yeah. Any source code or just the understanding of how it's done. any help will be a big help to me.
