### ISSUE TITLE
How to Implement Central System on AWS?

### ISSUE THREAD

**Issue by gowthamreddythumu** [mobilityhouse/ocpp#394]
Hii!
I want to implement OCPP central system on AWS, is it possible?
If possible, please help me anyone how to implement that one?
I am using Raspberry Pi as a Client

**Comment by tropxy** [comment]
Hi, yes it is possible. You have to create an EC2 instance, install python and the prokect and run your CSMS there. There are plenty of tutorials on how to create one: https://www.guru99.com/creating-amazon-ec2-instance.html

The hard part may be to expose the CSMS URL to the outside in a fix IP and custom URL, but for that you can play around with Elastic IP and maybe route 53 of aws

**Comment by gowthamreddythumu** [comment]
@tropxy 
I have to send all Charging data to dyanamo DB and make it available to end user through API 
For that is it required to use AWS lamda?

**Comment by Jared-Newell-Mobility** [comment]
AWS offers a number of options for the deployment of a CSMS (OCPP central system ) on their platform, support documentation available for their services may offer better insight for application deployment and configuration on their services.
