### ISSUE TITLE
how to create OCPP scenario between CP and CS

### ISSUE THREAD

**Issue by andreas19733791** [mobilityhouse/ocpp#396]
I am a beginner trying to make an OCPP program, based on the existing CP example , I modified it as follows

import asyncio
import logging
import websockets
from datetime import datetime

from ocpp.routing import on
from ocpp.v16 import ChargePoint as cp
from ocpp.v16.enums import Action, RegistrationStatus, FirmwareStatus, ChargePointErrorCode, ChargePointStatus, CancelReservationStatus
from ocpp.v16 import call, call_result

#logging.basicConfig(level=logging.ERROR)
logging.basicConfig(level=logging.INFO)

class ChargePoint(cp):
    
    # operations inititated by charge point 
    async def send_boot_notification(self):
       request = call.BootNotificationPayload(
           charge_point_model = "Optimus Prime" , charge_point_vendor = "The Mobility 123" , charge_point_serial_number="1ABC"       
           )
       response = await self.call(request)
       
       if response.status == 'Accepted':
           print("Connected to central system.")

    async def send_heartbeart(self):
        """
        This contains the field definition of the Heartbeat.req PDU sent by
        the Charge Point to the Central System. See also Heartbeat
        No fields are defined.
        """
        request = call.HeartbeatPayload()
        response = await self.call(request)
        print(response.current_time)
        print("-> heartbeat")

    async def send_start_transaction(self,tx_id,tx_val):
        request = call.StartTransactionPayload(
            connector_id=1,
            id_tag='1010010112345678',
            meter_start=tx_val,
            reservation_id=tx_id,
            timestamp=datetime.now().isoformat()
        )
        response = await self.call(request)
        if response.id_tag_info['status'] == RegistrationStatus.accepted:
            print("===================================")
            print("StartTransaction started. transaction_id: ", response.transaction_id)
            print("===================================")
        print ("-> ", response.transaction_id)
        
    async def send_stop_transaction(self,tx_id,tx_val):
        request = call.StopTransactionPayload(
            id_tag='1010010112345678',
            meter_stop=tx_val,
            timestamp=datetime.now().isoformat(),
            transaction_id=tx_id
        )
        response = await self.call(request)
        if response.id_tag_info['status'] == RegistrationStatus.accepted:
            print("===================================")
            print("StopTransaction started. transaction_id: ")
            print("===================================")
        
    @on(Action.ClearCache)
    def on_clear_cache(self, **kwargs):
        logging.info('========== Got a Clear Cache ==========')
        #status =  "Accepted" / "Rejected"
        return call_result.ClearCachePayload(
            status = "Accepted"
        )

async def main():
    async with websockets.connect(
        'ws://192.168.1.69:8080/steve/websocket/CentralSystemService/CP_1',
         subprotocols=['ocpp1.6']
    ) as ws:
        cp = ChargePoint('CP_1', ws)
        await asyncio.gather(cp.start(),cp.send_boot_notification())

if __name__ == '__main__':
    asyncio.run(main())

My question is after doing a boot notification, how do I do other transactions, such as send_start_transaction or send_heartbeart because it looks like the program has stopped after running the await command asyncio.gather(cp.start(),cp.send_boot_notification())

**Comment by gowthamreddythumu** [comment]
Change the line
asyncio.gather(cp.start(),cp.send_boot_notification())
with
await asyncio.gather(cp.start(), cp.send_boot_notification(), cp.send_heartbeart(), cp.send_start_transaction(), cp.send_stop_transaction(), cp.on_clear_cache() )
