### ISSUE TITLE
How to retrieve message_id from the payload I received from ChargePoint?

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [mobilityhouse/ocpp#400]
Is there any way to capture the message_id?

**Comment by OrangeTux** [comment]
Unfortunately, it can't be done in a nice way. 

You could override `ChargePoint._handle_call()`. This function receives an instance of `Call`. 

```python
class MyCharger(ChargePoint):
    async def _handle_call(self, msg: Call): 
        print(msg.unique_id)
        super()._handle_call(msg)
```

**Comment by ChaitanyaYeole02** [comment]
And what method should I use to send my ow unique id?
My guess is using CallResult

**Comment by OrangeTux** [comment]
Not via a public API. However, you can set  the 'private' [ChargePoint._unique_id_generator()](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/charge_point.py#L120-L123). This  attribute is a callable and used to generate unique id's. It's private, therefore might changed in the future.

**Comment by ChaitanyaYeole02** [comment]
@OrangeTux Can you share a snippet of the same?

**Comment by OrangeTux** [comment]
I'm not sure if I understand your question. But [here's a test](https://github.com/mobilityhouse/ocpp/blob/master/tests/v16/conftest.py#L26-L35) that sets a `ChargePoint._unique_id_generator()` to a custom value.
