### ISSUE TITLE
How to initiate call_error (messageid type =3) from CP.

### ISSUE THREAD

**Issue by Kshankarpy** [mobilityhouse/ocpp#403]
I reboot the the CP and the boot notification has been sent to the client(CS). The status for the response of boot notification request is Rejected. So the CP should rsponds with  the CALLERROR: SecurityError for every message request it recieved as the boot notifcation status is rejected. Here, in the pakage i can see call_result and call but  i could not able to figure it out any module to send call_error that satisfees RPC framework.

**Comment by OrangeTux** [comment]
With OCPP you can't send CallErrors with message type id of 3. CallErrors always carry type id 4.

You can raise an instance of [ `OCPPError`.](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/exceptions.py#L1) That's [automatically turned into a `CallError`.](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/charge_point.py#L197-L204)

**Comment by Kshankarpy** [comment]
Sorry, type id is 4 for call error . typo mistake. Thanks for the clarification. It means if we raise an exception from taking an instance from OCPPError from exception file for example i have to raise SecurityError

**Comment by OrangeTux** [comment]
No, `OCPPError` doesn't have an attribute 'SecurityError'. You need to raise `[ocpp.exceptions.SecurityErrror.](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/exceptions.py#L61-L68)`

**Comment by Kshankarpy** [comment]
Yes, Got it. Thanks for the Clarification.
