### ISSUE TITLE
How Trigger Message Works?

### ISSUE THREAD

**Issue by vagio** [mobilityhouse/ocpp#404]
Hello i have a question about how trigger message actually works. This is my code

Central System
``` 
async def send_trigger(cp):
    request=call.TriggerMessagePayload(
        requested_message='BootNotification'
    )
    await cp.call(request)
```
Charging Point
```
@on(Action.TriggerMessage)
    def on_trigger(self,**kwargs):
        return call_result.TriggerMessagePayload(
            status="Accepted")
```
i wonder if i have to add something else to trigger boot notification(or any other message) or it will be trigger from charging point automatically.

**Comment by Kshankarpy** [comment]
Trigger message is  the request message that has been sent from the CS to CP. The trigger message is  nothing but CS requesting the CP to initiate a request message i.e, BootNotification, metervalues e.t.c. CP can responds with accepted or rejected status  for the trigger message request.

**Comment by vagio** [comment]
> Trigger message is the request message that has been sent from the CS to CP. The trigger message is nothing but CS requesting the CP to initiate a request message i.e, BootNotification, metervalues e.t.c. CP can responds with accepted or rejected status for the trigger message request.

So if we test it on a real charging station, if it responds with acceptance, it will automatically send the requested message?

**Comment by OrangeTux** [comment]
Correct.

**Comment by vagio** [comment]
Thank you both for your replies.
