### ISSUE TITLE
[OCPP 2.0.1] ReservationStatusUpdate has no payload response and breaks the handler

### ISSUE THREAD

**Issue by TheHardGamer** [mobilityhouse/ocpp#408]
Greetings, I am working on a 2.0.1 server and whenever ReservationStatusUpdate is received from charge point, it causes the websocket connection to break because of the handler.

Error:

```
 INFO:ocpp:: receive message [2,"b7311abf-b106-44ce-af09-5f8014e206fd","ReservationStatusUpdate",{"reservationId":0,"reservationUpdateStatus":"Expired"}]
 ERROR:websockets.server:connection handler failed
 File "/home/.local/lib/python3.10/site-packages/ocpp/charge_point.py", line 208, in _handle_call
     temp_response_payload = asdict(response)
   File "/usr/lib/python3.10/dataclasses.py", line 1238, in asdict
     raise TypeError("asdict() should be called on dataclass instances")
 TypeError: asdict() should be called on dataclass instances
```

My handler code:
```
 @on('ReservationStatusUpdate')
 def on_reservation_status_update(self, **kwargs): 
    print("Received ReservationStatusUpdate")
```

I was able to reproduce this issue by creating a simple client script and sending the pre formed message to the server.

Steps to reproduce:
Take the minimal CSMS 2.0.1 example, add ReservationStatusUpdate handler
Send "[2,"b7311abf-b106-44ce-af09-5f8014e206fd","ReservationStatusUpdate",{"reservationId":0,"reservationUpdateStatus":"Expired"}]"  to it.

PS: My bad, i selected the question template by mistake for the issue.

**Comment by OrangeTux** [comment]
Which version of the library are you using?

**Comment by TheHardGamer** [comment]
> I think the error is that you're handler is not returning a response. Make sure to return a `call_result.ReservationStatusUpdatePayload` instance.

Oh ok, since the ocpp documentation stated that no fields are defined for reservation status update response, i didn't bother checking the library code, its working perfectly fine now, thank you!
