### ISSUE TITLE
Heartbeat and StartRemoteTransaction in one connection

### ISSUE THREAD

**Issue by stig888881** [mobilityhouse/ocpp#409]
Greetings. Can anyone share an example of how you can receive requests from a station to the server and send requests from the server to the station in one connection?

**Comment by damnhalfling** [comment]
I have a lot of difficulty about that too, I'm implement this on FASTAPI, that have some more complications.
But my solution is to use the after hook on heartbeat notification to call another class, split the code of messages in 2 one for CP->CS and other for CS->CP

@on(Action.Heartbeat)
    def on_Heartbeat(
        self, **kwargs
    ):
        print("-------------------")
        print("HEARTBEAT")
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().isoformat(),
        )
        print("-------------------")

    @after(Action.Heartbeat)
    async def after_boot_notification(self):
        cs = ChargeServer()
        await cs.main(self)
        
  On my cs.main, i implemented a logic that works with mongo, to know witch message i have to call, based on others request. from my front-end
  
  
I have a problem of flood my CP, and take time out. Sou have overhide the method start from ocpp.v16 ChargePoint, add a sleep, its not a beatifull solution, but it works, by now. I look to make better in future:


async def start(self):
        while True:
            message = await self._connection.recv()
            LOGGER.info("%s: receive message %s", self.id, message)
            await self.route_message(message)
            time.sleep(5)

**Comment by stig888881** [comment]
> I have a lot of difficulty about that too, I'm implement this on FASTAPI, that have some more complications. But my solution is to use the after hook on heartbeat notification to call another class, split the code of messages in 2 one for CP->CS and other for CS->CP
> 
> @on(Action.Heartbeat) def on_Heartbeat( self, **kwargs ): print("-------------------") print("HEARTBEAT") return call_result.HeartbeatPayload( current_time=datetime.utcnow().isoformat(), ) print("-------------------")
> 
> ```
> @after(Action.Heartbeat)
> async def after_boot_notification(self):
>     cs = ChargeServer()
>     await cs.main(self)
> ```
> 
> On my cs.main, i implemented a logic that works with mongo, to know witch message i have to call, based on others request. from my front-end
> 
> I have a problem of flood my CP, and take time out. Sou have overhide the method start from ocpp.v16 ChargePoint, add a sleep, its not a beatifull solution, but it works, by now. I look to make better in future:
> 
> async def start(self): while True: message = await self._connection.recv() LOGGER.info("%s: receive message %s", self.id, message) await self.route_message(message) time.sleep(5)

I have come up with what I think is a more reasonable solution. Among other things, it includes the presence of a graphical interface and working with the database. You should pay attention https://github.com/stig888881/CMS_server/tree/master/CMS_server%20version%200.1

**Comment by stig888881** [comment]
> I have a lot of difficulty about that too, I'm implement this on FASTAPI, that have some more complications. But my solution is to use the after hook on heartbeat notification to call another class, split the code of messages in 2 one for CP->CS and other for CS->CP
> 
> @on(Action.Heartbeat) def on_Heartbeat( self, **kwargs ): print("-------------------") print("HEARTBEAT") return call_result.HeartbeatPayload( current_time=datetime.utcnow().isoformat(), ) print("-------------------")
> 
> ```
> @after(Action.Heartbeat)
> async def after_boot_notification(self):
>     cs = ChargeServer()
>     await cs.main(self)
> ```
> 
> On my cs.main, i implemented a logic that works with mongo, to know witch message i have to call, based on others request. from my front-end
> 
> I have a problem of flood my CP, and take time out. Sou have overhide the method start from ocpp.v16 ChargePoint, add a sleep, its not a beatifull solution, but it works, by now. I look to make better in future:
> 
> async def start(self): while True: message = await self._connection.recv() LOGGER.info("%s: receive message %s", self.id, message) await self.route_message(message) time.sleep(5)

Pay special attention to this part
`async def on_connect(websocket, path):
    """For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers["Sec-WebSocket-Protocol"]
    except KeyError:
        logging.error("Client hasn't requested any Subprotocol. Closing Connection")
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning(
            "Protocols Mismatched | Expected Subprotocols: %s,"
            " but client supports  %s | Closing connection",
            websocket.available_subprotocols,
            requested_protocols,
        )
        return await websocket.close()

    charge_point_id = path.strip("/")
    cp = ChargePoint(charge_point_id, websocket)
    print(charge_point_id)
    print(websocket.remote_address[0])

    async def remotestart():
        global h,N
        while True:
            if h==1:
                if cp.id==N:
                    await cp.remote_start_transaction()
                    h=0
                else:
                    await asyncio.sleep(0.1)
            else:
                await asyncio.sleep(0.1)
    try:
        await asyncio.gather(cp.start(),remotestart())
    except websockets.exceptions.ConnectionClosedError:
        for row in range(window.tableWidget.rowCount()):
            if charge_point_id == window.tableWidget.item(row,0).text():
                window.tableWidget.setItem(row, 3, QTableWidgetItem("Отключен"))
                window.tableWidget.setItem(row, 5, QTableWidgetItem(""))
                break`

**Comment by stig888881** [comment]
> I have a lot of difficulty about that too, I'm implement this on FASTAPI, that have some more complications. But my solution is to use the after hook on heartbeat notification to call another class, split the code of messages in 2 one for CP->CS and other for CS->CP
> 
> @on(Action.Heartbeat) def on_Heartbeat( self, **kwargs ): print("-------------------") print("HEARTBEAT") return call_result.HeartbeatPayload( current_time=datetime.utcnow().isoformat(), ) print("-------------------")
> 
> ```
> @after(Action.Heartbeat)
> async def after_boot_notification(self):
>     cs = ChargeServer()
>     await cs.main(self)
> ```
> 
> On my cs.main, i implemented a logic that works with mongo, to know witch message i have to call, based on others request. from my front-end
> 
> I have a problem of flood my CP, and take time out. Sou have overhide the method start from ocpp.v16 ChargePoint, add a sleep, its not a beatifull solution, but it works, by now. I look to make better in future:
> 
> async def start(self): while True: message = await self._connection.recv() LOGGER.info("%s: receive message %s", self.id, message) await self.route_message(message) time.sleep(5)

Pay special attention to this part
```
async def on_connect(websocket, path):
    """For every new charge point that connects, create a ChargePoint
    instance and start listening for messages.
    """
    try:
        requested_protocols = websocket.request_headers["Sec-WebSocket-Protocol"]
    except KeyError:
        logging.error("Client hasn't requested any Subprotocol. Closing Connection")
        return await websocket.close()
    if websocket.subprotocol:
        logging.info("Protocols Matched: %s", websocket.subprotocol)
    else:
        # In the websockets lib if no subprotocols are supported by the
        # client and the server, it proceeds without a subprotocol,
        # so we have to manually close the connection.
        logging.warning(
            "Protocols Mismatched | Expected Subprotocols: %s,"
            " but client supports  %s | Closing connection",
            websocket.available_subprotocols,
            requested_protocols,
        )
        return await websocket.close()

    charge_point_id = path.strip("/")
    cp = ChargePoint(charge_point_id, websocket)
    print(charge_point_id)
    print(websocket.remote_address[0])

    async def remotestart():
        global h,N
        while True:
            if h==1:
                if cp.id==N:
                    await cp.remote_start_transaction()
                    h=0
                else:
                    await asyncio.sleep(0.1)
            else:
                await asyncio.sleep(0.1)
    try:
        await asyncio.gather(cp.start(),remotestart())
    except websockets.exceptions.ConnectionClosedError:
        for row in range(window.tableWidget.rowCount()):
            if charge_point_id == window.tableWidget.item(row,0).text():
                window.tableWidget.setItem(row, 3, QTableWidgetItem("Отключен"))
                window.tableWidget.setItem(row, 5, QTableWidgetItem(""))
                break
```
