### ISSUE TITLE
ocpp compliancy

### ISSUE THREAD

**Issue by kramzarales** [mobilityhouse/ocpp#410]
Hello,

I am implementing this library on a charging station we are making. I have never worked with ocpp before and i want to know, if you want to be officialy OCPP compliant, do you need to have EVERY OCPP response/request implemented or is it enough to just have the commands that the station will use actualy be able to use?

For example, do you need to implement the UpdateFirmwareRequest.json/UpdateFirmwareResponse.json  if your station for exaple didnt support this feature?

**Comment by OrangeTux** [comment]
What do you mean with "officially OCPP compliant"? I assume you refer the [OCPP 1.6](https://www.openchargealliance.org/certification/ocpp-16-certification/) and [OCPP 2.0.1](https://www.openchargealliance.org/certification/ocpp-201-certification/) certification programs of the Open Charge Alliance (OCA).

To get compliant, you've to implement their requirements. This library doesn't handle any OCPP message itself. You've to provide an implementation for all messages.

**Comment by kramzarales** [comment]
Yes, this is what i am refering to. Specificly the 2.0.1 certification.
I am awere that this library only provides the format structure for comunication and doesnt actualy have any softwere control on its own. 
But my question was, if it is required to have a response for all the possible requests that a central system could send. 
And also if that is the case, Is it enough to just send back an emptie response that doesnt actualy do anything on the charging system?

**Comment by Lobo-57** [comment]
> Yes, this is what i am refering to. Specificly the 2.0.1 certification. I am awere that this library only provides the format structure for comunication and doesnt actualy have any softwere control on its own. But my question was, if it is required to have a response for all the possible requests that a central system could send. And also if that is the case, Is it enough to just send back an emptie response that doesnt actualy do anything on the charging system?

https://www.openchargealliance.org/certification/ocpp-16-certification/
In this link you can see the specifications for the devices you may build and certify. There is more detailed information in the documentation, they explain what are the messages that you are obligated to implement for each device and for each kind of certification. Good luck!

**Comment by Jared-Newell-Mobility** [comment]
The OCA certification path specifically for 2.0.1 is at - https://www.openchargealliance.org/certification/ocpp-201-certification/
