### ISSUE TITLE
Demonstration on sending ChangeConfiguration request from OCPP to charger?

### ISSUE THREAD

**Issue by carlbenjaminlyon** [mobilityhouse/ocpp#411]
Message received by OCPP is formatted as such:
`{"id": "1234567890","msg_type": "ChangeConfiguration", "HeartbeatInterval": "30"}`

What I would like to know, is what the expected form of the output being sent to the charger? If I'm reading the OpenCharge Alliance docs under `2.2.1 ChangeConfiguration Message`, the outgoing object should appear as such:
`{"configurationKey":[{"key": "HeartbeatInterval", "value": "30"}]}`.
I think I'm just confused on the expected form of the json object/dict/list that is being sent to the charger from the OCPP server.

**Comment by OrangeTux** [comment]
In OCPP 1.6, configuration keys are send individually. Here's a request I pulled from from my application logs:

```python
[2,
 '3be500c7-61c8-41b5-afac-85a025353251',
 'ChangeConfiguration',
 {'key': 'MeterValuesSampledData',
  'value': 'Power.Active.Import,Current.Offered,Energy.Active.Import.Register,Current.Import.L1,Current.Import.L2,Current.Import.L3,Power.Offered'}]
```

**Comment by carlbenjaminlyon** [comment]
Thank you! This helps a lot. I was able to get the ChangeConfiguration command working a few days ago, and getting response messages from the charger. My question was geared more toward the actual code for the OCPP call to the charger, of which I wasn't certain how to do (still new to Python). 
`
keyValue = "%s" % key
vValue = "%s" % args[key]
msg = call.ChangeConfigurationPayload(
   key = keyValue,
   value = vValue
)
`
I need to work on my variable naming conventions. The next step is to have a response message with the charger serial id, and the status of the response message so I can ingest them into my restful api.

**Comment by Jared-Newell-Mobility** [comment]
As this looks to be resolved, I'll close this issue for now.
