### ISSUE TITLE
Wrong dataclass AuthorizationData (v1.6)

### ISSUE THREAD

**Issue by tzzdvd** [mobilityhouse/ocpp#412]
Based on the documentation on section "7.1. AuthorizationData", this class has the idTagInfo field Optional

In file ocpp.v16.datatypes.py, the field is actually optional but the default is missing

current version (0.16.0)
``` python
@dataclass
class AuthorizationData:
    """
    Elements that constitute an entry of a Local Authorization List update.
    """

    id_tag: str
    id_tag_info: Optional[IdTagInfo]
```
In my opinion, it should be
``` python
@dataclass
class AuthorizationData:
    """
    Elements that constitute an entry of a Local Authorization List update.
    """

    id_tag: str
    id_tag_info: Optional[IdTagInfo] = None
```

Without that correction, the following code crashes

``` python
k = {"id_tag": "1234"}
k_dataclass = AuthorizationData(**k)
```
with 
``` python
TypeError: AuthorizationData.__init__() missing 1 required positional argument: 'id_tag_info'
```
In the meantime, the only fix I have found at application level is 
``` python
k = {"id_tag": "1234"}
if "id_tag_info" not in k:
    k["id_tag_info"] = None
k_dataclass = AuthorizationData(**k)
```
an no crashes occurs.

Best regards
Davide

**Comment by zapoig** [comment]
I concur, this makes the removal of a badge in the local auth list by an incremental update impossible : it needs the id_tag_info not to be present.
