### ISSUE TITLE
Modify response to GetConfiguration and ChangeConfiguration to include charger serial

### ISSUE THREAD

**Issue by carlbenjaminlyon** [mobilityhouse/ocpp#414]
Hey all,
I'm working with a RESTful api, ingesting messages from the OCPP server. Each message is dependent on the {"id":"1234567"} charger serial value. Currently, the responses I'm getting from the charger from the 'ChangeConfiguration' message returns as the following: `ChangeConfigurationPayload(status='Accepted')`, which doesn't help me update the value. Does anyone have an idea of how to modify the following code to be able to add in the serial? Ideally, I'd like to have the message response in the following format:
`
{ id: '1234567', msg_type: 'ChangeConfigurationPayload', status: 'Accepted'}
`

The current relevant portions of code:
`
                msg = call.ChangeConfigurationPayload(
                  key = keyValue,
                  value = vValue
                )
`         
         
       `response = str(await self.call(payload=msg))
        logger.info("RESPONSE: %s", response)
        self.csms.sqs_client.send(response)

`
Really, I'd like to change the result of the 'ChangeConfiguration.conf' response message that is finally being sent back to the SQS queue to my api to include the charger serial value.

**Comment by OrangeTux** [comment]
The charger id is available at `ChargePoint.id`. See https://github.com/mobilityhouse/ocpp/blob/22b52387ea60558cc0398f668a00eed6d5f75286/ocpp/charge_point.py#L93-L99

Does that help?

**Comment by carlbenjaminlyon** [comment]
It does! I might have brained out in the process of writing the original post, and I figured it out before your comment, but thank you still!
