### ISSUE TITLE
FormatViolation Error

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [mobilityhouse/ocpp#415]
@OrangeTux 
I am receiving FormatViolationError continuously on my OCPP Server. As one of the CP's is sending incorrect Json Payload. How can I change it into an exception and log it into warning? So that my log file does not fill up.

**Comment by ChaitanyaYeole02** [comment]
@OrangeTux 

A CP is sending me this raw message and I am receiving FormatViolationError while it is trying to unpack the raw message. How can I convert this error log into a Warning?

`[2,"213","StartTransaction",{"connectorId":2,"idTag":"336699\\\\\\","meterStart":33259490,"timestamp":"2022-07-28T09:41:15Z"}]`

ERROR
`FormatViolationError: Payload for Action is syntactically incorrect or structure for Action`

**Comment by Jared-Newell-Mobility** [comment]
To help understand why this is happening, could you please post the code you have written?
