### ISSUE TITLE
Get_Diagnostics Uploading Failed 

### ISSUE THREAD

**Issue by carving85** [mobilityhouse/ocpp#416]
When I try to download the diagnostics I get the status "Uploading Failed" all the time. I suspect this is my mistake. Do you have any sample code to download diagnostics

**Comment by Jared-Newell-Mobility** [comment]
That you are receiving a valid response from the Charge Point of UploadFailed - would indicate that your code is implemented correctly at least for this message type. See section OCPP 1.6 4.4. Diagnostics Status Notification. 

It can be assume that the GetDiagnostics.req in section 6.25. is not able to upload to the location specified in the message. To understand this in more detail I would suggest that the Charge Point logs should be consulted. As it could be any number of issues between from the Charge Point to the location that was specified, assuming the location is correct and available from the Charge Point.

**Comment by Jared-Newell-Mobility** [comment]
This issue looks to be no longer active, so closing for now.
