### ISSUE TITLE
Implementing RemoteStartStop without authorization

### ISSUE THREAD

**Issue by carlbenjaminlyon** [mobilityhouse/ocpp#417]
Hello,
I'm currently working on a 1.6 compliant EV charger that when in 'authorizedChargingOnly' mode, requires a card scan on the device to initiate a charge, or to set the charger into 'Preparing', where the user is then able to plug the charger into their vehicle and begin a charging session. In the 'authorizedChargingOnly' mode, I'm able to initiate a RemoteStartStop charging session successfully. I am able to set the charger into an unauthorized charging mode, where the user does not need to scan an authorization card to begin a charging session, and the charger immediately begins a new charging session.

However, when the device is in the unauthorized charging state, RemoteStart is bypassed. Is there a configuration  so the EV Charger does not begin a charging session upon being plugged in, and also does not require authorization from a card swipe or by a remote process? Apologies if this is poorly worded - if additional clarification is needed, I can provide.

Thanks!

**Comment by Jared-Newell-Mobility** [comment]
If I have understood correct: 

You could leave the charge point in authorizedChargingOnly - the user doesn't perform authorization at the Charge Point (assuming it is not possible e.g. no RFID card). 

A Remote Start Transaction (OCPP 1.6  Section 5.11.) can then be sent from the Central System to the Charge Point. 

Ensure the AuthorizeRemoteTxRequests configuration key in the Charge Point is set to False (Section 9.1.3. AuthorizeRemoteTxRequests). AllowOfflineTxForUnknownId should also be false. LocalPreAuthorize should also be false. For completeness LocalAuthorizeOffline should also be false. This can be done from the central system with section 5.3. Change Configuration if it is not available in the Charge Point configuration.

As stated section 6.33. a RemoteStartTransaction.req requires an IdToken (string) this can be set to something which the Central System will accept for all cases. That is with the implementation of confirming the IdToken on the Central System the only check that is done is that the IdToken sent in the RemoteStartTransaction matches the IdToken stored in the Central System.

I hope this helps

**Comment by Jared-Newell-Mobility** [comment]
This issue looks to be no longer active, closing for now.
