### ISSUE TITLE
Change Availability

### ISSUE THREAD

**Issue by betovaca** [mobilityhouse/ocpp#418]
Hi,

I'm trying to implement OCPP 2.0.1 and in the specifications Part 2, figure 74, there's the possibility to wait for transaction on EVSE to finish. 

I have a variable in my server named "charging_state"
and my code for the ChangeAvailabilityRequest is:
```
while(charging_state != "Idle"):
    pass

```
But it doesn't seems to wait for the transaction to end, is there a way to wait for the transaction effectively? 

Thanks in advance

**Comment by Jared-Newell-Mobility** [comment]
In referring to Figure 74. Sequence Diagram: Status Notification - This use case covers the functionality that a Charging Station sends a notification to the CSMS to inform the CSMS about a Connector status change. The events which trigger this message is when the connection status becomes Available, Occupied, Reserved, Unavailable, Faulted.

However, the above message type does not equal to an transaction.

When you can be sure that a transaction is completed a TransactionEvent (see Section 1.60.) will contain the event type called **Ended**. I would expect you would want to look for this message on the CSMS, originating from the Charge Point.

I hope this helps

**Comment by Jared-Newell-Mobility** [comment]
This issue appears to no longer be active, so closing for now.
