### ISSUE TITLE
Can remote start/stop be enabled without the charger automatically charging upon being plugged in?

### ISSUE THREAD

**Issue by carlbenjaminlyon** [mobilityhouse/ocpp#422]
Title. 
I'm setting up remote start/stop to allow for a user to plug in their EV, and then begin/end a charging session remotely via the RemoteStartTransaction/RemoteStopTransaction commands. Currently, the charger, when in unauthenticated mode, will begin charging as soon as it is plugged in. Is there a way to allow a user to plug in their EV, and have the charge point not initiate a charging session until receiving the RemoteStartTransaction command?

**Comment by Jared-Newell-Mobility** [comment]
It appears as the Charge Point is configured with the user case  -  E02 - Start Transaction - Cable Plugin First (see OCPP 2.0.1 Part 2 Specification, section 2.1. OCPP transaction mechanism).

This behaviour on the Charge Point can be changed from the CSMS with a SetVariables (section 1.57.) message that modifies the 2.6.4. TxStartPoint - component name TxCtrlr, variable name TxStartPoint and value Authorized.

(see  section 1.1. Flexible transaction start/stop)

I would say at present the charge point is configured with the TxStartPoint as EVConnected - you could confirm this assumption from the CSMS with a  GetVariablesRequest (see section 1.28.1.)

I hope this helps

**Comment by Jared-Newell-Mobility** [comment]
This issue appears to be stale, so closing for now
