### ISSUE TITLE
Components and Controllers

### ISSUE THREAD

**Issue by betovaca** [mobilityhouse/ocpp#423]
Hi, I have implemented all the Controller components and Physical components to the OCPP Client (the charging station) but I'm not sure if I have to implement the same controller components to the server?
If so, the Server needs to have a Controller Components for every Charging Station that connects to it or it only need to have one Controller Component for all the clients? 

Thanks in advance

**Comment by Jared-Newell-Mobility** [comment]
Assuming OCPP 2.0.1 and sections 1. Controller Components, 2. Referenced Components and Variables 

These are to be implemented on the charge point (OCPP client). For more details why and how - see section 4. Device Model: Addressing Components and Variables in OCPP 2.0.1 Part 1 - Architecture and Topology.

For the CSMS (Charging Station Management System) or Server - the message types SetVariables or GetVariables can be used to write or read respectively, the specific component and variable is defined in the message and a response is received from the charge point. Note: variables can be ReadOnly, WriteOnly or ReadWrite.

I hope this helps

**Comment by Jared-Newell-Mobility** [comment]
This issue appears to be no longer active so closing for now
