### ISSUE TITLE
Fix validation of payloads containing floats

### ISSUE THREAD

**Issue by pagetable** [mobilityhouse/ocpp#43]
What are the todo and special actions in validate_payload() supposed to be? Are they to deal with the 'multipleof' problem of jsonschema check?

https://github.com/mobilityhouse/ocpp/blob/75dd91fb80f34c401365061e90db9907a9faac33/ocpp/messages.py#L118-L124

Besides, I am not sure if it is proper to ask this question here, if not, please feel free to delete this issue.

Thank you.

**Comment by OrangeTux** [comment]
Hello @pagetable 

Nice catch! Here is a comment I found in our internal code base related to this issue:

``` python
# These 3 schedules have fields of type floats. The JSON schema defines
# a certain precision for these fields of 1 decimal. A value of 21.4 is
# valid, whereas a value if 4.11 is not.
#
# The problem is that Python's internal representation of 21.4 might
# have more than 1 decimal. It might be 21.399999999999995. This would
# make the validation fail, although the payload is correct. This is a
# known issue with jsonschemas, see:
# https://github.com/Julian/jsonschema/issues/247
#
# This issue can be fixed by using a different parser for floats than
# the default one that is used.
#
# Both the schema and the payload must be parsed using the different
# parser for floats.
```

I will implement it soon.
