### ISSUE TITLE
Attributes with 'v2x' are serialized as 'V2x', but should be serialized as 'V2X'.

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#431]
https://github.com/mobilityhouse/ocpp/blob/db25fbd6c693e83f280660e58c683228ae794e0a/ocpp/v201/extensions/v2x/datatypes.py#L85-L86

Serializing objects with attributes that have 'v2x' in the name, are not serialized correctly. E.g. `V2XChargeParametersType.ev_max_v2x_energy_request` is serialized as "evMaxV2xEnergyRequest", but it should be "evMinV2**X**EnergyRequest". This problem happens also to other objects.

**Comment by Jared-Newell-Mobility** [comment]
Currently:

`@dataclass
class Bidirectional:
    ev_min_v2x_energy_request: Optional[str] = None


def test_serialise():

    expected = {'evMinV2XEnergyRequest': None}

    assert snake_to_camel_case(asdict(Bidirectional())) == expected`

{'evMinV2xEnergyRequest': None} != {'evMinV2XEnergyRequest': None)

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/522 is prepared for inclusion in v1.0.0
