### ISSUE TITLE
Typo in CostUpdated Action

### ISSUE THREAD

**Issue by nodge261** [mobilityhouse/ocpp#435]
In ocpp/v201/enums.py Action class the entry for CostUpdated is "CostUpdate" (missing "d").

**Comment by dinko-pehar** [comment]
https://github.com/mobilityhouse/ocpp/blob/e6ed033830050e9fd95b500737ff8cb6db469162/ocpp/v201/enums.py#L17

**Comment by Jared-Newell-Mobility** [comment]
Thank-you for picking this up - yes this should be CostUpdated - I'll change this to a bug

**Comment by Jared-Newell-Mobility** [comment]
https://github.com/mobilityhouse/ocpp/pull/491 - will be merged with the next major release

**Comment by Jared-Newell-Mobility** [comment]
Closed now referenced in https://github.com/mobilityhouse/ocpp/issues/174
