### ISSUE TITLE
A simple python CP example considering one charging cycle locally

### ISSUE THREAD

**Issue by dipankarkhartad** [mobilityhouse/ocpp#437]
Hello Team,

Thank you very much team for the library designed in Python. 

Can you share a simple example considering one complete charging cycle? That will be easier to visualize the flow. 

1. Boot Notification
2. Heartbeat
3. Authorize
4. StartTransaction
5. Metervalues
6. StopTransaction

**Comment by r3econ** [comment]
@dipankarkhartad Hello, I'm looking for a similar example. Were you able to get it running?

**Comment by AlanCluet** [comment]
Hi, im looking for an example of the part 3 and 5 also and couldn't find anything.

**Comment by larrykluger** [comment]
https://github.com/victormunoz/OCPP-1.6-Chargebox-Simulator may be of help.

**Comment by Jared-Newell-Mobility** [comment]
As there is an existing issue regarding improving documentation in https://github.com/mobilityhouse/ocpp/issues/55 - so I will close this issue for now
