### ISSUE TITLE
issues in call method for FirmwareStatusNotification Payload

### ISSUE THREAD

**Issue by deepakEnercent** [mobilityhouse/ocpp#439]
As per my understanding the method call is used when we send some command to charger and call_result is for getting the response from the charger.

As per OCPP1.6J document for the FirmwareStatusNotification payload call_result would return the status of the firmware being updated on the charger which should be FirmwareStatus given to the server i.e. CMS

But as per the OCPP library call_result is not taking any parameter and and call wants an FirmwareStatus argument.

Is my understanding correct .?? if wrong pls someone figure out to me where iam getting wrong.

Need help.

<img width="1280" alt="Screenshot 2023-04-19 at 7 30 38 AM" src="https://user-images.githubusercontent.com/86566162/232947329-283b5450-173c-44f3-897d-5e1ef5ced14c.png">

**Comment by tropxy** [comment]
Hi,

I am not sure from which side you are working (CSMS or CS), but if you are the CS, then you need to create a call for the FirmwareStatusNotification:

```python
async def send_fw_status(self):
    request = call.FirmwareStatusNotification(status=FirmwareStatus.downloading)
    await self.call(request)
```
Note that the response of is has no payload, according to the standard, so there is no point on trying to get the payload from the call like `response = await self.call(request)`


if you are the CSMS, then you need to handle the CALL request:

```python
class ChargePoint(cp):
    @on(Action.FirmwareStatusNotification)
    def on_fw_status(
        self, status: FirmwareStatus
    ):
        logger.info(f"Station is {status}")
        return call_result.FirmwareStatusPayload()
```

As you see on the station side, we process the status provided by the call by just logging its value, and then we return the FirmwareStatusPayload which accepts no argument.

I hope this makes it clear for you.
