### ISSUE TITLE
Cannot send MeterValuePayload

### ISSUE THREAD

**Issue by Hillerr** [mobilityhouse/ocpp#44]
When I try to send some EVSE meter values to the central system it says that cannot parse with JSON schema. Can somebody write a simple example how I should send meter_values parameter from MeterValuePayload data class.

**Comment by proelke** [comment]
Without seeing your code or the exceptions, if you are getting schema validation errors then your payload must not conform to the standard. Are these meter values coming from a charge point, or some test code?

The meter_values can be a little tricky. If you look at the [schema](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v16/schemas/MeterValues.json) and/or the [documentation](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-1.6.pdf), maybe you can find where in the code you are getting hung up.

**Comment by Hillerr** [comment]
Proelke, 
This is the function that I'm using to send MeterValues payload:
`async def send_meter_values(cp, connector_id, meter_value, transaction_id):
    request = call.MeterValuesPayload(connector_id, meter_value, transaction_id)
    response = await cp.call(request)
    print('Meter Values resposne: ', response.__dict__)`

When call this function from EVSE main task I just send this parameters:
`await send_meter_values(cp, 1, meter_value=['value: 200', 'measurand: Voltage'], transaction_id=1)`

And then this happens:
`ocpp.exceptions.ValidationError: Payload '{'connectorId': 1, 'meterValue': ['value: 200', 'measurand: Voltage'], 'transactionId': 1} for action
'MeterValues' is not valid: 'value: 200' is not of type 'object'

Failed validating 'type' in schema['properties']['meterValue']['items']:
    {'properties': {'sampledValue': {'items': {'properties': {'context': {'enum': ['Interruption.Begin',
                                                                                   'Interruption.End',
                                                                                   'Sample.Clock',
                                                                                   'Sample.Periodic',
                                                                                   'Transaction.Begin',
                                                                                   'Transaction.End',
                                                                                   'Trigger',
                                                                                   'Other'],
                                                                          'type': 'string'},
                                                              'format': {'enum': ['Raw',
                                                                                  'SignedData'],
                                                                         'type': 'string'},
                                                              'location': {'enum': ['Cable',
                                                                                    'EV',
                                                                                    'Inlet',
                                                                                    'Outlet',
                                                                                    'Body'],
                                                                           'type': 'string'},
                                                              'measurand': {'enum': ['Energy.Active.Export.Register',
                                                                                     'Energy.Active.Import.Register',
                                                                                     'Energy.Reactive.Export.Register',
                                                                                     'Energy.Reactive.Import.Register',
                                                                                     'Energy.Active.Export.Interval',
                                                                                     'Energy.Active.Import.Interval',
                                                                                     'Energy.Reactive.Export.Interval',
                                                                                     'Energy.Reactive.Import.Interval',
                                                                                     'Power.Active.Export',
                                                                                     'Power.Active.Import',
                                                                                     'Power.Offered',
                                                                                     'Power.Reactive.Export',
                                                                                     'Power.Reactive.Import',
                                                                                     'Power.Factor',
                                                                                     'Current.Import',
                                                                                     'Current.Export',
                                                                                     'Current.Offered',
                                                                                     'Voltage',
                                                                                     'Frequency',
                                                                                     'Temperature',
                                                                                     'SoC',
                                                                                     'RPM'],
                                                                            'type': 'string'},
                                                              'phase': {'enum': ['L1',
                                                                                 'L2',
                                                                                 'L3',
                                                                                 'N',
                                                                                 'L1-N',
                                                                                 'L2-N',
                                                                                 'L3-N',
                                                                                 'L1-L2',
                                                                                 'L2-L3',
                                                                                 'L3-L1'],
                                                                        'type': 'string'},
                                                              'unit': {'enum': ['Wh',
                                                                                'kWh',
                                                                                'varh',
                                                                                'kvarh',
                                                                                'W',
                                                                                'kW',
                                                                                'VA',
                                                                                'kVA',
                                                                                'var',
                                                                                'kvar',
                                                                                'A',
                                                                                'V',
                                                                                'K',
                                                                                'Celcius',
                                                                                'Fahrenheit',
                                                                                'Percent'],
                                                                       'type': 'string'},
                                                              'value': {'type': 'string'}},
                                               'required': ['value'],
                                               'type': 'object'},
                                     'type': 'array'},
                    'timestamp': {'format': 'date-time', 'type': 'string'}},
     'required': ['timestamp', 'sampledValue'],
     'type': 'object'}

On instance['meterValue'][0]:
    'value: 200'`

I have tried many ways to send a simple voltage sample. Obviously is the way that I'm passing the `meter_value` list.

**Comment by proelke** [comment]
meter_value should be a list of dicts. The dict should contain at least two keys timestamp and sampledValue. timestamp is pretty clear. sampledValue is another list of dicts. These dicts contain keys such as value, location, context, measurand, phase, etc. So as an example:

`[{'timestamp': '2019-11-12 15:56:57.887102', 'sampledValue': [{'value': 200, 'measurand': 'Voltage'}]}]`

**Comment by Hillerr** [comment]
It worked perfectly now. Thank you so much for your time and support, proelke.

Best regards.

**Comment by proelke** [comment]
No problem. The meter values can be a little trick because of the nesting.
