### ISSUE TITLE
How to send multiple keys in ChangeConfiguration payload?

### ISSUE THREAD

**Issue by ChaitanyaYeole02** [mobilityhouse/ocpp#441]
@OrangeTux 
This is given in OCPP1.6 Documentation
```
If a key value is defined as a CSL, it MAY be accompanied with a [KeyName]MaxLength key, indicating the max
length of the CSL in items. If this key is not set, a safe value of 1 (one) item SHOULD be assumed.
```

**Comment by AditSoni** [comment]
call.ChangeConfigurationPayload(key=key, value=value)
Here it accepts only 1 key at a time so you have to update your calling function to take multiple key:value pairs and do it via a for loop.

**Comment by OrangeTux** [comment]
The ChangeConfiguration request in OCPP 1.6 only allows to configure 1 key per request. 

The quote @ChaitanyaYeole02 is mentioning refers to configuration _values_ that are comma separated lists. For example the the key "MeterValueSampledData" is a comma seperated list of all measurands a MeterValue request must include. 

The number of items in that comma separated list is defined by the value of MeterValueSampledDataMaxLength key. This value defaults to 1.
