### ISSUE TITLE
Requested message not triggered

### ISSUE THREAD

**Issue by arturoInt** [mobilityhouse/ocpp#442]
I'm testing the TriggerMessage from the Central System to the Charge Point. But the Charge Point doesn't send the requested message.

Central system:
``` python
async def trigger_message(self):
        request = call.TriggerMessagePayload(
            requested_message = MessageTrigger.bootNotification,
        )
        response = await self.call(request)
        if response.status == TriggerMessageStatus.accepted:
            print("Request accepted!!!")
```

Charge Point:
``` python
@on(Action.TriggerMessage)
    async def on_trigger_message(self, **kwargs):
        return call_result.TriggerMessagePayload(
            status = TriggerMessageStatus.accepted
        )
```

Log:
```
INFO:ocpp:Test_CP1: receive message [2,"5494e4e1-0c7c-4403-aa99-600285076498","TriggerMessage",{"requestedMessage":"BootNotification"}]
INFO:ocpp:Test_CP1: send [3,"5494e4e1-0c7c-4403-aa99-600285076498",{"status":"Accepted"}]
```

The Charge Point receives the request but never sends the BootNotification message.

Is there something else I need to do to allow the Charge Point to send the  requested message?

Thank you.

**Comment by OrangeTux** [comment]
Your implementation only returns a response, but doesn't do anything else. You've to implement all logic yourself.
[`@after` ](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/routing.py#L59-L83)might be use full here.
