### ISSUE TITLE
Python 3.11 changes behavior how enums are formatted as string

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#447]
@proelke made me aware about a changes to Python 3.11 that introduce [subtle changes to all enums](https://docs.python.org/3/whatsnew/3.11.html#enum) that subclass from both `str` and `enum.Enum`. Practically all enums defined in this library are subclassed from these 2 classes.

Consider the following code:

```python
import enum

class ResetType(str, enum.Enum):
    hard = "hard"
    soft = "soft"

# Passes in both Python 3.11 and earlier.
assert ResetType.hard == "hard"

# Passes in Python 3.10 and below, but fails in Python 3.11.
assert f'{ResetType.hard}' == "hard"
```

```
$  python3.11 /enum_test.py
Traceback (most recent call last):
  File "/tmp/enum_test.py", line 15, in <module>
    assert f'{ResetType.hard}' == "hard"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

The underlying cause is that Python 3.11 changes the behavior of `enum.Enum.__format__()`  slightly. `f-strings` (and a few other string formatting methods) rely on dunder method `__format___()`.

So far, I considered two solutions. 

## Solution 1: StrEnum 
Python 3.11 introduces [`enum.StrEnum`](https://docs.python.org/3/library/enum.html#enum.StrEnum). One could implement a solution as described at https://tomwojcik.com/posts/2023-01-02/python-311-str-enum-breaking-change

```python
try:
    # breaking change introduced in python 3.11
    from enum import StrEnum
except ImportError:  # pragma: no cover
    from enum import Enum  # pragma: no cover

    class StrEnum(str, Enum):  # pragma: no cover
        pass  # pragma: no cover

class ResetType(StrEnum):
    hard = "hard"
    soft = "soft"

# Passes in both Python 3.11 and earlier.
assert ResetType.hard == "hard"

# Passes now in Python 3.10 and below and Python 3.11!
assert f'{ResetType.hard}' == "hard"
```

## Manually implement `__format__()`
 
The other solution is to implement `__format__()` manually. 
```python
import enum

class _Enum(str, enum.Enum):
    def __format__(self, spec) -> str:
        return str.__format__(str(self.name), spec)

class ResetType(_Enum):
    hard = "hard"
    soft = "soft"

# Passes in both Python 3.11 and earlier.
assert ResetType.hard == "hard"

# Passes now in Python 3.10 and below and Python 3.11!
assert f"{ResetType.hard}" == "hard"
```

See also
* https://blog.pecar.me/python-enum
* https://www.reddit.com/r/Python/comments/zt4ot4/enum_with_str_or_int_mixin_breaking_change_in/

**Comment by larrykluger** [comment]
A regression error introduced in a .01 update! Good grief.

**Comment by Jared-Newell-Mobility** [comment]
@OrangeTux - Another option may be this?

```
import enum

def test_this():

    class ResetType(str, enum.auto):
        hard = "hard"
        soft = "soft"

    print(ResetType.hard == "hard")
    print(f'{type(ResetType.hard)}')

    # Passes in Python 3.10 and Python 3.11.
    assert f'{ResetType.hard}' == "hard"


```
===================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/jared/PycharmProjects/test_project/tests
collected 1 item                                                                                                                                                                                                               

test_enum.py .                                                                                                                                                                                                           [100%]

====================================================================================================== 1 passed in 0.00s =======================================================================================================

===================================================================================================== test session starts ======================================================================================================
platform linux -- Python 3.11.5, pytest-7.4.3, pluggy-1.3.0
rootdir: /home/jared/PycharmProjects/test_project
collected 1 item                                                                                                                                                                                                               

tests/test_enum.py .                                                                                                                                                                                                     [100%]

====================================================================================================== 1 passed in 0.00s =======================================================================================================

**Comment by Jared-Newell-Mobility** [comment]
Related ticket has this same behaviour, see comments in https://github.com/mobilityhouse/ocpp/issues/433

**Comment by OrangeTux** [comment]
That's a clever solution. I didn't knew of this `enum.auto` and it's behavior. But I'm afraid that doesn't work for 2 reason:

* my demo code contains a bug. The members string should be capitalized, so "Hard" instead of "hard"
* a lot of enums in this project consists of multiple terms, e.g. `FirmwareStatus.download_failed` which should match the string "DownloadFailed". `enum.auto` does't work in this case.

**Comment by OrangeTux** [comment]
I suggest that we pick Solution #1.
