### ISSUE TITLE
Add support for OCPP 2.1

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#448]
The Open Charge Alliance released a draft version of OCPP 2.1 to it's members. 
And this library aims to implement support for this version.

**Comment by OrangeTux** [comment]
Work is tracked in branch https://github.com/mobilityhouse/ocpp/tree/448-ocpp-21

**Comment by gitkh2891** [comment]
Hi, does the library intelligently handle chargepoints with different versions of OCPP eg. 1.6 vs 2.x when the establishing websocket connections? Or do we need to manually hardcode and check the response body of the "Sec-WebSocket-Protocol" header for the OCPP version and have different websocket endpoints for different OCPP versions?

**Comment by purcell-lab** [comment]
OCPP2.1 now released. https://openchargealliance.org/ocpp-2-1-is-now-available/
