### ISSUE TITLE
Searching for a working central server scrypt 

### ISSUE THREAD

**Issue by milanhin** [mobilityhouse/ocpp#464]
Hi,

I am very new to the OCPP system and I'm looking for a python scrypt of a central server that can actually handle a connection with a charging point via OCPP 1.6. From what I have understood is the example code in this repository incomplete and can't actually handle transaction notifications or most other messages. Would any of you be willing to share a more complete version of a central system that I can use to test around with?

Additionally, how did you start coding the different handlers for each type of message? I feel like there is a lack of documentation for this library so I have no idea how to even start on making handlers.

Thanks!

**Comment by OrangeTux** [comment]
Hello, this library only contains the building blocks create requests and responses and route them to handlers. The library does not provide business logic to tie handlers together. 

I recently created https://github.com/OrangeTux/ocpp-for-humans, a project to explain certain OCPP concepts using this library. It's empty at the moment, but you can keep an eye on that.

**Comment by larrykluger** [comment]
I plan to write an open source controller that will use this library for ocpp communications. It won't be ready for testing until November or so.

What brand of charger do you have? Did it come with any ocpp documentation? Regards, Larry

**Comment by Jared-Newell-Mobility** [comment]
The documentation on how to use this library has been raised as needing improvement in https://github.com/mobilityhouse/ocpp/issues/55,
regarding OCPP documentation, this library has all updated OCA OCPP documentation of all available versions under docs

I will close this issue for now
