### ISSUE TITLE
Using Raspberry Pi as OCPP client

### ISSUE THREAD

**Issue by pamukcu09** [mobilityhouse/ocpp#466]
I want to use Raspberry Pi as main microcontroller in an EV Charger.
Is it possible to use this library as OCPP client on Raspberry Pi? @OrangeTux

**Comment by zenetio** [comment]
Yes, you can use RPi. This is a Python library that can easily run on RPi. Surely, if you search the internet, you will find some examples of OCPP running on RPi.

**Comment by pamukcu09** [comment]
Thank you for your answer @zenetio .
