### ISSUE TITLE
Using Raspberry Pi as OCPP client 

### ISSUE THREAD

**Issue by pamukcu09** [mobilityhouse/ocpp#467]
I want to use Raspberry Pi as main microcontroller in an EV Charger.
Is it possible to use this library as OCPP client on Raspberry Pi? @OrangeTux

**Comment by tropxy** [comment]
Hi @pamukcu09 yes, it is possible. I wouldnt call the Raspberry a microcontroller tho (a better wording would be microprocessor), because that implies you would need a special toolchain to program in it or use micro python, but if that is not the case you can install our lib using pip.

**Comment by pamukcu09** [comment]
thank you for your reply @tropxy
