### ISSUE TITLE
GetLogResponse.json parameter typo

### ISSUE THREAD

**Issue by AugustinMoinat** [mobilityhouse/ocpp#468]
In Improved Security for OCPP 1.6, there is a typo which is copied and not corrected in this library:

Document: Improved Security for OCPP 1.6 from 2018-11-20
   Section: N01 - Retrieve Log Information
   Figure 12. Sequence Diagram: Get Security Log
        GetLogResponse has parameter "fileName"
but in the same document:
   Section: 5.10. GetLog.conf
       In the table the parameter in "filename"

From comparing to other documents, I believe the first one to be correct, but it's implemented as the second one in [here](https://github.com/mobilityhouse/ocpp/blob/master/ocpp/v16/schemas/GetLogResponse.json), line 21

**Comment by Jared-Newell-Mobility** [comment]
I see your point, however, the published JSON schemas represent filename (all lower case). In addition, in Section 5.10. GetLog.conf in the document 'Improved security for OCPP 1.6-J edition 2 FINAL, 2020-03-31' this is also as lower case (which you have highlighted). As we use the schemas as a point of truth we have to stick with all lower case.

```json{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "urn:OCPP:Cp:1.6:2020:3:GetLog.conf",
  "definitions": {
    "LogStatusEnumType": {
      "type": "string",
      "additionalProperties": false,
      "enum": [
        "Accepted",
        "Rejected",
        "AcceptedCanceled"
      ]
    }
  },
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "status": {
      "$ref": "#/definitions/LogStatusEnumType"
    },
    "filename": {
      "type": "string",
      "maxLength": 255
    }
  },
  "required": [
    "status"
  ]
}
```
