### ISSUE TITLE
Outbound request from different thread

### ISSUE THREAD

**Issue by nfoecking** [mobilityhouse/ocpp#472]
Hello,

I am implementing a `ChargePoint` to communicate with my wallbox. I am wondering if it is possible to do outbound communication, i.e., send a request to the wallbox, from a different thread than the one in which the `ChargePoint` "lives". Here is the method in my `ChargePoint`-implementation that I call from a different thread:

```python
    async def send_get_composite_schedule(self):
        request = call.GetCompositeSchedulePayload(connector_id=1, duration=3600,
                                                   charging_rate_unit=ChargingRateUnitType.amps)
        await self.call(request)
```

Sometimes, this results in the following error: `RuntimeError: <Queue at 0x111cba5d0 maxsize=0 tasks=1> is bound to a different event loop`. I already identified where the error raises. It is in the `_get_specific_response()`, where the response is tried to read from `self._response_queue`. The problem might be there because the used queue (`asyncio.Queue`) is not thread-safe. As a workaround (not saying that this is a feasible solution), one can add a `sleep()` call in the `call()`-function, which seems to solve the problem.

```python
    async def call(self, payload, suppress=True, unique_id=None):
        camel_case_payload = snake_to_camel_case(asdict(payload))

        unique_id = (
            unique_id if unique_id is not None else str(self._unique_id_generator())
        )

        call = Call(
            unique_id=unique_id,
            action=payload.__class__.__name__[:-7],
            payload=remove_nones(camel_case_payload),
        )

        validate_payload(call, self._ocpp_version)

        # Use a lock to prevent make sure that only 1 message can be send at a
        # a time.
        async with self._call_lock:
            await self._send(call.to_json())
            # ------------- the line below was added ---------------
            await asyncio.sleep(0.01)
            try:
                response = await self._get_specific_response(
                    call.unique_id, self._response_timeout
                )
            except asyncio.TimeoutError:
                raise asyncio.TimeoutError(
                    f"Waited {self._response_timeout}s for response on "
                    f"{call.to_json()}."
                )

        if response.message_type_id == MessageType.CallError:
            LOGGER.warning("Received a CALLError: %s'", response)
            if suppress:
                return
            raise response.to_exception()
        else:
            response.action = call.action
            validate_payload(response, self._ocpp_version)

        snake_case_payload = camel_to_snake_case(response.payload)
        
        cls = getattr(self._call_result, payload.__class__.__name__)  # noqa
        return cls(**snake_case_payload)
```

Is this expected behavior, i.e., is it only supported to make requests in the same thread?

Thanks very much in advance!
Niklas

**Comment by OrangeTux** [comment]
> The problem might be there because the used queue (asyncio.Queue) is not thread-safe.

That's correct. [Almost all asyncio objects are not thread safe. 
](https://docs.python.org/3/library/asyncio-dev.html#asyncio-multithreading)
An event loop is (intended to) bound to a single thread. The `RuntimeError`  suggests that you've at least two threads, each with it's own event loop. That's not a good idea. Your Python program should run one event loop only.

In general, I wouldn't advice to mix `asyncio` with threads. It's possible, but tricky. 

Instead, start all your async servers concurrently in the main thread and let them communicate with each other using `asycio.Queues`. [ `asyncio.TaskGroup`](https://docs.python.org/3/library/asyncio-task.html#asyncio.TaskGroup) is very useful here.

**Comment by nfoecking** [comment]
Thanks very much for the quick reply.
