### ISSUE TITLE
Random Transaction Id in meter values

### ISSUE THREAD

**Issue by surmitbhui** [mobilityhouse/ocpp#478]
Hi, I have an operating CSMS system connected to multiple charge points operating on OCPP 1.6. However, I have encountered a seemingly random bug wherein the meter values being generated for a given transaction are being transferred with transaction id of 0 even though the transaction_id was generated and sent as part of the StartTransaction.conf message from the CSMS to the Charger. 

Would be extremely helpful if I could get some insight into this behaviour as it is purely random in nature with the meter values running at the right transaction_id most of the times with random situations with transaction_id as 0 for the same charger. 

As an example, I am attaching three screenshots from my logs, wherein the RemoteStart request is sent from the CSMS and accepted by the charge point, which in turn requests the CSMS with the StartTransaction request and the CSMS responds with a TransactionId. However, when the meter values do start coming in, it comes in at transactionId of 0 and not the end generated by the CSMS. 

![RemoteStart](https://github.com/mobilityhouse/ocpp/assets/33169391/df0a42d4-40da-4ccd-98e3-f495c2cc1ac5)
![StartTransaction](https://github.com/mobilityhouse/ocpp/assets/33169391/13fbe08c-a0b1-4134-8a26-8461e496e612)
![MeterValues](https://github.com/mobilityhouse/ocpp/assets/33169391/2a881e1a-de91-4c21-b1bb-f7c4fa5787cf)

Any help would be greatly appreciated!

**Comment by deepakEnercent** [comment]
MeterValues payload comes from charge_point so is charge_point is a real charger or is it dummy cms simulator.??

**Comment by surmitbhui** [comment]
> MeterValues payload comes from charge_point so is charge_point is a real charger or is it dummy cms simulator.??
 
Hi, It's a real charger. The issue is I am unable to figure out why the ChargePoint randomly disregards the transaction_id generated in the StartTransaction payload in some scenarios while using it at others. It seems to be in the way the CMS is responding to the calls and was hoping to get some insight into this behaviour in OCPP?

**Comment by zenetio** [comment]
Its random, but not only with the same CS?

**Comment by Jared-Newell-Mobility** [comment]
From the log messages the central system is providing a transaction id to the charge point, however, the application of the transaction id by the charge point in meter values is not happening. In 1.6 the specification makes this optional and it is possible the charge point vendor hasn't implemented this correctly, it could also be a bug related when a small amount of time exist  between when a transaction is started and when sending meter values. It maybe best to seek support from the charge point vendor or logs in the charge point to confirm. I will close this for now.
