### ISSUE TITLE
OCPP v1.6 ReserveNow call does not follow standard

### ISSUE THREAD

**Issue by psauer** [mobilityhouse/ocpp#48]
https://github.com/mobilityhouse/ocpp/blob/75dd91fb80f34c401365061e90db9907a9faac33/ocpp/v16/call.py#L96

In the `ReserveNowPayload`, the `parent_id_tag` field is optional, but is not reflected here. It should be `parent_id_tag: str = None`.  This lead to an error when receiving a ReserveNowPayload with the `parent_id_tag` not sent.

**Comment by tropxy** [comment]
You are indeed correct @psauer. Thanks for your report. We will address this issue asap.

**Comment by OrangeTux** [comment]
This issue has been fixed in v0.4.2
