### ISSUE TITLE
Add support for Python3.6

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#5]
Python 3.6 can be supported by installing the `dataclasses` package from Pypi. 

Note that the classifiers in `setup.py` must be updated to reflect the support for Python 3.6

**Comment by JavanWang** [comment]
Could you demonstrate how to send a request form central server to charge point
Thanks a lot

**Comment by OrangeTux** [comment]
@JavanWang I moved your question to a separate issue because I don't think it is related to Python 3.6 support.

**Comment by JavanWang** [comment]
@OrangeTux Thanks, and Sorry for  I am a newbie in github, not familiar with open a issue, I got it now.

**Comment by OrangeTux** [comment]
That is no problem @JavanWang . Welcome to Github! If you have any other questions, don't hesitate to to ask.
