### ISSUE TITLE
Send Message from Central System to the ChargePoint

### ISSUE THREAD

**Issue by ElHaban3ro** [mobilityhouse/ocpp#503]
Hi guys. I'm stuck with the library, because, according to the OCPP v1.6 documentation the 'ChangeAvailability' event must be sent from the Central System to the Charge Point. 

![imagen_2023-11-01_070851648](https://github.com/mobilityhouse/ocpp/assets/79483552/5f046003-0c6f-426b-b74a-25ab7c3ca2bb)

So trying to integrate it I run into the fact that the request from the central system is not sent, it triggers the event on the client but does not trigger a response. Why could this be happening?

**central_system.py**
```python
    async def send_change_availability(self, connectorId):
        request = call.ChangeAvailabilityPayload(connectorId, AvailabilityType.operative) #? Test
        await self.call(request)
```

**client.py**
```python
        @on('ChangeAvailability')
        async def on_change_availability(self, **kwargs):
              print('print to trigger')
              r = call_result.ChangeAvailabilityPayload(status = AvailabilityStatus.scheduled)
              return r

```

So I receive the error from the Central System:
```
raise asyncio.TimeoutError(
TimeoutError: Waited 30s for response on [2,"eaa61381-9b05-4fe2-945c-c505e7907681","ChangeAvailability",{"connectorId":234,"type":"Operative"}]
```

**Comment by OrangeTux** [comment]
I don't know, unfortunately. Nothing seems wrong with this code.

**Comment by ElHaban3ro** [comment]
> I don't know, unfortunately. Nothing seems wrong with this code.

Lol. It is very strange, isn't it? I also can't identify where the problem comes from, if from the client (loader) or from the central system.

In theory what I showed is fine, isn't it? When calling the "send" function I'm doing it from an event. Basically when it listens to a "MeterValues" it triggers the send_change_availability(), because I can't find another way to test it. This is the right way to use it, right? I don't think there is a problem with this.

**Comment by OrangeTux** [comment]
Does the charger respond to other OCPP requests? 

Make sure that the charger is "started" by calling [`ChargePoint.start()`](https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/charge_point.py#L42). Without that call, the `ChargePoint` won't consume inbound OCPP messages.

**Comment by ElHaban3ro** [comment]
> Does the charger respond to other OCPP requests?
> 
> Make sure that the charger is "started" by calling [`ChargePoint.start()`](https://github.com/mobilityhouse/ocpp/blob/master/examples/v16/charge_point.py#L42). Without that call, the `ChargePoint` won't consume inbound OCPP messages.


https://github.com/mobilityhouse/ocpp/assets/79483552/6d4b099e-53d5-4f07-a87f-16e97b24537d

**Comment by ElHaban3ro** [comment]
Problem fixed. Apparently it was a corrutine problem. My solution was to run the send function under an asyncio task:
```python

    async def send_reserve_now(self):
        loop = asyncio.get_event_loop()
        loop.create_task(self.reserve_now() # <-- Function calling 'self.call(request)'.


```


Good day, boys

**Comment by OrangeTux** [comment]
Great that you found the issue. This kind of stuff can get tricky some times.
