### ISSUE TITLE
Documentation on readthedocs is possibly outdated ?

### ISSUE THREAD

**Issue by HaroldObasi** [mobilityhouse/ocpp#515]
The documentation for this project on https://ocpp.readthedocs.io/en/latest/index.html says that the package only supports OCPP 1.6, meanwhile here it says OCPP 1.6 (errata v4), OCPP 2.0 and OCPP 2.0.1 (Final Version) are supported. is there maybe something i am missing ?

**Comment by OrangeTux** [comment]
Yep, good catch. The doc builder is down for a while now.

**Comment by HaroldObasi** [comment]
unlucky, are there still any good ways to read the docs ?

**Comment by Jared-Newell-Mobility** [comment]
@OrangeTux looks like you are owner of ocpp in readthedocs, what would you like to do here? Grant permission to me or change ownership of the ocpp project?

**Comment by OrangeTux** [comment]
@Jared-Newell-Mobility Can you create an account on [readthedocs.org](https://readthedocs.org) and send me your username or email privately? Than I can provide you with access to platform hosting the docs.

**Comment by Jared-Newell-Mobility** [comment]
Documentation is now updated so will close - see https://ocpp.readthedocs.io/en/latest/index.html
