### ISSUE TITLE
Typo in `v201.enums.StatusInfoReasonType.invaild_schedule`

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#519]
https://github.com/mobilityhouse/ocpp/blob/7e14b1664588e9f732f21fc5ff08369693385f35/ocpp/v201/enums.py#L1297

The variant must be called `invalid_schedule`.

**Comment by Jared-Newell-Mobility** [comment]
PR created - https://github.com/mobilityhouse/ocpp/pull/521

**Comment by Jared-Newell-Mobility** [comment]
PR approved and scheduled for release in v1.0.0
