### ISSUE TITLE
ChargingStatus Status in OCPP 2.0.1

### ISSUE THREAD

**Issue by roastedmonk** [mobilityhouse/ocpp#532]
For Connector Status:
`[2,"1699530088997","StatusNotification",{"connectorId":1,"connectorStatus":"Available","evseId":2,"timestamp":"2023-11-09T11:41:29.225Z"}]`

Similarly not Seeing for Charger like:
[2,"1699530088997","StatusNotification",{**"connectorId":0**,"connectorStatus":"Available",**"evseId":0**,"timestamp":"2023-11-09T11:41:29.225Z"}] 

As EvseID can be 0 for Charging station, we could send ConnevctorID also as 0, rite.
![2023-11-13 09_52_15-OCPP-2 0 1_part1_architecture_topology pdf and 11 more pages - Work - Microsoft​](https://github.com/mobilityhouse/ocpp/assets/29171405/f793b425-acaa-4ca4-840c-6cbffc2c3bc5)

Can it be implemented like this?

**Comment by Jared-Newell-Mobility** [comment]
I am not completely sure of the question, is it possible to give some more context?

**Comment by roastedmonk** [comment]
Status Notification ocpp message is only for sending connector status or even for charger status?

If yes for Charger also what should be the connectorID value.

**Comment by Jared-Newell-Mobility** [comment]
It is used for the connector status - Part 2 Specification, presents the valid connector statuses in section 3.23. ConnectorStatusEnumType.  Using the device model in part 1 Architecture and Topology displays that the connector is connected to the evse, so in this case the evse has to be referenced with a number >=1 - so 0 is not valid by the device model hierarchy. In addition,  in (part 2) section 1.59. StatusNotification 1.59.1. StatusNotificationRequest evseId and connectorId are required field, supporting again that 0 is not valid.

In section 2.22. EventDataType can be used for the charger status.

I hope this answers your question

**Comment by roastedmonk** [comment]
Thank you. So for charger status do we have to do aggregation of connector status to form charger status.

**Comment by Jared-Newell-Mobility** [comment]
Without knowing details of what is it you are trying to achieve - I can only say, by collecting each message at the CSMS and storing the state, then the charge point status for all connectors can be known. However, how this is implemented is outside of scope for this library.

**Comment by roastedmonk** [comment]
Understood. Thanks
