### ISSUE TITLE
How to properly translate OCPP JSON Specification

### ISSUE THREAD

**Issue by HaroldObasi** [mobilityhouse/ocpp#534]
I'm still new to OCPP, I have been reading a lot of the documentation but something I don't understand is how the JSON specification for a request type is translated into what the Charge Point actually sends to the server, for example the StartTransaction json specification from the documents is like this: 

```
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "id": "urn:OCPP:1.6:2019:12:StartTransactionRequest",
    "title": "StartTransactionRequest",
    "type": "object",
    "properties": {
        "connectorId": {
            "type": "integer"
        },
        "idTag": {
            "type": "string",
            "maxLength": 20
        },
        "meterStart": {
            "type": "integer"
        },
        "reservationId": {
            "type": "integer"
        },
        "timestamp": {
            "type": "string",
            "format": "date-time"
        }
    },
    "additionalProperties": false,
    "required": [
        "connectorId",
        "idTag",
        "meterStart",
        "timestamp"
    ]
}

```

but the request sent to the server has look something like this: 

`[2,"eDJ4Rv1CdKsh8M8rw8HyEakA4rlYs8NMs1xU","StartTransaction",{"connectorId":2,"idTag":"","timestamp":"2023-10-22T09:22:19Z","meterStart":0,"reservationId":0}]`

I can see the similarities between this request and the specification but I just want to make sure I am reading it currectly, if anyone can refer me to any resources on how i'm meant to do this i will appreciate

**Comment by OrangeTux** [comment]
Are you familiar with the[ OCPP 1.6 JSON specification](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-j-1.6-errata-sheet.pdf)? In short, the JSON schemas model the payload of a request and a response.

**Comment by HaroldObasi** [comment]
Thanks for responding, yeah i am, what i dont understand is how / why the websocket server expects an array instead of an object / dictionary that closely models the json specs

**Comment by Jared-Newell-Mobility** [comment]
So this library gives the dataclasses, enums neccessary to build each message type (as the payload), this is then serialised and sent over a websocket. The building blocks defined in this library aligned with ocpp 1.6 documentation, where the json specification is exactly the specifications for each message (is often used for validation). The example in this library shows a basic implementation for the boot notification message from the point of view of the central system and the charge point.
