### ISSUE TITLE
AttributeError: 'str' object has no attribute 'recv'

### ISSUE THREAD

**Issue by crepperman** [mobilityhouse/ocpp#540]
I am using Docker to build a central_system ocpp1.6, and I am encountering this issue.
the test scenario is that the Charge Point (CP) connects to the Central System (CS) and the issue occurs.
I don't know if there is any solution.

Additionally, the issue does not occur in the Windows 10 docker-desktop Docker Engine:v24.0.5 environment, which is strange.

Docker version: 24.0.5, build 24.0.5-0ubuntu1~22.04.1
Docker Images :  python:3.12.0-slim-bullseye
ocpp version: 0.22
```
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:websockets.server:server listening on 0.0.0.0:9000
INFO:root:Server Started listening to new connections...
INFO:websockets.server:connection open
INFO:root:Protocols Matched: ocpp1.6
ERROR:websockets.server:connection handler failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/server.py", line 236, in handler
    await self.ws_handler(self)
  File "/usr/local/lib/python3.12/site-packages/websockets/legacy/server.py", line 1175, in _ws_handler
    return await cast(
           ^^^^^^^^^^^
  File "/server/service/ocpp_server.py", line 163, in on_connect
    await asyncio.gather(cp.start(), self.register(cp))
  File "/usr/local/lib/python3.12/site-packages/ocpp/charge_point.py", line 160, in start
    message = await self._connection.recv()
                    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'recv'
INFO:websockets.server:connection closed
```

**Comment by crepperman** [comment]
Additionally, the issue does not occur in the Windows 10 docker-desktop Docker Engine:v24.0.5 environment, which is strange.

**Comment by Jared-Newell-Mobility** [comment]
This looks to be outside the scope of this library - the implementation of OCPP is up to the individual (for example this ocpp_server implementation, with docker). The purpose of this library gives only the building blocks, documentation and some simple demonstration.
