### ISSUE TITLE
I want to create an "inter-chargers" communication, but it seems that it is not possible.

### ISSUE THREAD

**Issue by ElHaban3ro** [mobilityhouse/ocpp#543]
Good morning!

I have a dilemma to which I see little solution, really, but if you can help me, so much the better.

The thing is that for each loader that connects to a central system runs in its own thread and when a third party (me, from another websocket) sends a request that must be redirected to the loader (in the form of OCPP) there is no way to do (or at least I can't find it).

I don't know how to communicate with that loader which is connected to the central system in another thread. 

What approaches could I consider? I had thought of something like a list where I store a reference to each loader instance. That is, every time a loader is connected, it would be added to a "global" list, where it can access at any comment to any client. Although I really don't know if this would work, it's just a theory.

I leave you a diagram of what happens to me (sorry, it is made in paint xd):

![image](https://github.com/mobilityhouse/ocpp/assets/79483552/327cbdad-21f1-48d3-9517-7f0d9ff82783)

**Comment by Jared-Newell-Mobility** [comment]
The best place to start with this is the document OCPP 2.0.1: Part 4 - JSON over WebSockets Implementation guide - section 3.1.1. this describes how to setup multiple change points to connect to a central system. The design of the central system is up to the individual (more information can be found in OCPP 2.0.1 Part 1 Architecture and Topology), this library gives the building blocks for this and some simple demonstration only.
