### ISSUE TITLE
Dataclass MessageInfoType in ocpp201 has different attribute name than in json Schema for NotifyDisplayMessagesRequest

### ISSUE THREAD

**Issue by AlfredoNaef** [mobilityhouse/ocpp#548]
Hello, 

I am currently using your library to implement OCPP 2.0.1 fro my company. While, testing that my implemnetation of the messages at least are sent, recieved and answered, I noticed that for NotifyDisplayMessagesRequest the Pyaload is not sent. After some digging, I found that if  in NotifyDisplayMessagesPayload in the attribute message_info I provide the MessageInfoType and inside this dataclass I also define the attribute end_data_time, then the payload is not sent because it fails the validation with the json schema for NotifyDisplayMessagesRequest. Specifically, in MessageInfoType.end_data_time is a typo and should be MessageInfoType.end_date_time, because in the json schema the field is called endDateTime. In conclusion, to fix this bug you just need to rename the attribute in MessageInfoType from end_data_time to end_date_time (it's just a simple e instead of a).

**Comment by Jared-Newell-Mobility** [comment]
Thanks, nice catch - a PR has been opened https://github.com/mobilityhouse/ocpp/pull/549

**Comment by Jared-Newell-Mobility** [comment]
Merged and will be included in the next minor release
