### ISSUE TITLE
Typo in datatypes.ChargingNeedsType.request_energy_transfer that fails validation Payload

### ISSUE THREAD

**Issue by AlfredoNaef** [mobilityhouse/ocpp#552]
Hello,

There is small typo in the dataclass ChargingNeedsType in ocpp.ocpp.v201.datatypes. Specifically, the attribute request_energy_transfer should be refactored to requested_energy_transfer. Otherwise when sending the Payload for NotifyEVChargingNeedsRequest for validation with json schema it fails, because in the schema the field is called requestedEnergyTransfer and in the payload after conversion to camel case is requestEnergyTransfer.

**Comment by Jared-Newell-Mobility** [comment]
Thanks - PR https://github.com/mobilityhouse/ocpp/pull/496/commits/790f2dbe616ff3f30a45683b88e4e1367d862c6e covers this problem, as it is a duplicate I'll close this for now
