### ISSUE TITLE
Wrong type in ocpp.ocpp.v201.datatypes.ReportDataType.variable_attribute that yiedl a failure in the validation of the Payload

### ISSUE THREAD

**Issue by AlfredoNaef** [mobilityhouse/ocpp#553]
Hello,

When sending the payload for NotifyReportRequest (with also the  optional field report_data in the payload) it fails at the validation with the json schema. After some digging, I found out that the problem is due to the data type for ReportDataType.variable_attribute, that in the latets release of your code is defined as VariableAttributeType. However, it  should be List[VariableAttributeType] because in the json schema for NotifyReportRequest the equivalent field variableAttribute is defined as array. As such, for easier usage by users of your library you should change the type as I suggested.

**Comment by Jared-Newell-Mobility** [comment]
Thanks for raising the issue - this is covered in the PR https://github.com/mobilityhouse/ocpp/pull/529 so I will close this for now
