### ISSUE TITLE
Bug in parsing floats in Payloads that yields the failure of sending 5 Messages

### ISSUE THREAD

**Issue by AlfredoNaef** [mobilityhouse/ocpp#555]
Hello,

The messages NotifyChargingLimitRequest, NotifyMonitoringReportRequest, ReportChargingProfilesRequest, RequestStartTransactionRequest and SetChargingProfileRequest fail to be validated and hence to be sent. The bug happen when in all these messages payloads is present a float. Specifcally :

- NotifyChargingLimitRequest is when you add the optional filed charging_schedule, that requires ChargingScheduleType, that requires ChargingSchedulePeriodType, that requires the field limit as a float.

- NotifyMonitoringReportRequest is when you add the optional filed monitor, that requires MonitoringDataType, that requires VariableMonitoringType, that requires the field value as a float.

- ReportChargingProfilesRequest is always present because of the field charging_profile that requires ChargingProfileType, that requires ChargingScheduleType, that requires ChargingSchedulePeriodType, that requires the field limit as a float.

- RequestStartTransactionRequest is when you add the optional field charging_profile that requires ChargingProfileType, that requires ChargingScheduleType, that requires ChargingSchedulePeriodType, that requires the field limit as a float.

- SetChargingProfileRequest is always present because of the field charging_profile that requires ChargingProfileType, that requires ChargingScheduleType, that requires ChargingSchedulePeriodType, that requires the field limit as a float.

Aftre reading the comment inside your code to my understanding the problem is due to the parser used to parse the floats in the payloads, that a default is float(). Indeed, you left a comment specifying that for some schemas should be used decimal.Decimal. However, as an user of your library I can only access your code up to the call method of your ChargePoint class and there is no possibility for me to sepcify the parser inside call - validate_payload - get_validator. Do you think that adding the possibility to specify the parse_float at the call method will fix the issue or is there another problem with the parsing of the floats?

**Comment by OrangeTux** [comment]
Thanks for your elaborate report. 

I'm curious why validation fails, though. The schemas for OCPP 1.6 limit the decimal points of a few number types to 1.  It does so using the JSON Schema keyword [`multipleOf`](https://github.com/search?q=repo%3Amobilityhouse%2Focpp%20multipleOf&type=code). See for example [the subschema for  `ChargingSchedulePeriod.limit`. ](https://github.com/mobilityhouse/ocpp/blob/a9df8ebdaee922c323be1d06eace2d5a35a5f747/ocpp/v16/schemas/SetChargingProfile.json#L81-L84)

You noticed correctly that this library includes a custom encoder to serialize these numbers. See for example [here](https://github.com/mobilityhouse/ocpp/blob/a9df8ebdaee922c323be1d06eace2d5a35a5f747/ocpp/messages.py#L182-L219) and [here](https://github.com/mobilityhouse/ocpp/blob/a9df8ebdaee922c323be1d06eace2d5a35a5f747/ocpp/messages.py#L28-L63).

The schemas of OCPP 2.0.1 don't use the `multipleOf` JSON keyword. Therefore, I don't understand how you run into validation issues. Can you provide a code example shows the validation issue?

**Comment by Jared-Newell-Mobility** [comment]
To confirm the types highlighted in the issue are floats in the library - changing to question
