### ISSUE TITLE
Wrong data type in CostUpdatedPayload.total_cost in respect to json schema

### ISSUE THREAD

**Issue by AlfredoNaef** [mobilityhouse/ocpp#557]
Hello,

There is a mismatch between the data type for CostUpdatedPayload.total_cost in ocpp.ocpp.v201.datatypes and the json schema for CostUpdatedRequest. Specifically, in the first is defined as integer and the json schema a number, tha usually should be a float in python. Nevertheless, this difference yields the failure of the validation of the payload and hence the message is not sent. Though, just changing the type to float in CostUpdatedPayload.total_cost might not solve the problem, because afterwards the payload validation would fails when parsing the floats as metnioned in a previous issue of mine #555.

**Comment by OrangeTux** [comment]
Thanks for the report. You're right. The specification clearly states it's a decimal. And therefore, the `dataclass` should model the attribute `total_cost` as a float.

**Comment by Jared-Newell-Mobility** [comment]
PR created https://github.com/mobilityhouse/ocpp/pull/596

**Comment by Jared-Newell-Mobility** [comment]
Merged so will now close
