### ISSUE TITLE
Error while handling request

### ISSUE THREAD

**Issue by Ataraxiall** [mobilityhouse/ocpp#563]
Good afternoon, I have an OCPP error in some transactions, all of the same type (DeAuthorized). 

ERROR - Error while handling request '<Call - unique_id=fe87613f-a4a7-4434-8c1a-4451242c76a9, action=StopTransaction, payload={'idTag': 'MLG4C4F9U29HNUZCIHZM', 'timestamp': '2023-12-26T19:27:38.289Z', 'meterStop': 892000, 'transactionId': 1703609619, 'reason': 'DeAuthorized'}>'

V1.6 Json
Can you help me? Thank you.

**Comment by OrangeTux** [comment]
What is the error? Can you elaborate.

To me, this seems fine.  The `StopTransaction` indicates the end of a charging session. The reason `DeAuthorized` seems to indicate that someone provided an RFID to end the session and unplug the cable.
