### ISSUE TITLE
In GA, validate project against Python 3.11 and 3.12.

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#564]
Currently, this project is tested against [Python 3.7 till and including Python 3.10](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/.github/workflows/pull-request.yml#L14-L17).

The list should be extended to Python 3.11 and 3.12.

Note that #550 must be merged in order for the tests to pass in  Python 3.11 and 3.12

**Comment by OrangeTux** [comment]
Some work has been done already in #475

**Comment by Jared-Newell-Mobility** [comment]
Merged so will close
