### ISSUE TITLE
Drop support for Python 3.7

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#565]
Python 3.7 reached End of Life. Therefore, we can stop testing against this version. 

We should:
1. [remove Python 3.7 from our workflow.](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/.github/workflows/pull-request.yml#L14)
2. [raise the minimum Python supported Python version to 3.8](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/pyproject.toml#L34)
3. [remove the dependency on `asynctest`](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/pyproject.toml#L38-L39) That fixes #433 
4. Remove [Python 3.7 classifier](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/pyproject.toml#L30) from pyproject.toml

**Comment by MuhammadHasnain77** [comment]
I have remove the version 3.7 from workflow check it out
also can you explain the other two issue

**Comment by OrangeTux** [comment]
Among other things, `pyproject.toml` lists all dependencies of this project. That includes [the Python version(s)](https://github.com/mobilityhouse/ocpp/blob/5f27521b5c7b83abfb61217036ae5776e1fb6998/pyproject.toml#L34) that are supported by this project. 

That file must be modified so minimum supported Python version is raised from Python 3.7 to Python 3.8.  Read more at Poetry's documentation about [dependency specification](https://python-poetry.org/docs/dependency-specification/).

`asynctest` is a dependency when using this project with Python 3.7. For all new Python version, this dependency is not required anymore. Since we drop support for Python 3.7, we can also remove the dependency `asynctest` completely. [Here](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies) you can read more on restricting dependencies to specific Python version

**Comment by MuhammadHasnain77** [comment]
Thanks for describing the issue I will  work on it.

**Comment by Jared-Newell-Mobility** [comment]
Additional work to date can be found in https://github.com/mobilityhouse/ocpp/pull/475

**Comment by MuhammadHasnain77** [comment]
Hi 
Can you see my PR did i correct all the issues?

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/566

**Comment by Jared-Newell-Mobility** [comment]
Associated PR https://github.com/mobilityhouse/ocpp/pull/566

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/585 created and approved for inclusion in v1.0.0 - so closing issue

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/585 created and approved for inclusion in v1.0.0 - so closing issue
