### ISSUE TITLE
Correct naming of members of `v201.enums.AttributeType` 

### ISSUE THREAD

**Issue by Jared-Newell-Mobility** [mobilityhouse/ocpp#577]
The members `AttributeType.minSet` and `AttributeType.maxSet` don't follow the Python naming style guide. 
Instead, they should be written AttributeType.min_set` and `AttributeType.max_set`.

**Comment by OrangeTux** [comment]
The

**Comment by Jared-Newell-Mobility** [comment]
PR https://github.com/mobilityhouse/ocpp/pull/578 created and approved for inclusion in v1.0.0, so will close
