### ISSUE TITLE
Remove suffex 'Payload' from all calls and call results

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#583]
All the calls and call result types are suffixed with the term 'Payload'.
This term makes lengthy type names even more verbose and should be removed.

This change will break every application relying on this library. So I suggest we deprecate these old style types and urge users to use the new types. In a v2 of this library we can remove them.

**Comment by Jared-Newell-Mobility** [comment]
Satisfied with PR - https://github.com/mobilityhouse/ocpp/pull/584 - so will close
