### ISSUE TITLE
 Data transfer from CP to Central

### ISSUE THREAD

**Issue by Jonamaita** [mobilityhouse/ocpp#619]
I have been testing my central system sending it a data transfer message. So, I sent a json with the data transfer message how below:

```
data = [{
        "timestamp": str(datetime.utcnow()),
        "connectorId": 1,
         "vin": "1234567ADAD",
}]

data = json.dumps(data)

request = call.DataTransferPayload(
    vendor_id="StarCharge",
    message_id="CarId",
    data=data,
)
```
It should be noted that the `data` is serealized, so when use `call.DataTransferPayload` method the `data` will be seralized again remaining as follows:

`'"[{\\"timestamp\\": \\"2024-03-18 01:54:02.060142\\", \\"connectorId\\": 1, \\"vin\\": \\"1234567ADAD\\"}]"'`

The data was double seralized, so when the central system will unserializes the `data` it will get a `string` object and not `dict` object.

It is important to say that some industry loaders send a `json` in the data transfer message, so maybe the library should handle this case.

I can do a `PR` with a approach if this issue is accepted.

**Comment by FilMar** [comment]
Hi,  you don't have to do json.dumps on data, when you send with call(payload) function all the payload is translated to a json str

**Comment by Jonamaita** [comment]
> Hi, you don't have to do json.dumps on data, when you send with call(payload) function all the payload is translated to a json str

The `data` argument must be a string.

**Comment by FilMar** [comment]
Ok, if the data field needs to be a string, where is the problem here? You only need to do json.loads on the data you receive if you translated it to json when sending. Maybe your idea is to automatically deserialize twice if the string is json formatted?

**Comment by jainmohit2001** [comment]
Hi @Jonamaita, as per the official OCPP 1.6J and OCPP 2.0.1 documentation, the DataTransfer command requires the data field to be a string. In your case, the CP needs to send serialized json data (as you are already doing) and the Central System will received the serialized data only (We can't automatically deserialize the data again here as it will break for non-json data).
In short, the Central system should deserialize the data, if needed, on its own.
I hope this clears the issue at hand. Feel free to open the issue if it is still unclear.
