### ISSUE TITLE
deployment aiohttp and websocket in AKS, many Pods?

### ISSUE THREAD

**Issue by tomha85** [mobilityhouse/ocpp#633]
Any suggestions how to deploy websocket and aiohttp web server in production? AKS? ITO HUB?
code will not work if we deploy into AKS becaue it is stateful program, it will be worked on a Pod
Could someone have a suggestion for production

When your issue is related to code that isn't working as expected, please
enable debug logs:

``` python
import logging
logging.basicConfig(level=logging.DEBUG)
```

More info can be found in the [Debugging
section](https://github.com/mobilityhouse/ocpp#debugging) of the README.

If these actions didn't help to find the cause of your issue, please provide
code samples and logs with your question.

**Comment by jainmohit2001** [comment]
The question is not specific to OCPP package but a broader question about how to deploy python applications that are using websockets and aiohttp web server.
Closing this issue as it is not relevant to OCPP package.
