### ISSUE TITLE
Impossible to get CP connecting to CS

### ISSUE THREAD

**Issue by quentinalt-dintec** [mobilityhouse/ocpp#653]
I cannot get my CP to connect to my CSMS, I do not know what to set in the Server URL on my configuration interface of my CP :

![image](https://github.com/mobilityhouse/ocpp/assets/172390743/30bf8b39-0c59-49b7-a172-b1e2e55a224e)

I tried a lot of things such as :
- use "ws" instead of "wss"
- use different IP adresses instead of "test1.ocpps.ekoenergetyka.com.pl"
- use /ocpp instead of /ocppj

Some help would be very much appreciated !

**Comment by Yoshida-Taisei** [comment]
"I think it is necessary to modify the connection URL. Specifically, wouldn't it be to append the identify to the end?

Example: CP->CS connection destination
`wss://test1.ocpps.ekoenergetyka.com.pl/ocppj/QP-4723
`
However, I might be wrong as I have never used that simulator before."

**Comment by quentinalt-dintec** [comment]
Hello,
This is not a simulator, this is the settings interface of a real EV charger.
The point is that I cannot find out what URL to put in this and in my CSMS settings.

**Comment by Yoshida-Taisei** [comment]
Thank you, I understand.

Here are some points to check:

- Is the endpoint (/ocpp, /ocppj) necessary?
- Is the port specified? (:8080, etc.)
- Is the CP identifier (QP-4723) registered in the CS?

Is the CS something you have set up yourself?

**Comment by jainmohit2001** [comment]
Closing this issue, as it is not related to the OCPP packages.
