### ISSUE TITLE
Individual loggers for each ChargePoint instance

### ISSUE THREAD

**Issue by jainmohit2001** [mobilityhouse/ocpp#655]
Hi there.
I have been using the library for quite a while now.

I have recently come up with a small requirement: I want to log the OCPP stream to AWS Cloudwatch. After integrating with [watchtower](https://pypi.org/project/watchtower/), things are working fine, and all the OCPP logs are logged in a single log stream.

I wanted to understand if there is any way I can create an individual stream for OCPP logs based on the ID of the charger.

Any insights or direction would be of great help.

**Comment by jainmohit2001** [comment]
I think this requirement that I am facing could be a part of a bigger feature where the `ChargePoint` class can accept a `logger` instance from the user. Allowing users to handle the logging of OCPP messages on a per-charger basis.

**Comment by jainmohit2001** [comment]
@OrangeTux, is the repo still maintained?

**Comment by jainmohit2001** [comment]
@OrangeTux  @Jared-Newell-Mobility @proelke, let us know if the library is still being maintained.

**Comment by OrangeTux** [comment]
You're right. This library isn't real

**Comment by OrangeTux** [comment]
@mdwcrft You have expressed interest to take over ownership of this project. Is that offer still up?

**Comment by jainmohit2001** [comment]
@OrangeTux , I am also willing to contribute and keep this library up to date.

**Comment by jainmohit2001** [comment]
Hey @OrangeTux, any chance I can get the opportunity to maintain this package?

**Comment by jainmohit2001** [comment]
@OrangeTux @Jared-Newell-Mobility @proelke, let me know if I can help you manage this package.

**Comment by OrangeTux** [comment]
Hello @jainmohit2001, thanks for your offer. Ideally, I'm looking for multiple people to take over ownership, so I'll announce publicly that this project looking for new owners.

**Comment by mdwcrft** [comment]
> @mdwcrft You have expressed interest to take over ownership of this project. Is that offer still up?

Yep I'm happy to be added as a maintainer if there are others to make up for my rusty Python!

**Comment by OrangeTux** [comment]
Thanks @mdwcrft ! I'll move the discussion about maintainers to #662

**Comment by hhuseyinpay** [comment]
I wanted to let you know that I implemented this feature and submitted a pull request about four months ago: #641 The pull request is still awaiting review.

**Comment by jainmohit2001** [comment]
Duplicate of #641
