### ISSUE TITLE
Project is looking for new owners

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#662]
@Jared-Newell-Mobility  and I are stepping down as owners and maintainers of this project.
We both switched contexts and and lost interest in the project.

The project is used by several companies and [many open source projects](https://github.com/mobilityhouse/ocpp/network/dependents).

Who is/are willing to take ownership of this project?

The new owner(s) are responsible for maintaining, bug fixing and releasing the library.

**Comment by OrangeTux** [comment]
@jainmohit2001 already expressed interest.

**Comment by OrangeTux** [comment]
@mdwcrft also offered his help.

**Comment by OrangeTux** [comment]
And offline, @proelke also offered help

**Comment by OrangeTux** [comment]
Thanks for offering your help @proelke, @jainmohit2001 and @mdwcrft! It's really appreciated. 

I gave admin permissions to this repo to @mdwcrft and @proelke. I gave write permissions to @jainmohit2001.

@mdwcrft @proelke Can you make accounts on pypi.org and readthedocs.org? When you've done that, I can give you appropriate access.

**Comment by Abiorh001** [comment]
my company use the project and i would love to be part of the maintainer and contributor

**Comment by mdwcrft** [comment]
@OrangeTux - made accounts on pypi and readthedocs, my username is `chad-switch` on both

**Comment by OrangeTux** [comment]
@mdwcrft I invited you as owner of the pypi project. I failed to give you access to the project on RTD:


![2024-09-24-105023_927x446_scrot](https://github.com/user-attachments/assets/7a638ff1-fd20-4797-8278-80007da2f090)

Can you check that  you created an account on readthedocs.**org**  and not readthedocs.**com**.

**Comment by OrangeTux** [comment]
@Jared-Newell-Mobility I noticed that you already revoked your own access on pypi.org and Github. I also removed your access from the project on ReadTheDocs.

@tropxy You still have admin access to this project on Github and pypi.org. You haven't been much involved in the last few years,  I suggest we reduce your permissions or remove them entirely. What is your opinion here?

**Comment by OrangeTux** [comment]
@Abiorh001 Thanks for your offer! Contributors in the form of pull requests or reviews are always welcome.

**Comment by mdwcrft** [comment]
@OrangeTux apologies can you try again on RTD? Same username

**Comment by a-alak** [comment]
Thank you for all the time you put in it! Really appreciated.
And thanks to the new owners/contributors for willing to continue the project.
I just want to express my interest in contributing here. 
I have very minimal open source experience and would not now how projects like this is managed and cannot find any guide in the docs, but if you guys need contribution hit me up!

**Comment by Yoshida-Taisei** [comment]
@OrangeTux 
Thank you for leading this project so far.
This project is being used in our company's product, and many chargers are operating successfully.

I would like to continue contributing through issues and reviews.

**Comment by OrangeTux** [comment]
@mdwcrft The invitation on RTD is pending.

**Comment by OrangeTux** [comment]
Thanks @Yoshida-Taisei and @a-alak!  I leave the organization of this project to the new maintainers. Please check with them how to contribute.

**Comment by jainmohit2001** [comment]
Hi all,

We have the list of the new owners and maintainers as follows:

- Owners: @mdwcrft @proelke 
- Maintainers: @jainmohit2001

We welcome all the interested developers to contribute to this package through issues, reviews, discussions and PRs.

@mdwcrft and @proelke, please close this issue once everything is setup at your end. I think we can start with a simple `CONTRIBUTING.md` doc listing out various templates and ways for contributing. I have some easy changes and issues that I'll start creating soon.

**Comment by jainmohit2001** [comment]
Hi @mdwcrft and @proelke.
I hope you were able to assume ownership role. Please help me with processes and get things rolling. We have some improvements and bug fixes already lined up.

**Comment by RobertDeLeeuw** [comment]
Linux Foundation Energy has started a new Special Intrest Group (SIG) for EV Charging. Goal is to bring a lot of open source projects in the EV charging space toghether. I invite the new mainteiners/admins of the MobilityHouse OCPP project to join one of the monthly calls. I would love to discuss the plans and align with other open source projects in the EV charging space.
Mailing list can be found at: https://lists.lfenergy.org/g/ev-charging-sig

**Comment by proelke** [comment]
I'm happy to join a call but the main issue is that none of the current maintainers are employed or connected to TMH. I'm the closest as a former employee but I don't know what their plan is for the library and I'm not in a position to speak for them. However I can try to get in touch with contacts, or someone currently at TMH can comment.

**Comment by RobertDeLeeuw** [comment]
Dont get me wrong, anybody is welcome during the EV Charging SIG calls. Working on a open source project or not. f that project is part of LF Energy or not. I would really love to get to know the new maintainers. 
Next to that, I think it is a good idea for the new maintainers to discuss with TMH what their current goal/plans are for this library.

**Comment by proelke** [comment]
We've crossed paths at various events before and you've also encountered my colleague and owner of this project @mdwcrft. @jainmohit2001 is a new comer that I don't know personally. I will work to get in touch with someone at TMH. If you'll be at the OCA 10 year event, we can catch up there @RobertDeLeeuw.

**Comment by ajmirsky** [comment]
are you looking for additional maintainers? what was a passing interest has become a passionate deep dive into the world of electric vehicle charging. would be happy to contribute!

**Comment by jainmohit2001** [comment]
Hi @ajmirsky, you are welcome to pick up issues and discussions and contribute to the library in any way you feel is possible for you. Feel free to create PRs whenever necessary.

**Comment by mdwcrft** [comment]
Hi all, back from my holidays and looking forward to collaborating! @RobertDeLeeuw I've subscribed to the newsletter and will join the next available call.

Closing this issue now as I it looks like we're all set up with the new team
