### ISSUE TITLE
Docs for the package

### ISSUE THREAD

**Issue by jainmohit2001** [mobilityhouse/ocpp#671]
The following list of docs are necessary and good-to-have templates

- [x] README.md
- [x] CHANGELOG.md
- [x] Issue templates
    - [x] Bug report template
    - [x] Feature request template
    - [x] Documentation request template
- [x] SECURITY.md
- [x] CONTRIBUTING.md
- [x] CODE_OF_CONDUCT.md
- [x] SUPPORT.md

We welcome PRs for the above docs from the community.

**Comment by jainmohit2001** [comment]
@mdwcrft @proelke, we can use the following resources to add relevant templates to the repo. I believe only you have the permission to do this action.

Resources:

- [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
- [Creating a default community health file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file)

**Comment by mdwcrft** [comment]
@jainmohit2001 - new issue templates proposed here: https://github.com/mobilityhouse/ocpp/pull/679
