### ISSUE TITLE
Hactoberfest inclusion

### ISSUE THREAD

**Issue by jainmohit2001** [mobilityhouse/ocpp#672]
We can include this package to the [hacktoberfest](https://hacktoberfest.com/) event.

**Comment by jainmohit2001** [comment]
@proelke can you please add `hacktoberfest` topic to the repo?

**Comment by jainmohit2001** [comment]
@mdwcrft

**Comment by mdwcrft** [comment]
Apologies missed this one but I've added it now for next time
