### ISSUE TITLE
Add support for OCPP 2.0.1

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#74]

**Comment by davystrong** [comment]
How difficult is this? I see that there is a script to generate the dataclasses. What else needs to be done?

**Comment by OrangeTux** [comment]
With the correct scripts the code could to support OCPP 2.0.1 could be generated. [This script](https://github.com/mobilityhouse/ocpp/blob/master/scripts/schema_to_dataclass.py) can create the Call and CallResult dataclasses, but I am not sure how stable the script it.

We currently don't have scripts to generate the enums yet. But overall it shouldn't be difficult to modify or create scripts to generate the support.

I also saw that @tropxy did some work in adding OCPP 2.0.1 support lately. You can follow the progress in PR #88.
