### ISSUE TITLE
Charge Point reconnects every 40 seconds

### ISSUE THREAD

**Issue by pfirtelu** [mobilityhouse/ocpp#79]
Hi there
I have created a minimal server example with OCPP in python which works. It's basically built like this:

```
import ...
class ChargePoint(cp):
    async def startcp(self):
        while True:
            message = await self._connection.recv()
            await self.route_message(message)

    @on(Action.BootNotification)
    def on_boot_notitication(self, charge_point_vendor, charge_point_model, **kwargs):
        return call_result.BootNotificationPayload(current_time=datetime.utcnow().isoformat(),interval=100,status="Accepted")

    @on(Action.StatusNotification)
    ....
    ....

    ....


async def send_periodically():
    while True:
        await asyncio.sleep(4)
        # Execute some code periodically...


async def on_connect(websocket, path):
    # Code for new charging pile....


async def main():
    server = await websockets.serve(
        on_connect,
        '0.0.0.0',
        9000,
        subprotocols=['ocpp1.6']
    )
    await server.wait_closed()

if __name__ ==  '__main__':
    asyncio.async(main())
    asyncio.async(send_periodically())
    asyncio.get_event_loop().run_forever()
```

My problem is that charging piles get disconnected exactly 40 secs after they connect. On the charging point I see no settings correlated with this reconnecting loop. It basically works because instantly after disconnecting, they connect again. But certain functions behave not very smooth with this behavior (eg. if I want to use my function send_periodically to make sure all charging piles are read out periodically. It often fails when hitting exactly the reconnect time of a charging pile.)

Does anyone know this behavior? Could this be kind of an OCPP feature? Am I not correctly handling some kind of message to cause the pile to reconnect (because it does not receive some signal in a certain time?) I can see that it could make sense that the charging piles reconnect in preset intervals to allow reconnection after failures. But every 40 secs seems far too often for me.
Unfortunately I have only one type of charging pile to test this.
Thanks for your inputs!

**Comment by tropxy** [comment]
Hi @pfirtelu 

Well the only timeout that exists is when the CS sends a CALL and the CP does not respond for more than 30 sec. Then as far as I know, a TimeoutError is raised and the connection breaks. Are you sending a message that your CP does not answer? 

Also, can you explain me why are you using this method?
```python
async def startcp(self):
        while True:
            message = await self._connection.recv()
            await self.route_message(message)
```

when there is this method [https://github.com/mobilityhouse/ocpp/blob/6098908e6f7e51a355bcbeb3eda7479f73d6781c/ocpp/charge_point.py#L120](https://github.com/mobilityhouse/ocpp/blob/6098908e6f7e51a355bcbeb3eda7479f73d6781c/ocpp/charge_point.py#L120)

**Comment by OrangeTux** [comment]
Not sure if this one is related #67. 

Are you able to monitor the network traffic with `tcpdump` or `wireshark`? The logs of one of those programs would be help ful.

**Comment by pfirtelu** [comment]
Thanks for your answers!

> Are you sending a message that your CP does not answer?
> 
This also happens if I break down my minimal example to only answers from calls in the following form:
```
def on_something(self, charge_point_vendor, charge_point_model, **kwargs):
        return call_result.SomePayload
```
And not sending other messages from the CS to the CP. So I think it is not correlated to that?

> Also, can you explain me why are you using this method?
> ```async def startcp(self):```

I overloaded this because I added some of my own code to it, so it can be neglected...

> Are you able to monitor the network traffic with `tcpdump` or `wireshark`? The logs of one of those programs would be help ful.

I have tcpdump on the server but don't know very well how to use it or how to interpret the output. I attached 2 files:

[1.txt](https://github.com/mobilityhouse/ocpp/files/4375013/1.txt)

Output of **tcpdump -i INTERFACE 'port 9000'**
There should be reconnects at 12:20:11, 12:20:51 and 12:21:32

[2.txt](https://github.com/mobilityhouse/ocpp/files/4375014/2.txt)

Output of **tcpdump -i INTERFACE 'port 9000' -A**
There should be reconnects at 12:39:40, 12:40:20 and 12:41:01

Where SERVERNAME is the IP of my server, CHARGEPOINT is the IP of my chargepoint and CHARGEPOINTID is the OCPP ID of my chargepoint.

**Comment by pfirtelu** [comment]
Meanwhile I've also contacted the supplier of the charging point. He says that when all OCPP messages are answered, there should be no reconnects. In my code I have the following answers to standard messages:

```
    @on(Action.BootNotification)
    def on_boot_notitication(self, charge_point_vendor, charge_point_model, **kwargs):
        return call_result.BootNotificationPayload(
            current_time=datetime.utcnow().isoformat(),
            interval=100,
            status="Accepted"
        )
    @on(Action.StatusNotification)
    def on_status_notification(self, **kwargs):
        #self.chargerlog("Action.StatusNotification")
        return call_result.StatusNotificationPayload()
    @on(Action.Heartbeat)
    def on_heartbeat(self, **kwargs):
        return call_result.HeartbeatPayload(
            current_time=datetime.utcnow().isoformat()
        )
   @on(Action.MeterValues)
    def on_meter_values(self, **kwargs):
        return call_result.MeterValuesPayload()
    @on(Action.DataTransfer)
    def on_data_transfer(self, **kwargs):
        return call_result.DataTransferPayload(
            status=RegistrationStatus.accepted,
            data=None
        )
    @on(Action.FirmwareStatusNotification)
    def on_firmware_status_notification(self, **kwargs):
        return call_result.UpdateFirmwarePayload()
    @on(Action.StartTransaction)
    def on_start_transaction(self, **kwargs):
        return call_result.StartTransactionPayload(
            transaction_id = 1,
            id_tag_info = None
        )
    @on(Action.StopTransaction)
    def on_stop_transaction(self, **kwargs):
        self.chargerlog("Action.StopTransaction")
        return call_result.StopTransactionPayload(
            id_tag_info=None
        )
```

Is there anything missing for a minimal working example without having the CP reconnecting? Are these Payloads correct for a minimal example?

Is there a way with @on to catch all the other incoming messages which not yet have been caought with @on?

Thank you.

**Comment by OrangeTux** [comment]
For a true minimal example you should implement the Core feature profile for OCPP. 

You can see all in  and out going by configuring the `ocpp` logger, even some unrouted messages.

``` python
import logger
logger = logging.getLogger("ocpp")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
```

Otherwise you could override `ChargePoint.route_message()` and `ChargePoint._send()` as described here: https://github.com/mobilityhouse/ocpp/issues/78#issuecomment-602202612

**Comment by OrangeTux** [comment]
@pfirtelu Any update on your side?

**Comment by pfirtelu** [comment]
Dear OrangeTux
I implemented logging as you suggested, which displayed messages sent from Server to CP:
```
import logging
logger = logging.getLogger("ocpp")
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
```
Then I overloaded route_message as per your advice, to also get messages from CP to Server, as follows:
```
class ChargePoint(cp):
    ...
    async def route_message(self, message: bytes):
        print("Received:        "+str(message))
        await super().route_message(message)
    ...
```
This gives me the following communication:
```
Received:           [2,"122724","BootNotification",{"chargePointVendor":"MANUFACTURER","chargePointModel":"CHARGERMODEL","chargePointSerialNumber":"SERIALNUMBER","firmwareVersion":"FIRMWAREVERSION"}]
CHARGEPOINTID: send [3, "122724", {"currentTime": "2020-04-10T12:12:11.996422", "interval": 100, "status": "Accepted"}]
Received:           [2,"122725","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
CHARGEPOINTID: send [3, "122725", {}]
Received:           [2,"122726","Heartbeat",{}]
CHARGEPOINTID: send [3, "122726", {"currentTime": "2020-04-10T10:12:12.087976"}]
Received:           [2,"122727","Heartbeat",{}]
CHARGEPOINTID: send [3, "122727", {"currentTime": "2020-04-10T10:12:23.060381"}]

<-- here the charge point disconnects and reconnects again for some reason -->

Received:           [2,"122728","BootNotification",{"chargePointVendor":"MANUFACTURER","chargePointModel":"CHARGERMODEL","chargePointSerialNumber":"SERIALNUMBER","firmwareVersion":"FIRMWAREVERSION"}]
CHARGEPOINTID: send [3, "122728", {"currentTime": "2020-04-10T12:12:52.304683", "interval": 100, "status": "Accepted"}]
Received:           [2,"122729","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"Available"}]
CHARGEPOINTID: send [3, "122729", {}]
Received:           [2,"122730","Heartbeat",{}]
CHARGEPOINTID: send [3, "122730", {"currentTime": "2020-04-10T10:12:52.405214"}]
Received:           [2,"122731","Heartbeat",{}]
CHARGEPOINTID: send [3, "122731", {"currentTime": "2020-04-10T10:13:23.059333"}]

<-- next reconnect -->
```
As you see almost exactly every 40 secs the charge point reconnects. As can be seen I have blanked manufacturer, model, firmware, ... of the charging point...

Did I do everything right with my answers to the received messages? Is this a problem on the Charge Point side? Is an empty payload as answer to "StatusNotification" correct? Thank you for further advice!

**Comment by tropxy** [comment]
Hi @pfirtelu,
Thanks for sharing your results.
I have analyzed them and I think I have two comments to do about them. Before that, I want to share you some logs output of a successful test with a Vendor, so that you can compare with your results.

```shell
2019-12-13T13:30:23.957Z:COM:ocpp_rpc.c:1108:-> [2,"1","BootNotification",{"chargePointVendor":"XXXX","chargePointModel":
2019-12 13T13:30:23.957Z:COM:ocpp_rpc.c:1108:"NXXX","chargePointSerialNumber":"XXXX","chargeBoxSerialNumber":"TM
2019-12-13T13:30:23.957Z:COM:ocpp_rpc.c:1108:H_000620","firmwareVersion":"#1:4-30660"}]
2019-12-13T13:30:24.011Z:COM:ocpp_rpc.c:1059:<- [3, "1", {"currentTime": "2019-12-13T12:30:24Z", "interval": 350, "status": "
2019-12-13T13:30:24.011Z:COM:ocpp_rpc.c:1059:Accepted"}]

2019-12-13T13:30:34.414Z:COM:ocpp_rpc.c:1108:-> [2,"2","StatusNotification",{"connectorId":0,"errorCode":"NoError","status":"
2019-12-13T13:30:34.414Z:COM:ocpp_rpc.c:1108:Available"}]
2019-12-13T13:30:34.476Z:COM:ocpp_rpc.c:1059:<- [3, "2", {}]
2019-12-13T13:30:34.480Z:COM:ocpp_rpc.c:1108:-> [2,"3","StatusNotification",{"connectorId":1,"errorCode":"NoError","status":"
2019-12-13T13:30:34.480Z:COM:ocpp_rpc.c:1108:Available"}]
2019-12-13T13:30:34.515Z:COM:ocpp_rpc.c:1059:<- [3, "3", {}]
2019-12-13T13:30:34.523Z:COM:ocpp_rpc.c:1108:-> [2,"4","StatusNotification",{"connectorId":2,"errorCode":"NoError","status":"
2019-12-13T13:30:34.523Z:COM:ocpp_rpc.c:1108:Available"}]
2019-12-13T13:30:34.574Z:COM:ocpp_rpc.c:1059:<- [3, "4", {}]

2019-12-13T13:51:43.257Z:COM:ocpp_rpc.c:1108:-> [2,"8509","Heartbeat",{}]
2019-12-13T10:51:43.300Z:COM:ocpp_rpc.c:1059:<- [3, "8509", {"currentTime": "2019-12-13T09:51:44Z"}]
```

At first glance there seems to be no difference in the messages you have answered to and the ones of the above code, however I have noticed 2 things:

1. The Heartbeat interval (100 s) in your test is not respected
2. The Time in "currentTime" does not respect OCPP guidelines (also check the time stamp representation differences between your test and the logs I have provided)

Regarding the first item, either is already a faulty behaviour of the station or it is possible that it is caused by issue number 2.
Therefore, I would recommend you to follow OCPP guidelines and use UTC times and, most importantly, respect ISO 8601 (page 29 of OCPP 1.6 spec 2nd Edition). 
Try that and then let us know if it changed something.

I cant guarantee that this is the cause of the problems, because you answer with that time representation right in the beginning in the Boot confirmation message, but by experience, we had quite a few problems with some Vendors due to the time stamps, so I would give it a try.

All the best to you and happy Easter!

**Comment by OrangeTux** [comment]
Closed because of inactivity. Feel free to reopen if needed.

**Comment by pfirtelu** [comment]
Finally found the cause of this misbehavior, just in case anyone meets the same difficulty:
A Firmware upgrade from the manufacturer of this Charging Pile resolved the issue.

**Comment by OrangeTux** [comment]
Great! Thanks for coming back to this issue with this result. Any chance that you can disclose the charge point model and firmware?

**Comment by salvisolamartinell** [comment]
This is 4 years ago, but for future reference, if the central system is implemented using something like Python's websockets library, it has a default ping_interval = 20 and ping_timeout = 20. Together they are 40 s, so it may be that the charge point is not responding to websocket pings. This would raise an error `ConnectionClosedError: sent 1011 (internal error) keepalive ping timeout; no close frame received`, but maybe you haven't configured the logs properly.
