### ISSUE TITLE
how to implement Central to charging request like RequestStartTransaction

### ISSUE THREAD

**Issue by madhavsund** [mobilityhouse/ocpp#82]
how to invoke functions from central to charging point like for making 
RequestStartTransactionRequest

**Comment by OrangeTux** [comment]
I guess you want to send a 'RemoteStartTransaction'. That is explained in both #62 and #81 . Also #7 explains how to send a request from the central system to the charge point.

**Comment by madhavsund** [comment]
ok. thanks

**Comment by madhavsund** [comment]
I am struck here.. My use case is at any time the CSMS needs to send message to Charge point 
how to initiate from central to CP like RemoteStart in the middle 
not during connect  as
 `await asyncio.gather(cp.start(), cp.get_configuration())`

**Comment by OrangeTux** [comment]
I think this question is answered in [this comment](https://github.com/mobilityhouse/ocpp/issues/86#issuecomment-620205346) in #86 .
