### ISSUE TITLE
WebSocket Compression

### ISSUE THREAD

**Issue by madhavsund** [mobilityhouse/ocpp#83]
how websocket compression can be done on payload

**Comment by OrangeTux** [comment]
Compression is done by the websocket implementation  you use. The [examples](https://github.com/mobilityhouse/ocpp/tree/master/examples) are using the [websockets](https://websockets.readthedocs.io/) library. You can control compression with the `compression` attribute in the [websocket.client.connect()](https://websockets.readthedocs.io/en/stable/api.html#websockets.client.connect) and [websocket.server.serve()](https://websockets.readthedocs.io/en/stable/api.html#websockets.server.serve).

**Comment by madhavsund** [comment]
ok thanks
