### ISSUE TITLE
invoke charge point functions using message queue

### ISSUE THREAD

**Issue by madhavsund** [mobilityhouse/ocpp#84]
I need to invoke charge point functions(like AuthorizeToken)  depending on the messages  from message queue send by charge point GUI.. 
like 
 ```
   mq = sysv_ipc.MessageQueue(1234, sysv_ipc.IPC_CREAT)
    while True:
        message = mq.receive()
        print(message)
        Here need to invoke functions accordingly
```

is it feasible here?

**Comment by OrangeTux** [comment]
Sure, why would you think it is not feasible?

**Comment by madhavsund** [comment]
I am new toMessage queue, I tried like this inside main function
```
 mq = sysv_ipc.MessageQueue(1234, sysv_ipc.IPC_CREAT)
 while True:
       message = mq.receive()
       print(message)
       if(message == 'start'):
           await asyncio.gather(cp.start(),cp.send_start_transaction())
```
this runs on first incoming message and the control is not back and it hangs

**Comment by OrangeTux** [comment]
`cp.start()` is blocking, it only returns if the websocket connection is gone. So you should move that call outside of the `while` loop.

**Comment by madhavsund** [comment]
It worked ..Thanks a lot !!!
