### ISSUE TITLE
How to recieve OCPP messages from multiple clients simultaneously

### ISSUE THREAD

**Issue by guptaraghav1999** [mobilityhouse/ocpp#87]
In the example given in README, I found that if multiple clients send some message, the server was not able to receive them simultaneously. How can we make the server run on different asyncio loops for different clients so that it can serve multiple clients in parallel? Any help would be appreciated.  Thanks in advance!

**Comment by OrangeTux** [comment]
Hello. The server is able to handle multiple messages simultaneously. But it might that you've some other code that is blocking the event loop. Can you share your code?

Running multiple event loops is a bad idea. You'll quickly run in concurrency problems and problems with tasks being bound to different loop than they are executed it.

**Comment by OrangeTux** [comment]
I just wrote a CSMS that is a little bit more elaborate than the ones in the examples. It allows to connect multiple chargers. Maybe it helps. You can find it [here](https://github.com/mobilityhouse/ocpp/issues/86#issuecomment-620205346).
