### ISSUE TITLE
Is it possible to determine ocpp version?

### ISSUE THREAD

**Issue by MrMika96** [mobilityhouse/ocpp#89]
I am curious, is it possible to determine which version of OCPP charge point is using? For example, if we use protocols 1.2 or 1.5, you can tell them apart, becouse they using SOAP, so if request header having this field in it "urn://Ocpp/Cs/2010/08/" it`s OCPP 1.2 and if request header having this field "urn://Ocpp/Cs/2012/06/" it`s OCPP 1.5. Or if your central system can hanlde OCPP 2.0 you can handle older versions as well?

**Comment by OrangeTux** [comment]
A client must use the HTTP header `Sec-Websocket-Protocol` to specify the version of the protocol it's using. See section 3.1.2 of [the OCPP-J 1.6 specification](https://github.com/mobilityhouse/ocpp/blob/master/docs/v16/ocpp-j-1.6-specification.pdf).

**Comment by MrMika96** [comment]
Thanks for the answer!
