### ISSUE TITLE
Killer for the start() method

### ISSUE THREAD

**Issue by fassedou** [mobilityhouse/ocpp#93]
In the charge point class, is it possible to add a way to properly kill the infinite loop ? Just by adding a flag and a shutdown() method to change this flag, for instance.

Currently, whenever I want to stop my OCPP client, I can't do it cleanly because the thread where start() is running can't be stop properly.

Thanks !

**Comment by OrangeTux** [comment]
Thanks for your request @fassedou . I think it would be possible to add `ChargePoint.stop()` method that stop the loop in `ChargePoint.start()` .

I quicktly created an implementation. You can find it here: https://github.com/mobilityhouse/ocpp/commit/fad84bc673283a9a702277a59d7c19cf2d1d9162 It is currently untested though. But would something like that work for you?

**Comment by fassedou** [comment]
Thank you @OrangeTux for this
Something like this would definitively work for me, however I tried it but the code crashed right at the beginning on the line :
`_, pending = asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)`
With the error : 
`TypeError: cannot unpack non-iterable coroutine object` 

This is fixed by adding an `await` : 
`_, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)`

After this, an other error occurred, again right at the beginning of the execution:
`asyncio.exceptions.CancelledError` 

This is automatically raised when a task in cancelled, it just needs to be caught : 
```
async def start(self):
    """ Start listening on connection for inbound messages until `stop()`
    is called. """
    self._stop.clear()
    while not self._stop.is_set():
        tasks = [
            asyncio.create_task(self._read_connection()),
            asyncio.create_task(self._stop.wait()),
        ]
        _, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
        for task in pending:
            task.cancel()
            try:
                await task
            except asyncio.exceptions.CancelledError:
                pass
```

After this, everything worked just fine (although I only did some basic testings), thank you very much !

**Comment by maurerle** [comment]
Is it possible to add this feature to the implementation?

**Comment by timothy-cypress** [comment]
My team also encountered the need to terminate the ChargePoint. I am leaving this comment here to document how my colleague and I handled it for posterity.

Instead of waiting for PRs (https://github.com/mobilityhouse/ocpp/pull/339 and https://github.com/mobilityhouse/ocpp/commit/fad84bc673283a9a702277a59d7c19cf2d1d9162) to be approved or forking the repository then modifying the source code, we just created a new child class of `Chargepoint`, overrode the `start` function in `Chargepoint` class from `ocpp.v16` and added `stop` function. This let us create a websocket connection, do something, then shut it down. We used this to perform synthetic testing of our production OCPP server to ensure OCPP server websocket connection is working. 

I have included code below to show how what our child class looks like and how to simply start, send a heartbeat notification, then shut down the ChargePoint.ChargePoint

```python3
import asyncio
from ocpp.v16 import call, ChargePoint as cp

class ChargePoint(cp):

    async def heartbeat(self):
        """
        Heartbeat request
        Section 4.6, OCPP1.6 Specification
        """
        heartbeatReq = call.HeartbeatPayload()    
        
        response = await self.call(heartbeatReq)
        return response

    async def start(self):
        """
        Starts running ChargePoint to listen for websocket messages
        - This overrides the parent's start function which contains a forever loop
        """
        self.cp_task = asyncio.create_task(super().start())

    async def stop(self): 
        """
        Close down Chargepoint
        """

        # Stop chargepoint                
        is_cancel_success = self.cp_task.cancel()

        if is_cancel_success == False:
            print(f'Could not cancel task for chargepoint: {self.id}')
    
    async def main():
        URI = "ws://localhost:8888/CP_1"
        async with websockets.connect(URI, subprotocols=['ocpp1.6']) as ws:
            currentTime = datetime.utcnow()
            cp = ChargePoint("CP_1", ws)
            await cp.start()
            heartbeat_conf = await cp.heartbeat()
            await cp.stop()
    
    asyncio.run(main())
```

This is similar to the code example in the official docs except that now the ChargePoint class can be stopped with `cp.stop()`. In the [example here](https://ocpp.readthedocs.io/en/latest/README.html#charge-point), it would hang at 

```python3
await asyncio.gather(cp.start(), cp.send_boot_notification())
```

because `cp.start()` contains a [forever loop](https://github.com/mobilityhouse/ocpp/blob/75a8fb360e320b6cff34c33f22771252baf25db6/ocpp/charge_point.py#L127-L131) and control is never returned, so it just hangs.

I hope someone finds this useful!

**Comment by stStavropoulos** [comment]
> My team also encountered the need to terminate the ChargePoint. I am leaving this comment here to document how my colleague and I handled it for posterity.
> 
> Instead of waiting for PRs (#339 and [fad84bc](https://github.com/mobilityhouse/ocpp/commit/fad84bc673283a9a702277a59d7c19cf2d1d9162)) to be approved or forking the repository then modifying the source code, we just created a new child class of `Chargepoint`, overrode the `start` function in `Chargepoint` class from `ocpp.v16` and added `stop` function. This let us create a websocket connection, do something, then shut it down. We used this to perform synthetic testing of our production OCPP server to ensure OCPP server websocket connection is working.
> 
> I have included code below to show how what our child class looks like and how to simply start, send a heartbeat notification, then shut down the ChargePoint.ChargePoint
> 
> ```python
> import asyncio
> from ocpp.v16 import call, ChargePoint as cp
> 
> class ChargePoint(cp):
> 
>     async def heartbeat(self):
>         """
>         Heartbeat request
>         Section 4.6, OCPP1.6 Specification
>         """
>         heartbeatReq = call.HeartbeatPayload()    
>         
>         response = await self.call(heartbeatReq)
>         return response
> 
>     async def start(self):
>         """
>         Starts running ChargePoint to listen for websocket messages
>         - This overrides the parent's start function which contains a forever loop
>         """
>         self.cp_task = asyncio.create_task(super().start())
> 
>     async def stop(self): 
>         """
>         Close down Chargepoint
>         """
> 
>         # Stop chargepoint                
>         is_cancel_success = self.cp_task.cancel()
> 
>         if is_cancel_success == False:
>             print(f'Could not cancel task for chargepoint: {self.id}')
>     
> async def main():
>     URI = "ws://localhost:8888/CP_1"
>     async with websockets.connect(URI, subprotocols=['ocpp1.6']) as ws:
>         currentTime = datetime.utcnow()
>         cp = ChargePoint("CP_1", ws)
>         await cp.start()
>         heartbeat_conf = await cp.heartbeat()
>         await cp.stop()
>     
> asyncio.run(main())
> ```
> 
> This is similar to the code example in the official docs except that now the ChargePoint class can be stopped with `cp.stop()`. In the [example here](https://ocpp.readthedocs.io/en/latest/README.html#charge-point), it would hang at
> 
> ```python
> await asyncio.gather(cp.start(), cp.send_boot_notification())
> ```
> 
> because `cp.start()` contains a [forever loop](https://github.com/mobilityhouse/ocpp/blob/75a8fb360e320b6cff34c33f22771252baf25db6/ocpp/charge_point.py#L127-L131) and control is never returned, so it just hangs.
> 
> I hope someone finds this useful!

Hello! I used your solution and it works, but didn't you experience an error like this one whenever you stop:

INFO:websockets.server:connection closed
ERROR:websockets.server:connection handler failed

raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedOK: received 1000 (OK); then sent 1000 (OK)
INFO:websockets.server:connection closed
