### ISSUE TITLE
Python 3.8 warnings

### ISSUE THREAD

**Issue by adamchainz** [mobilityhouse/ocpp#95]
I'm seeing this warning on Python 3.8:

```
/.../lib/python3.8/site-packages/ocpp/charge_point.py:184: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  response = await asyncio.coroutine(handler)(**snake_case_payload)
```

Is there any reason not to convert the associated methods to `async def` ?

**Comment by OrangeTux** [comment]
Thanks for the report. This line executes the handlers that are registered for an action. Handlers can be both regular functions as well as async functions. E.g.:

``` python
@on("Heartbeat")
def on_heart_beat(*args, **kwargs):
    pass

@on("Heartbeat")
async def on_heart_beat(*args, **kwargs):
    pass
```

`response = await asyncio.coroutine(handler)(**snake_case_payload)` makes sure that that both version can be executed.
You state correctly that `asyncio.coroutine` is depricated. Therefore I think we should replace it with:

``` python
response = handler(**snake_case_payload)
if inspect.isawaitable(response):
                 response = await response
```

**Comment by laysauchoa** [comment]
cc @OrangeTux 
Hey, is someone working on this ticket?

**Comment by OrangeTux** [comment]
Nope.
