### ISSUE TITLE
Log All in server

### ISSUE THREAD

**Issue by mastin-zgz** [mobilityhouse/ocpp#97]
good morning,
The first thing to apologize since I am new on GitHub and programming in general. I would like to know if the server gives the option of being able to see everything in the log, not only the failures or errors, also the connections, and requests that it makes ...

Thank you very much for your time

A greeting!

**Comment by tropxy** [comment]
Hi,
Thanks for reaching us, regardless of your lack of your experience ;)

To answer your question, yes; if you implement the central system or a charge point handler, the code will print out the Request and Response messages as you can see here in the code:
send: https://github.com/mobilityhouse/ocpp/blob/6098908e6f7e51a355bcbeb3eda7479f73d6781c/ocpp/charge_point.py#L297

reception: https://github.com/mobilityhouse/ocpp/blob/6098908e6f7e51a355bcbeb3eda7479f73d6781c/ocpp/charge_point.py#L123

**Comment by OrangeTux** [comment]
I'd like to add to this that you can also enable debug logs by adding this to you project:

```
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by mastin-zgz** [comment]
@OrangeTux @tropxy  Thank you very much for your responses and patience.

@OrangeTux I have to put that line in my central system code?

Thanks!

**Comment by OrangeTux** [comment]
@mastin-zgz Yes. I also created a PR to have these lines in the examples by default. You can find it #98

**Comment by mastin-zgz** [comment]
Thanks @OrangeTux !!

It works perfect!
If I wanted to have the Centralsystem.py running and that I generated a file with all the log it would be like this, right?

`logging.basicConfig( level=logging.DEBUG, filename='example.log')`

Thanks for your time!

**Comment by OrangeTux** [comment]
I think so, yes.

**Comment by Ataraxiall** [comment]
Taking advantage of this post. Can you see how many connections are active on the server?

Thaks!

**Comment by OrangeTux** [comment]
> Can you see how many connections are active on the server?

No.As this library doesn't enforce you to use a specific websockets implementation this library cannot track that. 

But it's easy to track the number of connected chargers in the connection handler. If you're using  [websockets] it could look something like this:

``` python
charge_points_connected = 0

async def on_connect(websocket, path):
    """ For every new charge point that connects, create a ChargePoint instance
    and start listening for messages.

    """
    charge_point_id = path.strip('/')
    cp = ChargePoint(charge_point_id, websocket)
    
    charge_points_connected += 1
    try:
        await cp.start()
    finally:
        charge_points_connected -= 1
```

**Comment by Ataraxiall** [comment]
Sorry, I don't know if I understood you correctly.

That would go in the /websocket/server.py file?

Thank you!

**Comment by OrangeTux** [comment]
That is impossible for me to say. I don't know how your project looks like.
