### ISSUE TITLE
Websocket "Pong" error.

### ISSUE THREAD

**Issue by Ataraxiall** [mobilityhouse/ocpp#99]
Good morning,

First of all, congratulations on the OCPP server, it is very useful.

I wanted to ask you how to remove an error that continually jumps at me, the error is this.
```
`ERROR:ocpp:Unable to parse message: 'pong', it doesn't seem to be valid OCPP: Message is not valid JSON: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ocpp/messages.py", line 66, in unpack
    msg = json.loads(msg)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/ocpp/charge_point.py", line 136, in route_message
    msg = unpack(raw_msg)
  File "/usr/local/lib/python3.7/dist-packages/ocpp/messages.py", line 68, in unpack
    raise FormatViolationError(f'Message is not valid JSON: {e}')
ocpp.exceptions.FormatViolationError: Message is not valid JSON: Expecting value: line 1 column 1 (char 0)`
```

The "client" in my case is a node-red module, this module uses the "Pong" function to know if the server is operational (it is part of the websocket module).

Is there a way to fix/eliminate/igore this error?

Thank you

**Comment by OrangeTux** [comment]
My guess is that there is something wrong with the Node implementation of the Websocket protocol. 
I think that the Python code is sending `ping` as control frame, but the Node Red implementation returns `pong` as a data frame instead of control frame.

I suggest to fix this in your Node Red implementation.

Alternatively you can ignore `pong` data frames by overriding `ChargePoint.route_message()` with something like this:

``` python
class ChargePoint:
    ...
    async def route_message(self, raw_msg)
       if raw_message == 'pong':
           return

       try:
            msg = unpack(raw_msg)
        except OCPPError as e:
            LOGGER.exception("Unable to parse message: '%s', it doesn't seem "
                             "to be valid OCPP: %s", raw_msg, e)
            return
```

**Comment by tropxy** [comment]
I have also answered through email, but to keep the record here is a transcript of my mail:

```shell
Good morning,
 
Thank you for the kind words ;)
 
I have a few questions for you:
 
1. Is your client sending a Pong as response to a Ping or is it involuntarily sending a Pong?
2. Is your client sending a Pong as a Pong frame, i.e., with opcode = 0xA (as stated in the Websocket RFC https://tools.ietf.org/html/rfc6455#section-5.5.2)?
3. Is it possible to have a sniff of the packets exchanged between client and server, for example, through wireshark?
 
It is weird that you are experiencing that error, because the websockets lib that we use internally handles ping/pong requests, so right now I am assuming that the pong message may not be the Pong that is expected...
 
```

**Comment by proelke** [comment]
I've also seen these Pong messages from other implementations as well while implementing the proxy and integrating with other third party backends.

**Comment by OrangeTux** [comment]
Assuming that @Ataraxiall  is using  [Argonne-National-Laboratory](https://github.com/Argonne-National-Laboratory/node-red-contrib-ocpp) I think I found the problem.

The following snippet is taken from [ocpp/ocpp-cp-json.js](https://github.com/Argonne-National-Laboratory/node-red-contrib-ocpp/blob/f85c90a26d3ad228031c86e4733620f81b0bb795/ocpp/ocpp-cp-json.js#L149-L152):
``` javascript
    ws.on('ping', function(){
      debug('Got Ping');
      ws.send('pong');
    });
```

`ws.send` seems to send `pong` as a data frame. Instead the project should use [`ws.pong`](https://github.com/websockets/ws/blob/HEAD/doc/ws.md#websocketpongdata-mask-callback). Can you check if that is the problem @Ataraxiall ?

**Comment by Ataraxiall** [comment]
Thanks all,

@OrangeTux i change it and at the moment dont apear the error. Thanks!

**Comment by OrangeTux** [comment]
I reported the problem to the Node Red repo. I'll close this issue now.
